"use client";
/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Award, CheckCircle2, Circle, Download, ExternalLink, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Certificate = { certificate_no: string; authenticity_code: string; recipient_name: string; course_title: string; issued_at: string };
type CertificateRequest = { id: number; status: "pending" | "approved" | "rejected" | "cancelled"; review_note: string | null; created_at: string };
type Eligibility = { eligible: boolean; lessons_completed: number; lessons_total: number; quizzes_passed: number; quizzes_total: number; assignments_graded: number; assignments_total: number };
const SITE_URL = "https://burmesebridge.com";

export default function CourseCertificate({ locale, productId, userId }: { locale: string; productId: number; userId: string | null }) {
  const copy = locale === "zh" ? { heading:"课程证书",intro:"完成课时、通过测验并完成作业批改后，可提交教师审核。",issue:"申请证书审核",locked:"尚未满足申请条件",pending:"证书申请正在等待教师审核",rejected:"申请未通过",retry:"重新申请审核",download:"下载 PDF 证书",certify:"兹证明",completed:"已完成 BurmeseBridge 课程并通过审核",issued:"颁发日期",verify:"证书编号",authenticity:"防伪码",scan:"扫码验证证书",open:"在线验证",error:"暂时无法提交申请，请刷新资格状态后重试。",lessons:"完成全部课时",quizzes:"通过全部测验",assignments:"作业完成教师批改",waiting:"提交作业后需等待教师评分，评分完成后即可申请。" }
    : locale === "my" ? { heading:"သင်တန်းလက်မှတ်",intro:"သင်ခန်းစာ၊ စစ်ဆေးမှုနှင့် အိမ်စာစစ်ဆေးခြင်းများ ပြီးပါက ဆရာ၏အတည်ပြုချက်ကို လျှောက်ထားနိုင်သည်။",issue:"လက်မှတ်စစ်ဆေးမှု လျှောက်ရန်",locked:"လျှောက်ထားရန် သတ်မှတ်ချက် မပြည့်သေးပါ",pending:"လက်မှတ်လျှောက်ထားမှုကို ဆရာက စစ်ဆေးနေသည်",rejected:"လျှောက်ထားမှု အတည်မပြုပါ",retry:"ပြန်လည်လျှောက်ထားရန်",download:"PDF လက်မှတ် ဒေါင်းလုဒ်ရန်",certify:"ဤလက်မှတ်ဖြင့် အသိအမှတ်ပြုသည်",completed:"BurmeseBridge သင်တန်းကို ပြီးမြောက်၍ အတည်ပြုချက်ရရှိခဲ့သည်",issued:"ထုတ်ပေးသည့်ရက်",verify:"လက်မှတ်အမှတ်",authenticity:"အတုအပကာကွယ်ရေးကုဒ်",scan:"QR Code ဖြင့် လက်မှတ်စစ်ဆေးရန်",open:"အွန်လိုင်းမှ စစ်ဆေးရန်",error:"လျှောက်ထား၍မရသေးပါ။ အရည်အချင်းအခြေအနေကို ပြန်လည်စစ်ဆေးပါ။",lessons:"သင်ခန်းစာအားလုံး ပြီးစီးခြင်း",quizzes:"စစ်ဆေးမှုအားလုံး အောင်မြင်ခြင်း",assignments:"အိမ်စာအားလုံးကို ဆရာ စစ်ဆေးပြီးခြင်း",waiting:"အိမ်စာတင်ပြီးနောက် ဆရာ၏အမှတ်ပေးမှုကို စောင့်ရပါမည်။ အမှတ်ပေးပြီးပါက လျှောက်ထားနိုင်သည်။" }
    : { heading:"Course certificate",intro:"Complete the lessons, pass the quizzes and have all assignments graded before instructor review.",issue:"Request certificate review",locked:"Eligibility requirements not met",pending:"Your certificate request is awaiting instructor review",rejected:"Certificate request not approved",retry:"Request another review",download:"Download PDF certificate",certify:"This certifies that",completed:"has completed the BurmeseBridge course and passed review",issued:"Issued",verify:"Certificate number",authenticity:"Authenticity code",scan:"Scan to verify",open:"Verify online",error:"The request could not be submitted. Refresh the eligibility status and try again.",lessons:"Complete all lessons",quizzes:"Pass all quizzes",assignments:"Have all assignments graded",waiting:"After submitting assignments, wait for instructor grading. You can apply once grading is complete." };
  const [certificate,setCertificate]=useState<Certificate|null>(null),[request,setRequest]=useState<CertificateRequest|null>(null),[eligibility,setEligibility]=useState<Eligibility|null>(null),[qrCode,setQrCode]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const certificateRef=useRef<HTMLDivElement>(null);
  const verificationUrl=useMemo(()=>certificate?`${SITE_URL}/${locale}/certificate/${encodeURIComponent(certificate.authenticity_code||certificate.certificate_no)}`:"",[certificate,locale]);
  const load=useCallback(async()=>{if(!userId)return;const[{data:certificateData},{data:requestData},{data:eligibilityData}]=await Promise.all([supabase.from("knowledge_certificates").select("certificate_no,authenticity_code,recipient_name,course_title,issued_at").eq("product_id",productId).eq("user_id",userId).eq("status","active").maybeSingle(),supabase.from("knowledge_certificate_requests").select("id,status,review_note,created_at").eq("product_id",productId).eq("user_id",userId).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.rpc("get_knowledge_certificate_eligibility",{p_product_id:productId})]);setCertificate(certificateData as Certificate|null);setRequest(requestData as CertificateRequest|null);setEligibility(eligibilityData as Eligibility|null)},[productId,userId]);
  useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load()},[load]);
  useEffect(()=>{let active=true;if(!verificationUrl)return;void import("qrcode").then(({default:QRCode})=>QRCode.toDataURL(verificationUrl,{width:220,margin:1,errorCorrectionLevel:"M",color:{dark:"#0e5a49",light:"#fffdf8"}})).then(value=>{if(active)setQrCode(value)});return()=>{active=false}},[verificationUrl]);
  async function issue(){setBusy(true);setMessage("");const{error}=await supabase.rpc("request_knowledge_certificate",{p_product_id:productId,p_learner_note:null});if(error){setMessage(copy.error);await load()}else await load();setBusy(false)}
  async function waitForAssets(root:HTMLElement){const images=Array.from(root.querySelectorAll("img"));await Promise.all(images.map(image=>image.complete&&image.naturalWidth>0?Promise.resolve():new Promise<void>(resolve=>{image.addEventListener("load",()=>resolve(),{once:true});image.addEventListener("error",()=>resolve(),{once:true})})));await document.fonts.ready}
  async function download(){if(!certificateRef.current||!certificate||!qrCode)return;setBusy(true);try{await waitForAssets(certificateRef.current);const[{default:html2canvas},{jsPDF}]=await Promise.all([import("html2canvas-pro"),import("jspdf")]);const canvas=await html2canvas(certificateRef.current,{scale:2.5,backgroundColor:"#fffdf8",useCORS:true,logging:false});const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4",compress:true});pdf.addImage(canvas.toDataURL("image/png"),"PNG",0,0,297,210,undefined,"FAST");pdf.setProperties({title:`${certificate.course_title} — ${certificate.recipient_name}`,subject:`BurmeseBridge verified certificate ${certificate.certificate_no}`,author:"BurmeseBridge",keywords:`BurmeseBridge, certificate, ${certificate.certificate_no}`});pdf.save(`BurmeseBridge-${certificate.certificate_no}.pdf`)}finally{setBusy(false)}}
  const checks=eligibility?[{label:copy.lessons,done:eligibility.lessons_completed,total:eligibility.lessons_total},{label:copy.quizzes,done:eligibility.quizzes_passed,total:eligibility.quizzes_total},{label:copy.assignments,done:eligibility.assignments_graded,total:eligibility.assignments_total}]:[];
  return <section className="course-certificate"><header><Award size={22}/><div><h2>{copy.heading}</h2><p>{copy.intro}</p></div></header>{certificate?<><div className="certificate-sheet" ref={certificateRef}><div className="certificate-frame"><div className="certificate-brand"><img src="/brand-icon-1024.png" alt="" width="48" height="48"/><strong>Burmese<span>Bridge</span></strong></div><span className="certificate-label">CERTIFICATE OF COMPLETION</span><h2>{copy.certify}</h2><h1>{certificate.recipient_name}</h1><p>{copy.completed}</p><h3>{certificate.course_title}</h3><div className="certificate-authentication"><div className="certificate-metadata"><span>{copy.issued}<b>{new Date(certificate.issued_at).toLocaleDateString(locale)}</b></span><span><ShieldCheck size={18}/>{copy.verify}<b>{certificate.certificate_no}</b></span><span><ShieldCheck size={18}/>{copy.authenticity}<b>{certificate.authenticity_code}</b></span></div><div className="certificate-qr">{qrCode?<img src={qrCode} alt={copy.scan}/>:null}<span>{copy.scan}</span></div></div><footer>burmesebridge.com · admin@burmesebridge.com</footer></div></div><div className="certificate-actions"><button onClick={download} disabled={busy||!qrCode}><Download size={16}/>{busy?"…":copy.download}</button><a href={verificationUrl} target="_blank" rel="noreferrer"><ShieldCheck size={16}/>{copy.open}<ExternalLink size={13}/></a></div></>:request?.status==="pending"?<div className="certificate-request-status pending"><ShieldCheck size={19}/><strong>{copy.pending}</strong><small>{new Date(request.created_at).toLocaleString(locale)}</small></div>:<><div className="certificate-eligibility">{checks.map(item=>{const complete=item.total===0||item.done>=item.total;return <div className={complete?"complete":"incomplete"} key={item.label}>{complete?<CheckCircle2 size={18}/>:<Circle size={18}/>}<span>{item.label}</span><b>{item.done}/{item.total}</b></div>})}</div>{eligibility&&eligibility.assignments_graded<eligibility.assignments_total?<p className="certificate-waiting">{copy.waiting}</p>:null}<button onClick={issue} disabled={!userId||!eligibility?.eligible||busy}>{busy?"…":eligibility?.eligible?(request?.status==="rejected"?copy.retry:copy.issue):copy.locked}</button>{request?.status==="rejected"?<div className="certificate-request-status rejected"><strong>{copy.rejected}</strong>{request.review_note?<p>{request.review_note}</p>:null}</div>:null}</>}{message?<p className="verification-message">{message}</p>:null}</section>;
}
