"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { Award,Download,ShieldCheck } from "lucide-react";
import BrandLogo from "@/components/BrandLogo";
import { supabase } from "@/lib/supabase";
type Certificate={certificate_no:string;recipient_name:string;course_title:string;issued_at:string};
export default function CourseCertificate({locale,productId,userId,progress}:{locale:string;productId:number;userId:string|null;progress:number}){
 const copy=locale==="zh"?{heading:"课程证书",intro:"完成全部课时并通过所有测验后即可领取。",issue:"领取证书",locked:"完成课程后解锁",download:"下载 PDF 证书",certify:"兹证明",completed:"已完成 BurmeseBridge 课程",issued:"颁发日期",verify:"证书编号",error:"暂时无法颁发证书，请确认全部课程和测验均已完成。"}:locale==="my"?{heading:"သင်တန်းလက်မှတ်",intro:"သင်ခန်းစာအားလုံးပြီး၍ စစ်ဆေးမှုအားလုံးအောင်မြင်ပြီးနောက် ထုတ်ယူနိုင်သည်။",issue:"လက်မှတ်ထုတ်ယူရန်",locked:"သင်တန်းပြီးပါက ဖွင့်မည်",download:"PDF လက်မှတ် ဒေါင်းလုဒ်ရန်",certify:"ဤလက်မှတ်ဖြင့် အသိအမှတ်ပြုသည်",completed:"BurmeseBridge သင်တန်းကို ပြီးမြောက်ခဲ့သည်",issued:"ထုတ်ပေးသည့်ရက်",verify:"လက်မှတ်အမှတ်",error:"လက်မှတ်ထုတ်မရသေးပါ။ သင်ခန်းစာနှင့် စစ်ဆေးမှုအားလုံး ပြီးကြောင်း စစ်ဆေးပါ။"}:{heading:"Course certificate",intro:"Complete every lesson and pass all quizzes to claim your certificate.",issue:"Claim certificate",locked:"Unlocks after course completion",download:"Download PDF certificate",certify:"This certifies that",completed:"has completed the BurmeseBridge course",issued:"Issued",verify:"Certificate number",error:"The certificate could not be issued. Confirm all lessons and quizzes are complete."};
 const[certificate,setCertificate]=useState<Certificate|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const certificateRef=useRef<HTMLDivElement>(null);
 const load=useCallback(async()=>{if(!userId)return;const{data}=await supabase.from("knowledge_certificates").select("certificate_no,recipient_name,course_title,issued_at").eq("product_id",productId).eq("user_id",userId).maybeSingle();setCertificate(data as Certificate|null)},[productId,userId]);useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
 void load()},[load]);
 async function issue(){setBusy(true);setMessage("");const{data,error}=await supabase.rpc("issue_knowledge_certificate",{p_product_id:productId});if(error)setMessage(copy.error);else setCertificate(data as Certificate);setBusy(false)}
 async function download(){if(!certificateRef.current||!certificate)return;setBusy(true);try{const[{default:html2canvas},{jsPDF}]=await Promise.all([import("html2canvas-pro"),import("jspdf")]);const canvas=await html2canvas(certificateRef.current,{scale:2,backgroundColor:"#fffdf8",useCORS:true,logging:false});const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4",compress:true});pdf.addImage(canvas.toDataURL("image/jpeg",.94),"JPEG",0,0,297,210);pdf.save(`BurmeseBridge-${certificate.certificate_no}.pdf`)}finally{setBusy(false)}}
 return <section className="course-certificate"><header><Award size={22}/><div><h2>{copy.heading}</h2><p>{copy.intro}</p></div></header>{certificate?<><div className="certificate-sheet" ref={certificateRef}><div className="certificate-frame"><BrandLogo size={48}/><span className="certificate-label">CERTIFICATE OF COMPLETION</span><h2>{copy.certify}</h2><h1>{certificate.recipient_name}</h1><p>{copy.completed}</p><h3>{certificate.course_title}</h3><div><span>{copy.issued}<b>{new Date(certificate.issued_at).toLocaleDateString(locale)}</b></span><span><ShieldCheck size={18}/>{copy.verify}<b>{certificate.certificate_no}</b></span></div><footer>burmesebridge.eu.cc · admin@burmesebridge.eu.cc</footer></div></div><button onClick={download} disabled={busy}><Download size={16}/>{busy?"…":copy.download}</button></>:<button onClick={issue} disabled={!userId||progress<100||busy}>{progress<100?copy.locked:busy?"…":copy.issue}</button>}{message?<p className="verification-message">{message}</p>:null}</section>;
}
