"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { CheckCircle2,Headphones,RotateCcw,XCircle } from "lucide-react";
import { supabase } from "@/lib/supabase";
type Quiz={id:number;title_my:string|null;title_zh:string|null;title_en:string|null;passing_score:number};
type Question={id:number;question_type:"single"|"multiple"|"listening"|"ordering"|"fill"|"writing";prompt_my:string|null;prompt_zh:string|null;prompt_en:string|null;options:unknown;audio_url:string|null;position:number;points:number};
type Result={score:number;max_score:number;percentage:number;passed:boolean};
export default function QuizPanel({locale,lessonId,userId}:{locale:string;lessonId:number;userId:string|null}){
 const copy=locale==="zh"?{title:"随堂测验",empty:"本课没有测验",login:"登录后参加测验",submit:"提交测验",retry:"重新作答",passed:"已通过",failed:"未通过",score:"得分",select:"请选择答案",order:"顺序",answer:"填写答案",types:{single:"单选",multiple:"多选",listening:"听力",ordering:"排序",fill:"填空",writing:"书写"}}:locale==="my"?{title:"သင်ခန်းစာစစ်ဆေးမှု",empty:"စစ်ဆေးမှုမရှိပါ",login:"ဝင်ရောက်ပြီး ဖြေဆိုပါ",submit:"အဖြေတင်ရန်",retry:"ပြန်လည်ဖြေဆိုရန်",passed:"အောင်မြင်သည်",failed:"မအောင်မြင်ပါ",score:"ရမှတ်",select:"အဖြေရွေးပါ",order:"အစဉ်",answer:"အဖြေရေးပါ",types:{single:"တစ်ခုရွေး",multiple:"အများရွေး",listening:"နားထောင်",ordering:"အစဉ်စီ",fill:"ကွက်လပ်ဖြည့်",writing:"ရေးသား"}}:{title:"Lesson quiz",empty:"No quiz for this lesson",login:"Sign in to take the quiz",submit:"Submit quiz",retry:"Try again",passed:"Passed",failed:"Not passed",score:"Score",select:"Choose an answer",order:"Order",answer:"Write your answer",types:{single:"Single choice",multiple:"Multiple choice",listening:"Listening",ordering:"Ordering",fill:"Fill in",writing:"Writing"}};
 const[quiz,setQuiz]=useState<Quiz|null>(null);const[questions,setQuestions]=useState<Question[]>([]);const[answers,setAnswers]=useState<Record<number,unknown>>({});const[ordering,setOrdering]=useState<Record<number,Record<string,number>>>({});const[result,setResult]=useState<Result|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 const load=useCallback(async()=>{const{data:q}=await supabase.from("knowledge_quizzes").select("id,title_my,title_zh,title_en,passing_score").eq("lesson_id",lessonId).eq("status","published").order("id").limit(1).maybeSingle();setQuiz(q as Quiz|null);if(q){const{data}=await supabase.from("knowledge_quiz_questions").select("id,question_type,prompt_my,prompt_zh,prompt_en,options,audio_url,position,points").eq("quiz_id",q.id).order("position").order("id");setQuestions((data||[]) as Question[])}else setQuestions([])},[lessonId]);
 useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
 void load()},[load]);
 const local=(row:Quiz|Question,field:"title"|"prompt")=>{const value=row as unknown as Record<string,string|null>;const order=locale==="zh"?["zh","my","en"]:locale==="en"?["en","my","zh"]:["my","zh","en"];return order.map(s=>value[`${field}_${s}`]).find(Boolean)||""};
 const options=(question:Question)=>Array.isArray(question.options)?question.options.map(String):[];
 function toggleMultiple(id:number,value:string){const current=Array.isArray(answers[id])?(answers[id] as string[]):[];setAnswers(state=>({...state,[id]:current.includes(value)?current.filter(item=>item!==value):[...current,value]}))}
 function setRank(question:Question,value:string,rank:number){const next={...(ordering[question.id]||{}),[value]:rank};setOrdering(state=>({...state,[question.id]:next}));const ordered=Object.entries(next).sort((a,b)=>a[1]-b[1]).map(([item])=>item);setAnswers(state=>({...state,[question.id]:ordered}))}
 async function submit(event:FormEvent){event.preventDefault();if(!quiz||!userId)return;setBusy(true);setMessage("");const{data,error}=await supabase.rpc("submit_knowledge_quiz",{p_quiz_id:quiz.id,p_answers:Object.fromEntries(Object.entries(answers).map(([key,value])=>[String(key),value]))});if(error)setMessage(error.message);else setResult(data as Result);setBusy(false)}
 if(!quiz)return null;
 return <section className="quiz-panel"><h2>{copy.title}</h2><h3>{local(quiz,"title")}</h3>{result?<div className={`quiz-result ${result.passed?"passed":"failed"}`}>{result.passed?<CheckCircle2 size={28}/>:<XCircle size={28}/>}<strong>{result.passed?copy.passed:copy.failed}</strong><span>{copy.score}: {result.score}/{result.max_score} · {result.percentage}%</span><button onClick={()=>{setResult(null);setAnswers({});setOrdering({})}}><RotateCcw size={15}/>{copy.retry}</button></div>:userId?<form onSubmit={submit}>{questions.map((question,index)=>{const list=options(question);return <fieldset key={question.id}><legend><span>{index+1}</span><b>{local(question,"prompt")}</b><small>{copy.types[question.question_type]} · {question.points}</small></legend>{question.audio_url?<audio controls preload="none" src={question.audio_url}><Headphones/></audio>:null}{["single","listening"].includes(question.question_type)?<div className="quiz-options">{list.map(item=><label key={item}><input type="radio" name={`q-${question.id}`} checked={answers[question.id]===item} onChange={()=>setAnswers(state=>({...state,[question.id]:item}))}/><span>{item}</span></label>)}</div>:null}{question.question_type==="multiple"?<div className="quiz-options">{list.map(item=><label key={item}><input type="checkbox" checked={Array.isArray(answers[question.id])&&(answers[question.id] as string[]).includes(item)} onChange={()=>toggleMultiple(question.id,item)}/><span>{item}</span></label>)}</div>:null}{question.question_type==="ordering"?<div className="quiz-ordering">{list.map(item=><label key={item}><select value={ordering[question.id]?.[item]||""} onChange={event=>setRank(question,item,Number(event.target.value))}><option value="">—</option>{list.map((_,rank)=><option value={rank+1} key={rank}>{rank+1}</option>)}</select><span>{item}</span></label>)}</div>:null}{["fill","writing"].includes(question.question_type)?<textarea value={String(answers[question.id]||"")} onChange={event=>setAnswers(state=>({...state,[question.id]:event.target.value}))} placeholder={copy.answer}/>:null}</fieldset>})}<button disabled={busy||!questions.length}>{busy?"…":copy.submit}</button></form>:<p>{copy.login}</p>}{message?<p className="verification-message">{message}</p>:null}</section>;
}
