"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Gavel, Send } from "lucide-react";
import { supabase } from "@/lib/supabase";
type Appeal={id:number;action_type:string;action_reference:string|null;reason:string;status:string;review_note:string|null;created_at:string};
export default function AppealsPage(){const locale=String(useParams().locale||"my");const router=useRouter();const [items,setItems]=useState<Appeal[]>([]);const [type,setType]=useState("content_removed");const [ref,setRef]=useState("");const [reason,setReason]=useState("");const [message,setMessage]=useState("");const c=locale==="zh"?{title:"申诉中心",intro:"如果你认为内容处理、账号封禁或认证结果有误，可以在这里提交申诉。",type:"申诉类型",ref:"相关编号（可选）",reason:"详细说明（至少10个字）",send:"提交申诉",sent:"申诉已提交",empty:"暂无申诉记录",types:{content_removed:"内容被删除",account_banned:"账号被封禁",verification_rejected:"认证被拒绝",other:"其他"}}:locale==="my"?{title:"အယူခံတင်ရန်",intro:"ဆုံးဖြတ်ချက် မှားသည်ဟု ထင်ပါက အယူခံတင်နိုင်သည်။",type:"အမျိုးအစား",ref:"ရည်ညွှန်းနံပါတ်",reason:"အသေးစိတ်အကြောင်းပြချက်",send:"ပို့မည်",sent:"အယူခံတင်ပြီးပါပြီ",empty:"အယူခံ မရှိသေးပါ",types:{content_removed:"ပို့စ်ဖျက်ခံရ",account_banned:"အကောင့်ပိတ်ခံရ",verification_rejected:"အတည်ပြုချက်ပယ်ချ",other:"အခြား"}}:{title:"Appeals",intro:"Submit an appeal if you believe a moderation, ban, or verification decision was incorrect.",type:"Appeal type",ref:"Related reference (optional)",reason:"Explain your appeal (at least 10 characters)",send:"Submit appeal",sent:"Appeal submitted",empty:"No appeals yet",types:{content_removed:"Content removed",account_banned:"Account banned",verification_rejected:"Verification rejected",other:"Other"}};
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace(`/${locale}/login`);return}const{data}=await supabase.from("moderation_appeals").select("id,action_type,action_reference,reason,status,review_note,created_at").eq("user_id",user.id).order("created_at",{ascending:false});setItems((data||[]) as Appeal[])}useEffect(()=>{void load()},[]);
async function submit(e:FormEvent){e.preventDefault();if(reason.trim().length<10)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error}=await supabase.from("moderation_appeals").insert({user_id:user.id,action_type:type,action_reference:ref.trim()||null,reason:reason.trim()});if(error)setMessage(error.message);else{setReason("");setRef("");setMessage(c.sent);await load()}}
return <main className="appeals-page"><header><span><Gavel size={22}/></span><div><h1>{c.title}</h1><p>{c.intro}</p></div></header><form className="appeal-form" onSubmit={submit}><label>{c.type}<select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(c.types).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>{c.ref}<input value={ref} onChange={e=>setRef(e.target.value)}/></label><label>{c.reason}<textarea minLength={10} maxLength={1500} required value={reason} onChange={e=>setReason(e.target.value)}/></label>{message&&<p>{message}</p>}<button><Send size={16}/>{c.send}</button></form><section className="appeal-history">{items.length===0&&<div className="feedCard">{c.empty}</div>}{items.map(x=><article className="feedCard" key={x.id}><div><strong>{c.types[x.action_type as keyof typeof c.types]||x.action_type}</strong><span className={`appeal-status is-${x.status}`}>{x.status}</span></div><p>{x.reason}</p>{x.review_note&&<blockquote>{x.review_note}</blockquote>}<time>{new Date(x.created_at).toLocaleString()}</time></article>)}</section></main>}
