import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BookOpenCheck, CheckCircle2, Download, Headphones, Mic2, PenLine, PlayCircle, BookOpenText } from "lucide-react";
import { hskCourses, hskSkills, type HskSkill } from "@/lib/hskCourses";

const icons = { listening: Headphones, speaking: Mic2, reading: BookOpenText, writing: PenLine };
export default async function HskCoursePage({params}:{params:Promise<{locale:string;level:string;skill:string}>}){
  const {locale,level:rawLevel,skill:rawSkill}=await params; const level=Number(rawLevel); const skill=rawSkill as HskSkill;
  if(!Number.isInteger(level)||level<1||level>6||!hskSkills.includes(skill)) notFound();
  const course=hskCourses.find(item=>item.level===level&&item.skill===skill)!; const Icon=icons[skill]; const zh=locale==="zh"; const my=locale==="my";
  const names:Record<HskSkill,string>=zh?{listening:"听力",speaking:"口语",reading:"阅读",writing:"书写"}:my?{listening:"နားထောင်ခြင်း",speaking:"ပြောဆိုခြင်း",reading:"ဖတ်ရှုခြင်း",writing:"ရေးသားခြင်း"}:{listening:"Listening",speaking:"Speaking",reading:"Reading",writing:"Writing"};
  const modules=zh?["诊断与学习目标","核心词汇和语言点","标准发音与示范","情景训练与即时练习","综合任务与作业"]:my?["အဆင့်စစ်ဆေးခြင်းနှင့် ရည်မှန်းချက်","အဓိကဝေါဟာရနှင့် ဘာသာစကားအချက်များ","စံအသံထွက်နှင့် နမူနာ","အခြေအနေအလိုက် လေ့ကျင့်ခန်း","ပေါင်းစပ်တာဝန်နှင့် အိမ်စာ"]:["Diagnostic and goals","Core vocabulary and language points","Standard pronunciation and model","Scenario practice and checks","Integrated task and homework"];
  return <main className="hsk-course"><Link href={`/${locale}/videos/hsk`}><ArrowLeft size={16}/>{zh?"返回课程体系":my?"သင်တန်းစာရင်းသို့":"Back to curriculum"}</Link><header><Icon size={30}/><div><span>HSK {level} · 4Skill</span><h1>{names[skill]}</h1><p>{course.focus[zh?"zh":my?"my":"en"]}</p></div></header><div className="hsk-course-grid"><section><div className="hsk-course-placeholder"><PlayCircle size={48}/><strong>{zh?"分级视频课程":my?"အဆင့်လိုက် ဗီဒီယိုသင်ခန်းစာ":"Graded video lessons"}</strong><p>{zh?"视频只使用来源明确、发音可靠并允许嵌入的课程。管理员可按课时持续发布。":my?"ရင်းမြစ်ရှင်းလင်း၊ အသံထွက်မှန်ကန်ပြီး Embed ခွင့်ရှိသော ဗီဒီယိုများကိုသာ ထည့်သွင်းမည်။":"Videos are limited to traceable sources with reliable pronunciation and embedding permission."}</p></div><article><h2>{zh?"课程结构":my?"သင်တန်းဖွဲ့စည်းပုံ":"Course structure"}</h2>{modules.map((item,index)=><div key={item}><CheckCircle2 size={18}/><span><b>{index+1}</b>{item}</span></div>)}</article></section><aside><h2><BookOpenCheck size={19}/>{zh?"学习与作业":my?"လေ့လာမှုနှင့် အိမ်စာ":"Learning & homework"}</h2><p>{course.lessons} {zh?"个循序渐进课时":my?"ဆင့်ကဲသင်ခန်းစာ":"progressive lessons"}</p><ul><li>{zh?"课前词汇清单":my?"သင်ခန်းစာမတိုင်မီ ဝေါဟာရစာရင်း":"Pre-lesson vocabulary"}</li><li>{zh?"视频字幕与文本":my?"ဗီဒီယိုစာတန်းနှင့် စာသား":"Video transcript and captions"}</li><li>{zh?"每课即时练习":my?"သင်ခန်းစာတိုင်း လေ့ကျင့်ခန်း":"Lesson checks"}</li><li>{zh?"可下载作业附件":my?"Download လုပ်နိုင်သော အိမ်စာဖိုင်":"Downloadable homework"}</li><li>{zh?"阶段复习和结课测验":my?"အဆင့်လိုက် ပြန်လည်လေ့လာမှုနှင့် စာမေးပွဲ":"Reviews and final check"}</li></ul><button disabled><Download size={16}/>{zh?"作业随课时发布":my?"အိမ်စာကို သင်ခန်းစာနှင့်အတူ ထုတ်ဝေမည်":"Homework is attached per lesson"}</button></aside></div></main>;
}
