import Link from "next/link";
import { ArrowLeft, BookOpenText, Search } from "lucide-react";
import VocabularySpeakButton from "@/components/hsk/VocabularySpeakButton";

type Entry={hanzi:string;pinyin:string,meaning:string};
const PAGE_SIZE=50;
async function loadWords(level:number):Promise<Entry[]>{
  const response=await fetch(`https://raw.githubusercontent.com/tnm/hsk/main/public/data/hsk${level}.csv`,{next:{revalidate:86400}});
  if(!response.ok)throw new Error("Vocabulary source unavailable");
  return (await response.text()).split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const first=line.indexOf(","),second=line.indexOf(",",first+1);return{hanzi:line.slice(0,first).trim(),pinyin:line.slice(first+1,second).trim(),meaning:line.slice(second+1).trim()}}).filter(item=>item.hanzi&&item.pinyin);
}
export default async function HskVocabularyPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{level?:string;q?:string;page?:string}>}){
  const{locale}=await params;const query=await searchParams;const level=Math.min(6,Math.max(1,Number(query.level)||1));const q=(query.q||"").trim();const page=Math.max(1,Number(query.page)||1);const zh=locale==="zh",my=locale==="my";
  const copy=zh?{eyebrow:"完整开放词库",title:"HSK 1–6 词汇卡片",intro:"已接入六个等级的完整开放词表。搜索汉字、拼音或英文释义，并使用标准普通话朗读。",search:"搜索汉字、拼音或英文",submit:"搜索",words:"个词条",source:"数据来源与许可证",back:"返回四技能课程",empty:"没有匹配的词条",previous:"上一页",next:"下一页",speak:"播放发音"}:my?{eyebrow:"Open Vocabulary အပြည့်အစုံ",title:"HSK ၁–၆ ဝေါဟာရကတ်များ",intro:"HSK အဆင့်ခြောက်ဆင့်၏ Open Vocabulary အပြည့်အစုံကို ထည့်သွင်းထားသည်။ တရုတ်စာလုံး၊ Pinyin သို့မဟုတ် English အဓိပ္ပာယ်ဖြင့် ရှာပြီး စံတရုတ်အသံထွက်ကို နားထောင်ပါ။",search:"တရုတ်စာလုံး၊ Pinyin သို့မဟုတ် English ရှာရန်",submit:"ရှာရန်",words:" ဝေါဟာရ",source:"ဒေတာရင်းမြစ်နှင့် လိုင်စင်",back:"ဘာသာစွမ်းရည်လေးမျိုးသို့",empty:"ကိုက်ညီသော ဝေါဟာရမရှိပါ",previous:"ရှေ့စာမျက်နှာ",next:"နောက်စာမျက်နှာ",speak:"အသံထွက်ဖွင့်ရန်"}:{eyebrow:"Complete open vocabulary",title:"HSK 1–6 vocabulary cards",intro:"The complete open vocabulary sets for all six HSK levels are connected. Search characters, pinyin or English meaning and hear Mandarin pronunciation.",search:"Search character, pinyin or English",submit:"Search",words:" entries",source:"Data source and license",back:"Back to four-skill courses",empty:"No matching entries",previous:"Previous",next:"Next",speak:"Play pronunciation"};
  let words:Entry[]=[];try{words=await loadWords(level)}catch{}const needle=q.toLocaleLowerCase();const filtered=needle?words.filter(item=>`${item.hanzi} ${item.pinyin} ${item.meaning}`.toLocaleLowerCase().includes(needle)):words;const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const current=Math.min(page,pages);const visible=filtered.slice((current-1)*PAGE_SIZE,current*PAGE_SIZE);const href=(nextPage:number)=>`/${locale}/videos/hsk/vocabulary?level=${level}&q=${encodeURIComponent(q)}&page=${nextPage}`;
  return <main className="hsk-vocabulary-page"><Link className="hsk-vocabulary-back" href={`/${locale}/videos/hsk`}><ArrowLeft size={16}/>{copy.back}</Link><header><span><BookOpenText size={18}/>{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p></header><nav aria-label="HSK levels">{[1,2,3,4,5,6].map(item=><Link className={item===level?"active":""} href={`/${locale}/videos/hsk/vocabulary?level=${item}`} key={item}>HSK {item}</Link>)}</nav><section className="hsk-vocabulary-toolbar"><div><b>HSK {level}</b><span>{filtered.length}{copy.words}</span></div><form><input type="hidden" name="level" value={level}/><Search size={17}/><input name="q" defaultValue={q} placeholder={copy.search}/><button>{copy.submit}</button></form></section>{visible.length?<section className="hsk-vocabulary-grid">{visible.map((item,index)=><article key={`${item.hanzi}-${index}`}><div><strong>{item.hanzi}</strong><VocabularySpeakButton text={item.hanzi} label={copy.speak}/></div><b>{item.pinyin}</b><p>{item.meaning}</p></article>)}</section>:<p className="hsk-vocabulary-empty">{copy.empty}</p>}<footer className="hsk-vocabulary-pagination"><Link aria-disabled={current<=1} href={current<=1?"#":href(current-1)}>{copy.previous}</Link><span>{current} / {pages}</span><Link aria-disabled={current>=pages} href={current>=pages?"#":href(current+1)}>{copy.next}</Link></footer><aside><a href={`https://github.com/tnm/hsk/blob/main/public/data/hsk${level}.csv`} target="_blank" rel="noreferrer">{copy.source}: HSK Cards</a><span>MIT License · © Ted Nyman</span></aside></main>;
}
