"use client";
import {useCallback,useEffect,useState}from"react";
import {useParams}from"next/navigation";
import {BadgeCheck,BriefcaseBusiness,MapPin}from"lucide-react";
import AdminGuard from"@/components/admin/AdminGuard";
import AdminSidebar from"@/components/admin/AdminSidebar";
import{supabase}from"@/lib/supabase";

type Verification="unverified"|"reviewed"|"verified";
type Job={id:number;title_my:string|null;title_zh:string|null;title_en:string|null;employer_name:string|null;employer_registration:string|null;job_location:string|null;salary_details:string|null;application_contact:string|null;recruitment_verification:Verification;recruitment_review_note:string|null;created_at:string};

export default function AdminJobsPage(){return <AdminGuard><JobReviews/></AdminGuard>}
function JobReviews(){const locale=String(useParams().locale||"en");const[items,setItems]=useState<Job[]>([]),[filter,setFilter]=useState<Verification>("unverified"),[isAdmin,setIsAdmin]=useState(false),[message,setMessage]=useState("");const c=locale==="zh"?{title:"招聘审核中心",empty:"该状态暂无职位",employer:"雇主",registration:"登记/许可",location:"地点",salary:"工资",contact:"申请方式",note:"审核说明",review:"标记已审核",verify:"管理员核验",return:"退回未核验"}:locale==="my"?{title:"အလုပ်ကြော်ငြာ စိစစ်ရေး",empty:"ဤအခြေအနေတွင် အလုပ်မရှိပါ",employer:"အလုပ်ရှင်",registration:"မှတ်ပုံတင်/လိုင်စင်",location:"နေရာ",salary:"လစာ",contact:"လျှောက်ထားရန်",note:"စိစစ်မှတ်ချက်",review:"စိစစ်ပြီး",verify:"Admin အတည်ပြု",return:"မစိစစ်ရသေးအဖြစ်"}:{title:"Job review center",empty:"No jobs with this status",employer:"Employer",registration:"Registration/licence",location:"Location",salary:"Salary",contact:"Apply",note:"Review note",review:"Mark reviewed",verify:"Admin verify",return:"Return to unverified"};
const load=useCallback(async()=>{const{data,error}=await supabase.from("news").select("id,title_my,title_zh,title_en,employer_name,employer_registration,job_location,salary_details,application_contact,recruitment_verification,recruitment_review_note,created_at").eq("category","jobs").eq("recruitment_verification",filter).order("created_at",{ascending:false});if(error)setMessage(error.message);else setItems((data||[])as Job[])},[filter]);
useEffect(()=>{void load();supabase.auth.getUser().then(async({data})=>{if(!data.user)return;const{data:profile}=await supabase.from("profiles").select("role").eq("id",data.user.id).single();setIsAdmin(profile?.role==="admin")})},[load]);
async function review(id:number,value:Verification){const note=prompt(c.note)||null;const{error}=await supabase.from("news").update({recruitment_verification:value,recruitment_review_note:note}).eq("id",id).eq("category","jobs");if(error)setMessage(error.message);else{setMessage("");await load()}}
function title(x:Job){return locale==="zh"?x.title_zh||x.title_my||x.title_en:locale==="en"?x.title_en||x.title_my||x.title_zh:x.title_my||x.title_zh||x.title_en}
return <div className="adminShell"><AdminSidebar/><main className="adminContent"><header className="admin-report-head"><div><BriefcaseBusiness/><h1>{c.title}</h1></div><div>{(["unverified","reviewed","verified"]as Verification[]).map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></header>{message&&<p className="admin-access-message" role="alert">{message}</p>}<div className="admin-job-list">{!items.length&&<div className="feedCard">{c.empty}</div>}{items.map(x=><article className="feedCard admin-job-card" key={x.id}><header><div><span className={`job-verification is-${x.recruitment_verification}`}>{x.recruitment_verification}</span><h2>{title(x)}</h2></div><time>{new Date(x.created_at).toLocaleDateString()}</time></header><dl><div><dt>{c.employer}</dt><dd>{x.employer_name||"—"}</dd></div><div><dt>{c.registration}</dt><dd>{x.employer_registration||"—"}</dd></div><div><dt><MapPin size={13}/>{c.location}</dt><dd>{x.job_location||"—"}</dd></div><div><dt>{c.salary}</dt><dd>{x.salary_details||"—"}</dd></div><div className="wide"><dt>{c.contact}</dt><dd>{x.application_contact||"—"}</dd></div></dl>{x.recruitment_review_note&&<blockquote>{x.recruitment_review_note}</blockquote>}<footer><button onClick={()=>review(x.id,"unverified")}>{c.return}</button>{x.recruitment_verification==="unverified"&&<button onClick={()=>review(x.id,"reviewed")}>{c.review}</button>}{isAdmin&&x.recruitment_verification!=="verified"&&<button className="primary" onClick={()=>review(x.id,"verified")}><BadgeCheck size={16}/>{c.verify}</button>}</footer></article>)}</div></main></div>}
