"use client";

import { useEffect, useState } from "react";
import { BadgeCheck, Pencil, UserRound } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Request = { id: number; requested_badge: "student" | "teacher" | "company" | "author"; evidence: string; status: "pending" | "approved" | "rejected"; review_note: string | null; created_at: string };
type ApplicationKind = Request["requested_badge"];

export default function AccountProfilePanel({ locale, userId, email, initialName, nameUpdatedAt, verified }: { locale: string; userId: string; email: string; initialName: string; nameUpdatedAt: string | null; verified: boolean }) {
  const copy = locale === "zh" ? {
    title: "个人资料与认证", name: "显示名称", change: "修改名称", rule: "显示名称每 30 天只能修改一次。", next: "下次可修改日期", save: "保存名称", cooldown: "显示名称尚在 30 天修改冷却期内。", verify: "申请教师、作者等身份认证", verifyCopy: "选择申请类型，完整阅读对应规则制度并提交资料。审核通过后，才可获得相应的 BurmeseBridge 平台身份标识或证件。", student: "学生", teacher: "教师", company: "企业", author: "作者", evidence: "身份说明、经历、所属机构或证明链接", submit: "提交申请", pending: "申请正在审核中", approved: "身份已经通过认证", rejected: "已拒绝", history: "申请记录", termsTitle: "申请规则与制度", termsHint: "请在下方滚动阅读完整条款至底部。阅读完成后才能勾选同意。", termsEnd: "已读完全部条款", readConsent: "我已阅读、了解并同意以上规则制度", termsRequired: "请先滚动阅读到底部并勾选同意后再提交申请",
  } : locale === "my" ? {
    title: "ကိုယ်ရေးအချက်အလက်နှင့် အတည်ပြုခြင်း", name: "ဖော်ပြမည့်အမည်", change: "အမည်ပြောင်းရန်", rule: "ဖော်ပြမည့်အမည်ကို ရက် ၃၀ လျှင် တစ်ကြိမ်သာ ပြောင်းနိုင်သည်။", next: "နောက်တစ်ကြိမ် ပြောင်းနိုင်မည့်ရက်", save: "အမည်သိမ်းမည်", cooldown: "အမည်ပြောင်းရန် ရက် ၃၀ ပြည့်ရမည်။", verify: "ဆရာ၊ စာရေးသူ စသည်တို့အဖြစ် လျှောက်ထားရန်", verifyCopy: "လျှောက်ထားမည့်အမျိုးအစားကို ရွေးပြီး သက်ဆိုင်ရာ စည်းမျဉ်းများကို အဆုံးအထိ ဖတ်ကာ အချက်အလက်တင်ပြပါ။ အတည်ပြုပြီးမှ BurmeseBridge ပလက်ဖောင်းအတွင်း အမှတ်အသား သို့မဟုတ် ကတ် ရရှိမည်။", student: "ကျောင်းသား", teacher: "ဆရာ", company: "ကုမ္ပဏီ", author: "စာရေးသူ", evidence: "ကိုယ်ရေးအထောက်အထား၊ အတွေ့အကြုံ၊ အဖွဲ့အစည်း သို့မဟုတ် အထောက်အထားလင့်ခ်", submit: "လျှောက်ထားမည်", pending: "လျှောက်ထားချက်ကို စိစစ်နေသည်", approved: "Identity ကို အတည်ပြုပြီးပါပြီ", rejected: "အတည်မပြုပါ", history: "လျှောက်ထားမှုမှတ်တမ်း", termsTitle: "လျှောက်ထားမှု စည်းမျဉ်းများ", termsHint: "အောက်ပါ စည်းမျဉ်းအားလုံးကို အောက်ဆုံးအထိ လှိမ့်ဖတ်ပြီးမှ သဘောတူနိုင်ပါမည်။", termsEnd: "စည်းမျဉ်းအားလုံး ဖတ်ပြီးပါပြီ", readConsent: "စည်းမျဉ်းများကို ဖတ်ရှုနားလည်ပြီး သဘောတူပါသည်", termsRequired: "အောက်ဆုံးအထိ ဖတ်ပြီး သဘောတူမှ လျှောက်ထားနိုင်ပါမည်",
  } : {
    title: "Profile and verification", name: "Display name", change: "Change name", rule: "Your display name can be changed once every 30 days.", next: "Next change available", save: "Save name", cooldown: "Your display name is still within the 30-day cooldown.", verify: "Apply for teacher, author, or other verification", verifyCopy: "Choose an application type, read its complete rules, and submit supporting information. A BurmeseBridge platform badge or ID is issued only after approval.", student: "Student", teacher: "Teacher", company: "Company", author: "Author", evidence: "Identity details, experience, organization, or supporting links", submit: "Submit application", pending: "Application under review", approved: "Identity verified", rejected: "Rejected", history: "Application history", termsTitle: "Application rules", termsHint: "Scroll through the complete rules below. The consent checkbox unlocks only after you reach the end.", termsEnd: "All rules read", readConsent: "I have read, understood, and agree to these rules", termsRequired: "Read to the end and tick consent before submitting",
  };

  const terms = locale === "zh" ? {
    student: ["学生认证用于记录你在 BurmeseBridge 私立学习平台内的学习身份。", "申请人必须提供真实、可核验的资料，不得冒用他人身份、伪造文件或重复申请。", "学生证仅是本站内部学习身份凭证，不是政府身份证、学历、学位或任何政府教育机构认证。", "平台可因资料失实、账号滥用或违反社区规则而拒绝、暂停或撤销认证。"],
    teacher: ["教师认证用于确认申请人已通过 BurmeseBridge 的内部教师审核，并可能在本站承担经批准的课程或班级教学工作。", "申请人应提交真实的教学经历、课程能力、所属机构或其他可核验材料，并配合 Admin 的补充审核。", "教师证仅证明本站认证的就职教师身份，不是教师资格证、执业许可、学历证明，也不代表任何政府教育机构或官方资格。", "教师必须遵守课程质量、学生安全、隐私、知识产权和平台内容审核制度；不得以本站名义作政府或官方授权宣传。", "Admin 拥有最终审批、签发、暂停和撤销权；认证不保证就业、收入、课程上线或任何第三方合作。"],
    company: ["企业认证用于记录企业或机构在 BurmeseBridge 平台提交的公开身份信息。", "申请人必须是有权代表该实体的人员，并提供真实的注册名称、联系方式和证明材料。", "企业认证不构成政府许可、行业资质、雇主背书或 BurmeseBridge 对其经营行为的保证。", "不得发布欺诈、歧视、违法招聘、收费陷阱或侵犯他人权益的内容；资料变化应及时更新。"],
    author: ["作者认证用于标识在 BurmeseBridge 发布原创或已获合法授权内容的创作者。", "申请人必须对提交内容拥有版权或明确授权，不得抄袭、盗用、误导署名或提交侵犯第三方权利的内容。", "作者标识只代表本站内部审核状态，不是出版机构、政府文化机构或版权登记证明。", "作者应遵守引用、隐私、未成年人保护和内容安全规则；平台可下架内容并暂停或撤销认证。"],
  } : locale === "my" ? {
    student: ["ကျောင်းသားအတည်ပြုခြင်းသည် BurmeseBridge ပုဂ္ဂလိကသင်ယူရေးပလက်ဖောင်းအတွင်း သင်ယူသူအဖြစ် မှတ်တမ်းတင်ရန်သာ ဖြစ်သည်။", "လျှောက်ထားသူသည် မှန်ကန်ပြီး စစ်ဆေးနိုင်သော အချက်အလက်များကို ပေးရမည်။ အခြားသူ၏အမည်သုံးခြင်း၊ စာရွက်စာတမ်းအတုလုပ်ခြင်းနှင့် ထပ်မံလျှောက်ထားခြင်း မပြုရ။", "ကျောင်းသားကတ်သည် ပလက်ဖောင်းအတွင်းသုံး အထောက်အထားသာဖြစ်ပြီး အစိုးရ ID၊ ဘွဲ့ သို့မဟုတ် အစိုးရပညာရေးအဖွဲ့၏ အသိအမှတ်ပြုမှု မဟုတ်ပါ။", "အချက်အလက်မမှန်ခြင်း၊ အကောင့်အလွဲသုံးခြင်း သို့မဟုတ် စည်းမျဉ်းချိုးဖောက်ခြင်းရှိပါက အတည်ပြုမှုကို ငြင်းပယ်၊ ရပ်ဆိုင်း သို့မဟုတ် ရုပ်သိမ်းနိုင်သည်။"],
    teacher: ["ဆရာအတည်ပြုခြင်းသည် လျှောက်ထားသူသည် BurmeseBridge ၏ အတွင်းပိုင်း ဆရာစစ်ဆေးမှုကို ဖြတ်ကျော်ပြီး ပလက်ဖောင်းအတွင်း အတည်ပြုထားသော သင်ကြားသူဖြစ်နိုင်ကြောင်းသာ မှတ်တမ်းတင်သည်။", "သင်ကြားမှုအတွေ့အကြုံ၊ သင်တန်းစွမ်းရည်၊ အဖွဲ့အစည်း သို့မဟုတ် စစ်ဆေးနိုင်သော အထောက်အထားများကို မှန်ကန်စွာ တင်ပြပြီး Admin ၏ ထပ်ဆင့်စစ်ဆေးမှုကို ပူးပေါင်းရမည်။", "ဆရာကတ်သည် ဤပလက်ဖောင်းတွင် အတည်ပြုထားသော ဆရာအဖြစ်သာ သက်သေပြသည်။ ဆရာလိုင်စင်၊ အရည်အချင်းလက်မှတ်၊ ဘွဲ့ သို့မဟုတ် အစိုးရပညာရေးအဖွဲ့၏ တရားဝင်အသိအမှတ်ပြုမှု မဟုတ်ပါ။", "သင်တန်းအရည်အသွေး၊ ကျောင်းသားလုံခြုံရေး၊ ကိုယ်ရေးအချက်အလက်၊ မူပိုင်ခွင့်နှင့် အကြောင်းအရာစစ်ဆေးမှု စည်းမျဉ်းများကို လိုက်နာရမည်။ အစိုးရ၏ တရားဝင်ခွင့်ပြုချက်ရှိသကဲ့သို့ မကြော်ငြာရ။", "Admin တွင် နောက်ဆုံးအတည်ပြု၊ ထုတ်ပေး၊ ရပ်ဆိုင်းနှင့် ရုပ်သိမ်းခွင့်ရှိသည်။ အတည်ပြုခြင်းသည် အလုပ်၊ ဝင်ငွေ သို့မဟုတ် တတိယပါတီပူးပေါင်းမှုကို အာမခံခြင်းမဟုတ်ပါ။"],
    company: ["ကုမ္ပဏီအတည်ပြုခြင်းသည် BurmeseBridge တွင် တင်ပြထားသော ကုမ္ပဏီ သို့မဟုတ် အဖွဲ့အစည်း၏ အများမြင် အချက်အလက်ကိုသာ မှတ်တမ်းတင်သည်။", "လျှောက်ထားသူသည် ထိုအဖွဲ့အစည်းကို ကိုယ်စားပြုခွင့်ရှိသူဖြစ်ပြီး မှန်ကန်သော မှတ်ပုံတင်အမည်၊ ဆက်သွယ်ရန်နှင့် အထောက်အထားများ ပေးရမည်။", "ကုမ္ပဏီအတည်ပြုခြင်းသည် အစိုးရလိုင်စင်၊ လုပ်ငန်းအရည်အချင်း၊ အလုပ်ရှင်အာမခံချက် သို့မဟုတ် လုပ်ငန်းအပြုအမူအပေါ် BurmeseBridge ၏ အာမခံချက် မဟုတ်ပါ။", "လိမ်လည်မှု၊ ခွဲခြားဆက်ဆံမှု၊ တရားမဝင်အလုပ်ခေါ်ယူမှု၊ အခကြေးငွေထောင်ချောက် သို့မဟုတ် အခြားသူ၏အခွင့်အရေးချိုးဖောက်မှုများ မပြုရ။"],
    author: ["စာရေးသူအတည်ပြုခြင်းသည် BurmeseBridge တွင် မူရင်း သို့မဟုတ် တရားဝင်ခွင့်ပြုထားသော အကြောင်းအရာ တင်ပြသူကိုသာ ခွဲခြားပြသည်။", "တင်ပြသည့်အကြောင်းအရာ၏ မူပိုင်ခွင့် သို့မဟုတ် တရားဝင်ခွင့်ပြုချက်ရှိရမည်။ ကူးယူခြင်း၊ အခြားသူ၏အမည်သုံးခြင်းနှင့် တတိယပါတီအခွင့်အရေးချိုးဖောက်ခြင်း မပြုရ။", "စာရေးသူအမှတ်အသားသည် ပလက်ဖောင်းအတွင်း စစ်ဆေးမှုအခြေအနေသာဖြစ်ပြီး ထုတ်ဝေရေးအဖွဲ့၊ အစိုးရယဉ်ကျေးမှုအဖွဲ့ သို့မဟုတ် မူပိုင်ခွင့်မှတ်ပုံတင်လက်မှတ် မဟုတ်ပါ။", "ကိုးကားမှု၊ ကိုယ်ရေးအချက်အလက်၊ ကလေးသူငယ်ကာကွယ်ရေးနှင့် အကြောင်းအရာလုံခြုံရေး စည်းမျဉ်းများကို လိုက်နာရမည်။"],
  } : {
    student: ["Student verification records your learning identity within the private BurmeseBridge platform.", "Applicants must provide truthful, verifiable information. Impersonation, forged documents, and duplicate applications are prohibited.", "A student ID is an internal platform credential, not a government ID, degree, qualification, or government education accreditation.", "We may reject, suspend, or revoke verification for false information, account abuse, or rule violations."],
    teacher: ["Teacher verification confirms that the applicant passed BurmeseBridge's internal teacher review and may teach an approved course or class on this platform.", "Applicants must provide truthful teaching experience, subject capability, organisation details, or other verifiable evidence and cooperate with Admin's review.", "A teacher ID only confirms an instructor verified by this platform. It is not a teaching licence, qualification certificate, academic credential, or approval by any government education institution.", "Teachers must follow course quality, student safety, privacy, intellectual property, and content moderation rules. They must not claim government authority or official endorsement.", "Admin has final authority to approve, issue, suspend, and revoke verification. Verification does not guarantee employment, income, course publication, or third-party work."],
    company: ["Company verification records public identity information submitted by a company or organisation on BurmeseBridge.", "The applicant must be authorised to represent the entity and provide truthful registration, contact, and supporting information.", "Company verification is not a government licence, industry qualification, employer endorsement, or guarantee of business conduct by BurmeseBridge.", "Fraud, discrimination, unlawful recruitment, fee traps, and rights violations are prohibited; material changes must be reported."],
    author: ["Author verification identifies creators who publish original or lawfully authorised content on BurmeseBridge.", "Applicants must own or be authorised to use submitted content. Plagiarism, misattribution, impersonation, and infringement of third-party rights are prohibited.", "The author badge records an internal platform review status. It is not a publisher credential, government cultural accreditation, or copyright registration.", "Authors must follow citation, privacy, child-safety, and content-safety rules. Content may be removed and verification suspended or revoked."],
  };

  const [name, setName] = useState(initialName), [updatedAt, setUpdatedAt] = useState(nameUpdatedAt), [pageOpenedAt] = useState(() => Date.now());
  const [open, setOpen] = useState(false), [message, setMessage] = useState(""), [requests, setRequests] = useState<Request[]>([]), [kind, setKind] = useState<ApplicationKind>("student"), [evidence, setEvidence] = useState(""), [termsRead, setTermsRead] = useState(false), [consent, setConsent] = useState(false);
  useEffect(() => { void supabase.from("verification_requests").select("id,requested_badge,evidence,status,review_note,created_at").eq("user_id", userId).order("created_at", { ascending: false }).then(({ data }) => setRequests((data || []) as Request[])); }, [userId]);
  const next = updatedAt ? new Date(new Date(updatedAt).getTime() + 30 * 86400000) : null;
  const locked = Boolean(next && next.getTime() > pageOpenedAt), pending = requests.some(request => request.status === "pending");
  async function saveName() { if (locked) return; setMessage(""); const { error } = await supabase.from("profiles").update({ display_name: name.trim() }).eq("id", userId); if (error) { setMessage(error.message.includes("display_name_change_cooldown") ? copy.cooldown : error.message); return; } setUpdatedAt(new Date().toISOString()); setOpen(false); window.location.reload(); }
  async function submit() { if (!evidence.trim() || pending || !termsRead || !consent) { setMessage(copy.termsRequired); return; } const { data, error } = await supabase.from("verification_requests").insert({ user_id: userId, requested_badge: kind, evidence: evidence.trim() }).select("id,requested_badge,evidence,status,review_note,created_at").single(); if (error) { setMessage(error.message); return; } setRequests(current => [data as Request, ...current]); setEvidence(""); setTermsRead(false); setConsent(false); setMessage(copy.pending); }
  function selectKind(value: ApplicationKind) { setKind(value); setTermsRead(false); setConsent(false); setMessage(""); }

  return <section className="account-profile-panel" id="profile-settings"><h2><UserRound size={20} />{copy.title}</h2><div className="account-profile-grid"><article className="account-profile-summary"><span>{copy.name}</span><strong>{name || email.split("@")[0]}</strong><small>{copy.rule}{locked && next ? <><br />{copy.next}: {next.toLocaleDateString(locale)}</> : null}</small><button type="button" onClick={() => setOpen(true)} disabled={locked}><Pencil size={16} />{copy.change}</button></article><article className="account-verification-summary"><h3><BadgeCheck size={18} />{copy.verify}</h3><p>{copy.verifyCopy}</p>{verified ? <div className="verification-approved">{copy.approved}</div> : pending ? <div className="verification-pending">{copy.pending}</div> : <><select value={kind} onChange={event => selectKind(event.target.value as ApplicationKind)}><option value="student">{copy.student}</option><option value="teacher">{copy.teacher}</option><option value="company">{copy.company}</option><option value="author">{copy.author}</option></select><section className="verification-terms"><h4>{copy.termsTitle}: {copy[kind]}</h4><p className="verification-terms-hint">{copy.termsHint}</p><div className="verification-terms-scroll" tabIndex={0} onScroll={event => { const element = event.currentTarget; if (element.scrollTop + element.clientHeight >= element.scrollHeight - 8) setTermsRead(true); }}>{terms[kind].map((paragraph, index) => <p key={index}>{paragraph}</p>)}<strong>{termsRead ? `✓ ${copy.termsEnd}` : ""}</strong></div><label className="verification-consent"><input type="checkbox" checked={consent} disabled={!termsRead} onChange={event => setConsent(event.target.checked)} /><span>{copy.readConsent}</span></label></section><textarea rows={3} value={evidence} onChange={event => setEvidence(event.target.value)} placeholder={copy.evidence} /><button onClick={() => void submit()} disabled={!evidence.trim() || !termsRead || !consent}>{copy.submit}</button></>}{requests.length > 0 && <details><summary>{copy.history} ({requests.length})</summary>{requests.map(request => <p key={request.id}><b>{copy[request.requested_badge]}</b> · {request.status === "rejected" ? copy.rejected : request.status}{request.review_note ? ` — ${request.review_note}` : ""}</p>)}</details>}</article></div>{message && <p className="security-message" role="status">{message}</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="account-dialog"><DialogHeader><DialogTitle>{copy.change}</DialogTitle><DialogDescription>{copy.rule}</DialogDescription></DialogHeader><div className="security-form"><input value={name} onChange={event => setName(event.target.value)} aria-label={copy.name} /><button type="button" onClick={() => void saveName()} disabled={!name.trim()}>{copy.save}</button></div></DialogContent></Dialog></section>;
}
