"use client";
import { useEffect, useState } from "react";
import { BadgeCheck, Pencil, UserRound } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Request={id:number;requested_badge:"teacher"|"company"|"author";evidence:string;status:"pending"|"approved"|"rejected";review_note:string|null;created_at:string};
export default function AccountProfilePanel({locale,userId,email,initialName,nameUpdatedAt,verified}:{locale:string;userId:string;email:string;initialName:string;nameUpdatedAt:string|null;verified:boolean}){
  const copy=locale==="zh"?{title:"个人资料与认证",name:"显示名称",change:"修改名称",rule:"显示名称每 30 天只能修改一次。",next:"下次可修改日期",save:"保存名称",cooldown:"显示名称尚在 30 天修改冷却期内。",verify:"专业身份认证",verifyCopy:"申请教师、企业或作者认证，审核通过后展示认证徽章。",teacher:"教师",company:"企业",author:"作者",evidence:"经历、所属机构或证明链接",submit:"提交申请",pending:"申请正在审核中",approved:"专业身份已经通过认证",rejected:"已拒绝",history:"申请记录"}:locale==="my"?{title:"ကိုယ်ရေးအချက်အလက်နှင့် အတည်ပြုခြင်း",name:"ဖော်ပြမည့်အမည်",change:"အမည်ပြောင်းရန်",rule:"ဖော်ပြမည့်အမည်ကို ရက် ၃၀ လျှင် တစ်ကြိမ်သာ ပြောင်းနိုင်သည်။",next:"နောက်တစ်ကြိမ် ပြောင်းနိုင်မည့်ရက်",save:"အမည်သိမ်းမည်",cooldown:"အမည်ပြောင်းရန် ရက် ၃၀ ပြည့်ရမည်။",verify:"Professional Verification",verifyCopy:"ဆရာ၊ ကုမ္ပဏီ သို့မဟုတ် စာရေးသူအဖြစ် လျှောက်ထားနိုင်သည်။",teacher:"ဆရာ",company:"ကုမ္ပဏီ",author:"စာရေးသူ",evidence:"အတွေ့အကြုံ၊ အဖွဲ့အစည်း သို့မဟုတ် အထောက်အထားလင့်ခ်",submit:"လျှောက်ထားမည်",pending:"လျှောက်ထားချက်ကို စိစစ်နေသည်",approved:"Professional Identity ကို အတည်ပြုပြီးပါပြီ",rejected:"အတည်မပြုပါ",history:"လျှောက်ထားမှုမှတ်တမ်း"}:{title:"Profile and verification",name:"Display name",change:"Change name",rule:"Your display name can be changed once every 30 days.",next:"Next change available",save:"Save name",cooldown:"Your display name is still within the 30-day cooldown.",verify:"Professional verification",verifyCopy:"Apply as a teacher, company, or author for a public verified badge.",teacher:"Teacher",company:"Company",author:"Author",evidence:"Experience, organization, or supporting links",submit:"Submit application",pending:"Application under review",approved:"Professional identity verified",rejected:"Rejected",history:"Application history"};
  const [name,setName]=useState(initialName);const [updatedAt,setUpdatedAt]=useState(nameUpdatedAt);const [pageOpenedAt]=useState(()=>Date.now());const [open,setOpen]=useState(false);const [message,setMessage]=useState("");const [requests,setRequests]=useState<Request[]>([]);const [kind,setKind]=useState<Request["requested_badge"]>("teacher");const [evidence,setEvidence]=useState("");
  useEffect(()=>{void supabase.from("verification_requests").select("id,requested_badge,evidence,status,review_note,created_at").eq("user_id",userId).order("created_at",{ascending:false}).then(({data})=>setRequests((data||[]) as Request[]));},[userId]);
  const next=updatedAt?new Date(new Date(updatedAt).getTime()+30*86400000):null;const locked=Boolean(next&&next.getTime()>pageOpenedAt);
  async function saveName(){if(locked)return;setMessage("");const {error}=await supabase.from("profiles").update({display_name:name.trim()}).eq("id",userId);if(error){setMessage(error.message.includes("display_name_change_cooldown")?copy.cooldown:error.message);return;}const now=new Date().toISOString();setUpdatedAt(now);setOpen(false);window.location.reload();}
  async function submit(){if(!evidence.trim()||requests.some(r=>r.status==="pending"))return;const {data,error}=await supabase.from("verification_requests").insert({user_id:userId,requested_badge:kind,evidence:evidence.trim()}).select("id,requested_badge,evidence,status,review_note,created_at").single();if(error){setMessage(error.message);return;}setRequests(current=>[data as Request,...current]);setEvidence("");}
  const pending=requests.some(r=>r.status==="pending");
  return <section className="account-profile-panel" id="profile-settings"><h2><UserRound size={20}/>{copy.title}</h2><div className="account-profile-grid"><article className="account-profile-summary"><span>{copy.name}</span><strong>{name||email.split("@")[0]}</strong><small>{copy.rule}{locked&&next?<><br/>{copy.next}: {next.toLocaleDateString(locale)}</>:null}</small><button type="button" onClick={()=>setOpen(true)} disabled={locked}><Pencil size={16}/>{copy.change}</button></article><article className="account-verification-summary"><h3><BadgeCheck size={18}/>{copy.verify}</h3><p>{copy.verifyCopy}</p>{verified?<div className="verification-approved">{copy.approved}</div>:pending?<div className="verification-pending">{copy.pending}</div>:<><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="teacher">{copy.teacher}</option><option value="company">{copy.company}</option><option value="author">{copy.author}</option></select><textarea rows={3} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder={copy.evidence}/><button onClick={submit} disabled={!evidence.trim()}>{copy.submit}</button></>}{requests.length>0&&<details><summary>{copy.history} ({requests.length})</summary>{requests.map(r=><p key={r.id}><b>{copy[r.requested_badge]}</b> · {r.status==="rejected"?copy.rejected:r.status}{r.review_note?` — ${r.review_note}`:""}</p>)}</details>}</article></div>{message&&<p className="security-message">{message}</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="account-dialog"><DialogHeader><DialogTitle>{copy.change}</DialogTitle><DialogDescription>{copy.rule}</DialogDescription></DialogHeader><div className="security-form"><input value={name} onChange={e=>setName(e.target.value)} aria-label={copy.name}/><button type="button" onClick={saveName} disabled={!name.trim()}>{copy.save}</button></div></DialogContent></Dialog></section>;
}
