"use client";
import { useParams } from "next/navigation";
import { useState } from "react";
import { Flame, Pin, Sparkles } from "lucide-react";
import BrandBadgeIcon from "@/components/BrandBadgeIcon";

export type BadgeType = "verified"|"moderator"|"admin"|"teacher"|"student"|"company"|"author"|"vip"|"premium"|"member"|"pinned"|"hot"|"featured";
const labels={my:{verified:"အတည်ပြုပြီး",moderator:"စီမံခန့်ခွဲသူ",admin:"အက်မင်",teacher:"ဆရာ",student:"ကျောင်းသား",company:"ကုမ္ပဏီ",author:"စာရေးသူ",vip:"VIP",premium:"Premium",member:"အသင်းဝင်",pinned:"ထိပ်ဆုံးပို့စ်",hot:"လူကြိုက်များ",featured:"အကြံပြု"},zh:{verified:"已认证",moderator:"版主",admin:"管理员",teacher:"老师",student:"学生",company:"企业",author:"作者",vip:"VIP会员",premium:"高级会员",member:"会员",pinned:"置顶",hot:"热门",featured:"推荐"},en:{verified:"Verified",moderator:"Moderator",admin:"Admin",teacher:"Teacher",student:"Student",company:"Company",author:"Author",vip:"VIP",premium:"Premium",member:"Member",pinned:"Pinned",hot:"Hot",featured:"Featured"}};
const contentIcons={pinned:Pin,hot:Flame,featured:Sparkles};
const colors:Record<string,string>={admin:"#a80f35",moderator:"#a95300",verified:"#006f55",teacher:"#5630c7",student:"#006b78",author:"#9d4500",company:"#075789",vip:"#945d00",premium:"#945d00",member:"#475569"};
const tints:Record<string,string>={"#a80f35":"#fff0f4","#a95300":"#fff5e8","#006f55":"#eafaf4","#5630c7":"#f3efff","#006b78":"#eaf9fb","#9d4500":"#fff3e8","#075789":"#edf7fc","#945d00":"#fff7df","#475569":"#f1f5f7"};
const badgeStyle=(color:string):React.CSSProperties=>({position:"relative",display:"inline-grid",placeItems:"center",flex:"0 0 34px",width:34,height:34,minWidth:34,maxWidth:34,border:`1.5px solid ${color}55`,borderRadius:10,color,background:`linear-gradient(145deg,#fff 5%,${tints[color]||"#f3f6f8"} 95%)`,boxShadow:`0 2px 8px ${color}24,inset 0 1px 0 rgba(255,255,255,.95)`,cursor:"help",verticalAlign:"middle"});
const tooltipStyle:React.CSSProperties={position:"absolute",left:"50%",bottom:"calc(100% + 8px)",zIndex:1000,transform:"translateX(-50%)",padding:"6px 9px",borderRadius:7,background:"#122c28",color:"#fff",fontSize:12,fontWeight:750,lineHeight:1,whiteSpace:"nowrap",pointerEvents:"none"};

export default function Badge({type,labelOverride}:{type:BadgeType|string;labelOverride?:string}){
 const locale=String(useParams().locale||"en") as keyof typeof labels,[show,setShow]=useState(false); const known=(type in labels.en?type:"member") as BadgeType; const label=labelOverride||labels[locale]?.[known]||labels.en[known]; const Icon=contentIcons[known as keyof typeof contentIcons];
 return <span className={`brand-icon-badge brand-icon-badge-${known}`} style={badgeStyle(colors[known]||colors.member)} onMouseEnter={()=>setShow(true)} onMouseLeave={()=>setShow(false)} onFocus={()=>setShow(true)} onBlur={()=>setShow(false)} onClick={()=>setShow(v=>!v)} tabIndex={0} role="img" aria-label={label}>{Icon?<Icon size={16}/>:<BrandBadgeIcon type={known}/>} {show?<span className="brand-badge-tooltip" style={tooltipStyle} role="tooltip">{label}</span>:null}</span>;
}
export function LevelBadge({level}:{level:number}){const locale=String(useParams().locale||"en"),[show,setShow]=useState(false),label=locale==="zh"?`成长等级 LV.${level}`:locale==="my"?`အဆင့် LV.${level}`:`Activity level LV.${level}`;return <span className="brand-icon-badge brand-level-icon" style={badgeStyle(colors.vip)} onMouseEnter={()=>setShow(true)} onMouseLeave={()=>setShow(false)} onFocus={()=>setShow(true)} onBlur={()=>setShow(false)} onClick={()=>setShow(v=>!v)} tabIndex={0} role="img" aria-label={label}><BrandBadgeIcon type="vip"/><b>{level}</b>{show?<span className="brand-badge-tooltip" style={tooltipStyle} role="tooltip">{label}</span>:null}</span>}
export function ProfileBadges({badges,badge,role,verified,level}:{badges?:string[]|null;badge?:string|null;role?:string|null;verified?:boolean|null;level?:number|null}){const ids=new Set<string>();(badges||[]).forEach(v=>v&&ids.add(v.toLowerCase()));if(role&&role!=="member")ids.add(role.toLowerCase());if(badge)ids.add(badge.toLowerCase());if(verified)ids.add("verified");if(!ids.size)ids.add("member");return <span className="profile-icon-badges" style={{display:"inline-flex",alignItems:"center",gap:5,flexWrap:"nowrap",width:"max-content",maxWidth:"100%"}} aria-label="Account badges">{Array.from(ids).map(type=><Badge key={type} type={type} labelOverride={type in labels.en?undefined:type}/>)}{level?<LevelBadge level={level}/>:null}</span>}
