"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import Link from "next/link";
import { CreditCard, ExternalLink, ShieldCheck } from "lucide-react";
import BrandLogo from "@/components/BrandLogo";
import { supabase } from "@/lib/supabase";

type Card={id:number;card_type:"student"|"teacher";card_no:string;verification_code:string;holder_name:string;issued_at:string;expires_at:string};

export default function EducationIdCards({locale,userId}:{locale:string;userId:string}){
 const[cards,setCards]=useState<Card[]>([]),[qrs,setQrs]=useState<Record<number,string>>({});
 const copy=locale==="zh"?{title:"我的教育证件",empty:"身份审核通过后，管理员可以签发 BurmeseBridge 学生证或教师证。",student:"学生证",teacher:"教师证",issued:"签发日期",expires:"有效期至",number:"证件编号",anti:"防伪码",verify:"在线查验",notice:"仅用于证明持有人在 BurmeseBridge 私立学习平台内的学习或教学身份，不是政府证件，也不代表政府教育机构认证。"}:locale==="my"?{title:"ကျွန်ုပ်၏ ပညာရေးကတ်",empty:"Identity စစ်ဆေးအတည်ပြုပြီးပါက Admin က BurmeseBridge ကျောင်းသားကတ် သို့မဟုတ် ဆရာကတ် ထုတ်ပေးနိုင်သည်။",student:"ကျောင်းသားကတ်",teacher:"ဆရာကတ်",issued:"ထုတ်ပေးသည့်ရက်",expires:"သက်တမ်းကုန်ရက်",number:"ကတ်အမှတ်",anti:"အတုအပကာကွယ်ရေးကုဒ်",verify:"အွန်လိုင်းမှ စစ်ဆေးရန်",notice:"BurmeseBridge ပုဂ္ဂလိကသင်ယူရေးပလက်ဖောင်းအတွင်း သင်ယူသူ/သင်ကြားသူအဖြစ်သာ သက်သေပြသည်။ အစိုးရ ID သို့မဟုတ် အစိုးရပညာရေးအဖွဲ့၏ အသိအမှတ်ပြုလက်မှတ် မဟုတ်ပါ။"}:{title:"My education IDs",empty:"After identity approval, an administrator can issue a BurmeseBridge student or teacher ID.",student:"Student ID",teacher:"Teacher ID",issued:"Issued",expires:"Valid until",number:"Card number",anti:"Authenticity code",verify:"Verify online",notice:"This only confirms learning or teaching status within the private BurmeseBridge learning platform. It is not a government ID and does not represent accreditation by a government education authority."};
 useEffect(()=>{let active=true;void supabase.from("education_id_cards").select("id,card_type,card_no,verification_code,holder_name,issued_at,expires_at").eq("user_id",userId).eq("status","active").order("issued_at",{ascending:false}).then(({data})=>{if(active)setCards((data||[]) as Card[])});return()=>{active=false}},[userId]);
 useEffect(()=>{let active=true;if(!cards.length)return;void import("qrcode").then(async({default:QRCode})=>{const entries=await Promise.all(cards.map(async card=>[card.id,await QRCode.toDataURL(`https://burmesebridge.com/${locale}/education-id/${encodeURIComponent(card.verification_code)}`,{width:180,margin:1,errorCorrectionLevel:"M",color:{dark:"#0e5a49",light:"#fffdf8"}})] as const));if(active)setQrs(Object.fromEntries(entries))});return()=>{active=false}},[cards,locale]);
 return <section className="education-id-section"><h2><CreditCard size={20}/>{copy.title}</h2>{cards.length?<div className="education-id-list">{cards.map(card=><article className={`education-id-card is-${card.card_type}`} key={card.id}><header><BrandLogo size={38}/><div><span>BurmeseBridge</span><strong>{copy[card.card_type]}</strong></div><ShieldCheck size={23}/></header><h3>{card.holder_name}</h3><dl><div><dt>{copy.number}</dt><dd>{card.card_no}</dd></div><div><dt>{copy.anti}</dt><dd>{card.verification_code}</dd></div><div><dt>{copy.issued}</dt><dd>{new Date(card.issued_at).toLocaleDateString(locale)}</dd></div><div><dt>{copy.expires}</dt><dd>{new Date(card.expires_at).toLocaleDateString(locale)}</dd></div></dl><div className="education-id-auth">{qrs[card.id]?<img src={qrs[card.id]} alt="QR"/>:null}<Link href={`/${locale}/education-id/${encodeURIComponent(card.verification_code)}`} target="_blank">{copy.verify}<ExternalLink size={13}/></Link></div><p>{copy.notice}</p></article>)}</div>:<p className="education-id-empty">{copy.empty}</p>}</section>
}
