"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { Award,ShieldCheck,XCircle } from "lucide-react";
import BrandLogo from "@/components/BrandLogo";
import { supabase } from "@/lib/supabase";
type Verification={valid:boolean;certificate_no:string;recipient_name:string;course_title:string;issued_at:string};
export default function CertificateVerificationPage(){const params=useParams();const locale=String(params.locale||"my");const code=decodeURIComponent(String(params.code||"")).toUpperCase();const[data,setData]=useState<Verification|null>(null);const[loaded,setLoaded]=useState(false);const copy=locale==="zh"?{title:"证书验证",valid:"有效证书",invalid:"没有找到此证书",recipient:"获得者",course:"课程",issued:"颁发日期",number:"证书编号",home:"返回首页"}:locale==="my"?{title:"လက်မှတ်စစ်ဆေးရန်",valid:"တရားဝင်လက်မှတ်",invalid:"ဤလက်မှတ်ကို မတွေ့ပါ",recipient:"လက်ခံသူ",course:"သင်တန်း",issued:"ထုတ်ပေးသည့်ရက်",number:"လက်မှတ်အမှတ်",home:"ပင်မစာမျက်နှာ"}:{title:"Certificate verification",valid:"Valid certificate",invalid:"Certificate not found",recipient:"Recipient",course:"Course",issued:"Issued",number:"Certificate number",home:"Back to home"};useEffect(()=>{let active=true;void supabase.rpc("verify_knowledge_certificate",{p_certificate_no:code}).then(({data})=>{if(active){setData(data as Verification|null);setLoaded(true)}});return()=>{active=false}},[code]);return <main className="certificate-verify-page"><BrandLogo size={46}/><header><Award size={28}/><h1>{copy.title}</h1></header>{!loaded?<div className="certificate-verify-card">…</div>:data?<div className="certificate-verify-card valid"><ShieldCheck size={44}/><h2>{copy.valid}</h2><dl><div><dt>{copy.recipient}</dt><dd>{data.recipient_name}</dd></div><div><dt>{copy.course}</dt><dd>{data.course_title}</dd></div><div><dt>{copy.issued}</dt><dd>{new Date(data.issued_at).toLocaleDateString(locale)}</dd></div><div><dt>{copy.number}</dt><dd>{data.certificate_no}</dd></div></dl></div>:<div className="certificate-verify-card invalid"><XCircle size={44}/><h2>{copy.invalid}</h2></div>}<Link href={`/${locale}`}>{copy.home}</Link></main>}
