import type { VocabularyEnrichment } from "@/lib/hskVocabularyMy";

// HSK 3 editorial Burmese layer. Meanings follow formal written Myanmar usage;
// grammar words are explained by function instead of being translated literally.
export const hsk3VocabularyMy: Record<string, VocabularyEnrichment> = {
  "阿姨": { meaningMy: "အဒေါ်၊ မိခင်နှင့် သက်တူရွယ်တူ အမျိုးသမီးကို ရိုသေစွာ ခေါ်ဝေါ်သည့်စကား", image: "/images/hsk/vocabulary/hsk3-ayi-aunt.png", imageAltMy: "မြန်မာအိမ်ခြံဝင်းတွင် အဒေါ်အရွယ် အမျိုးသမီးတစ်ဦးကို ရိုသေဖော်ရွေစွာ နှုတ်ဆက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "啊": { meaningMy: "အံ့ဩခြင်း၊ အတည်ပြုခြင်း သို့မဟုတ် လေသံကို ဖော်ပြသော ဝါကျအဆုံးသတ်ပုဒ်", image: "/images/hsk/vocabulary/hsk3-a-interjection.png", imageAltMy: "လက်ဖဝါးပေါ် လိပ်ပြာနားလာသည်ကို အံ့အားသင့်ဝမ်းသာစွာ တုံ့ပြန်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "矮": { meaningMy: "အရပ်ပုသော၊ နိမ့်သော", image: "/images/hsk/vocabulary/hsk3-ai-short.png", imageAltMy: "အရပ်အမြင့်ကွာခြားမှုကို သိသာစေသော လူနှစ်ဦးနှင့် နိမ့်မြင့်မတူသည့် ထိုင်ခုံများ", imageStatus: "generated" },
  "爱好": { meaningMy: "ဝါသနာ၊ နှစ်သက်စွဲလမ်းမှု", image: "/images/hsk/vocabulary/hsk3-aihao-hobby.png", imageAltMy: "အိမ်ရှိ ပန်းချီခန်းတွင် မိမိဝါသနာအဖြစ် သဘာဝရှုခင်းပန်းချီ ဆွဲနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "安静": { meaningMy: "တိတ်ဆိတ်သော၊ ငြိမ်သက်သော", image: "/images/hsk/vocabulary/hsk3-anjing-quiet.png", imageAltMy: "ကြောင်ကလေး အိပ်ပျော်နေသော တိတ်ဆိတ်ငြိမ်သက်သည့် စာကြည့်ခန်းတွင် စာဖတ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "把": { meaningMy: "အရာဝတ္ထုကို ကြိယာရှေ့သို့ ထုတ်ဖော်၍ လုပ်ဆောင်မှု၏ အကျိုးသက်ရောက်မှုကို ပြသော ဝါကျဖွဲ့ပုဒ်", image: "/images/hsk/vocabulary/hsk3-ba-handle.png", imageAltMy: "ကြမ်းပြင်ပေါ်ရှိ စာအုပ်ကို ယူ၍ စာအုပ်စင်ပေါ် စနစ်တကျ တင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "搬": { meaningMy: "ရွှေ့သည်၊ သယ်ရွှေ့သည်", image: "/images/hsk/vocabulary/hsk3-ban-move.png", imageAltMy: "အိမ်တံခါးဝမှ ပစ္စည်းသေတ္တာကို မိတ်ဆွေနှင့်အတူ ရွှေ့ပြောင်းသယ်ဆောင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "班": { meaningMy: "အတန်း၊ အလုပ်အဆိုင်း၊ အဖွဲ့", image: "/images/hsk/vocabulary/hsk3-ban-class.png", imageAltMy: "ဆရာမ၏ ရှင်းလင်းပြသမှုကို အတန်းဖော်များနှင့် အဖွဲ့လိုက် လေ့လာနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "半": { meaningMy: "တစ်ဝက်၊ ထက်ဝက်", image: "/images/hsk/vocabulary/hsk3-ban-half.png", imageAltMy: "ဝိုင်းပုံမုန့်တစ်ချပ်ကို အရွယ်တူ တစ်ဝက်နှစ်ပိုင်း ခွဲပြထားသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "办法": { meaningMy: "နည်းလမ်း၊ ဖြေရှင်းနည်း", image: "/images/hsk/vocabulary/hsk3-banfa-solution.png", imageAltMy: "လမ်းကို ပိတ်ဆို့နေသော ချောင်းငယ်အား ကျောက်ပြားများစီ၍ ဖြတ်ကူးနိုင်သည့် နည်းလမ်းကို ရှာဖွေဖြေရှင်းနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "办公室": { meaningMy: "ရုံးခန်း", image: "/images/hsk/vocabulary/hsk3-bangongshi-office.png", imageAltMy: "စနစ်တကျ ပြင်ဆင်ထားသော ရုံးခန်းစားပွဲတွင် ကွန်ပျူတာဖြင့် အလုပ်လုပ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "帮忙": { meaningMy: "ကူညီပေးသည်၊ ဝိုင်းဝန်းကူညီသည်", image: "/images/hsk/vocabulary/hsk3-bangmang-help.png", imageAltMy: "သက်ကြီးရွယ်အို အိမ်နီးချင်း၏ ဟင်းသီးဟင်းရွက်ခြင်းကို မီးဖိုချောင်စားပွဲပေါ် တင်ပေးကူညီနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "包": { meaningMy: "အိတ်၊ ထုပ်၊ ထုပ်ပိုးသည်", image: "/images/hsk/vocabulary/hsk3-bao-bag.png", imageAltMy: "ပန်းခြံထိုင်ခုံပေါ်တွင် BurmeseBridge အမှတ်တံဆိပ်ပါ အိတ်ကို ဖွင့်ကြည့်နေသော လမ်းညွှန်", imageStatus: "generated" },
  "饱": { meaningMy: "ဝသော၊ ဗိုက်ပြည့်သော", image: "/images/hsk/vocabulary/hsk3-bao-full.png", imageAltMy: "အစားအစာကုန်အောင် စားပြီးနောက် ဗိုက်ပြည့်ကျေနပ်စွာ ထိုင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "北方": { meaningMy: "မြောက်ဘက်၊ မြောက်ပိုင်းဒေသ", image: "/images/hsk/vocabulary/hsk3-beifang-north.png", imageAltMy: "အေးမြသော မြောက်ပိုင်း နှင်းဖုံးတောင်တန်းဒေသကို ကြည့်ရှုနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "被": { meaningMy: "ခံရသူကို ရှေ့ထား၍ အခံဝါကျဖွဲ့ရာတွင် သုံးသောပုဒ်၊ စောင်", image: "/images/hsk/vocabulary/hsk3-bei-passive.png", imageAltMy: "လေပြင်းတိုက်ခတ်မှုကြောင့် ထီးလန်ကာ မိုးရေစိုခံနေရသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "鼻子": { meaningMy: "နှာခေါင်း", image: "/images/hsk/vocabulary/hsk3-bizi-nose.png", imageAltMy: "ပန်းခြံတွင် ပန်းတစ်ပွင့်ကို နှာခေါင်းအနီးထား၍ မွှေးကြိုင်မှုကို ရှူရှိုက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "比较": { meaningMy: "နှိုင်းယှဉ်သည်၊ အတော်အတန်", image: "/images/hsk/vocabulary/hsk3-bijiao-compare.png", imageAltMy: "သစ်သီးပမာဏ မတူသော ခြင်းနှစ်ခြင်းကို လက်နှစ်ဖက်ဖြင့် ကိုင်၍ နှိုင်းယှဉ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "比赛": { meaningMy: "ပြိုင်ပွဲ၊ ယှဉ်ပြိုင်သည်", image: "/images/hsk/vocabulary/hsk3-bisai-competition.png", imageAltMy: "ပန်းခြံပြေးပြိုင်ပွဲတွင် အခြားပြိုင်ပွဲဝင်တစ်ဦးနှင့် ပန်းဝင်ကြိုးဆီ ပြေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "必须": { meaningMy: "မဖြစ်မနေ လုပ်ရမည်၊ လိုအပ်သည်", image: "/images/hsk/vocabulary/hsk3-bixu-must.png", imageAltMy: "စက်ဘီးမစီးမီ မဖြစ်မနေ လုပ်ရမည့် လုံခြုံရေးအဖြစ် ခေါင်းဆောင်းကို သေချာတပ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "变化": { meaningMy: "ပြောင်းလဲမှု၊ ပြောင်းလဲသည်", image: "/images/hsk/vocabulary/hsk3-bianhua-change.png", imageAltMy: "ပျိုးပင်ငယ်မှ ပန်းပွင့်သစ်ပင်အထိ အဆင့်ဆင့် ပြောင်းလဲကြီးထွားပုံကို ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "表示": { meaningMy: "ဖော်ပြသည်၊ ထုတ်ဖော်ပြောဆိုသည်", image: "/images/hsk/vocabulary/hsk3-biaoshi-express.png", imageAltMy: "ဆရာအိုအား ပန်းစည်းပေး၍ ကျေးဇူးတင်လေးစားမှုကို ကိုယ်ဟန်ဖြင့် ဖော်ပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "表演": { meaningMy: "ဖျော်ဖြေတင်ဆက်သည်၊ ဖျော်ဖြေပွဲ", image: "/images/hsk/vocabulary/hsk3-biaoyan-performance.png", imageAltMy: "ပရိသတ်ရှေ့ရှိ စင်မြင့်ပေါ်တွင် ယပ်တောင်အက ဖျော်ဖြေနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "别人": { meaningMy: "အခြားသူ၊ သူတစ်ပါး", image: "/images/hsk/vocabulary/hsk3-bieren-others.png", imageAltMy: "အများသုံးရေစင်ကို အသုံးပြုနေသည့် အခြားသူများနှင့် သီးခြားရပ်စောင့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "宾馆": { meaningMy: "တည်းခိုခန်း၊ ဟိုတယ်", image: "/images/hsk/vocabulary/hsk3-binguan-hotel.png", imageAltMy: "ခရီးဆောင်အိတ်နှင့်အတူ မြန်မာ့ရိုးရာပုံစံ တည်းခိုခန်းဧည့်ကြိုကောင်တာတွင် အခန်းသော့ လက်ခံနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "冰箱": { meaningMy: "ရေခဲသေတ္တာ", image: "/images/hsk/vocabulary/hsk3-bingxiang-fridge.png", imageAltMy: "အစားအစာနှင့် ဟင်းသီးဟင်းရွက်များ စနစ်တကျ ထည့်ထားသည့် ရေခဲသေတ္တာကို ဖွင့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "才": { meaningMy: "မှသာ၊ ထိုအခါမှ၊ အနည်းငယ်စောက", image: "/images/hsk/vocabulary/hsk3-cai-only-then.png", imageAltMy: "မိတ်ဆွေများ အချိန်ကြာစောင့်နေပြီးနောက် ညနေမှသာ ဥယျာဉ်တံခါးသို့ ရောက်လာသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "菜单": { meaningMy: "အစားအသောက်စာရင်း၊ မီနူး", image: "/images/hsk/vocabulary/hsk3-caidan-menu.png", imageAltMy: "စားသောက်ဆိုင်စားပွဲတွင် ဟင်းပွဲပုံများပါသော မီနူးစာအုပ်ကို ကြည့်၍ ရွေးချယ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "参加": { meaningMy: "ပါဝင်သည်၊ တက်ရောက်သည်", image: "/images/hsk/vocabulary/hsk3-canjia-participate.png", imageAltMy: "ရပ်ကွက်နေသူများနှင့်အတူ သစ်ပင်စိုက်ပျိုးရေးလုပ်ငန်းတွင် တက်ကြွစွာ ပါဝင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "草": { meaningMy: "မြက်", image: "/images/hsk/vocabulary/hsk3-cao-grass.png", imageAltMy: "စိမ်းလန်းသော မြက်ခင်းတွင် ဒူးထောက်၍ မြက်ရွက်များကို လက်ဖြင့် ထိတွေ့ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "层": { meaningMy: "အထပ်၊ အလွှာကို ရေတွက်သော ပုဒ်", image: "/images/hsk/vocabulary/hsk3-ceng-layer.png", imageAltMy: "ကိတ်မုန့်၏ အလွှာများနှင့် စင်၏ အထပ်များကို ပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "差": { meaningMy: "ကွာခြားသည်၊ ချို့တဲ့သည်၊ ညံ့သည်", image: "/images/hsk/vocabulary/hsk3-cha-difference.png", imageAltMy: "ကောင်းမွန်သော မြေအိုးနှင့် အက်ကွဲညံ့ဖျင်းသော မြေအိုးကို နှိုင်းယှဉ်ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "超市": { meaningMy: "စူပါမားကက်၊ ကုန်တိုက်", image: "/images/hsk/vocabulary/hsk3-chaoshi-supermarket.png", imageAltMy: "ကုန်ပစ္စည်းနှင့် သစ်သီးဟင်းသီးဟင်းရွက်စင်များရှိသော စူပါမားကက်တွင် ဈေးဝယ်လှည်းတွန်းနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "衬衫": { meaningMy: "ရှပ်အင်္ကျီ", image: "/images/hsk/vocabulary/hsk3-chenshan-shirt.png", imageAltMy: "အဝတ်ဗီရိုရှေ့တွင် ခရင်မ်ရောင် ရှပ်အင်္ကျီကို ချိတ်ဖြင့် ကိုင်ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "成绩": { meaningMy: "ရလဒ်၊ အမှတ်၊ အောင်မြင်မှု", image: "/images/hsk/vocabulary/hsk3-chengji-result.png", imageAltMy: "ဆရာထံမှ တိုးတက်မှုနှင့် မှန်ကန်မှုအမှတ်အသားများပါသော စာမေးပွဲရလဒ်ကို လက်ခံနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "城市": { meaningMy: "မြို့၊ မြို့ပြ", image: "/images/hsk/vocabulary/hsk3-chengshi-city.png", imageAltMy: "အဆောက်အအုံများ၊ မြို့ပတ်ရထားနှင့် မြစ်ကမ်းပန်းခြံပါသော ခေတ်မီမြို့ပြရှုခင်းကို ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "迟到": { meaningMy: "နောက်ကျရောက်သည်", image: "/images/hsk/vocabulary/hsk3-chidao-late.png", imageAltMy: "အတန်းသားများ စာသင်နေပြီးနောက်မှ စိုးရိမ်တကြီး အခန်းထဲသို့ နောက်ကျဝင်လာသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "出现": { meaningMy: "ပေါ်လာသည်၊ ဖြစ်ပေါ်လာသည်", image: "/images/hsk/vocabulary/hsk3-chuxian-appear.png", imageAltMy: "မိုးတိမ်များ ကွဲသွားချိန် ကောင်းကင်တွင် ရုတ်တရက် ပေါ်လာသော သက်တံကို ဝမ်းသာစွာ ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "除了": { meaningMy: "…မှလွဲ၍၊ …အပြင်", image: "/images/hsk/vocabulary/hsk3-chule-except.png", imageAltMy: "အစိမ်းရောင်ပန်းသီးများအားလုံးကို ခြင်းထဲထည့်ပြီး လိမ္မော်သီးတစ်လုံးကိုသာ အပြင်တွင် ချန်ထားသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "厨房": { meaningMy: "မီးဖိုချောင်", image: "/images/hsk/vocabulary/hsk3-chufang-kitchen.png", imageAltMy: "မီးဖို၊ ရေကန်နှင့် မီးဖိုချောင်သုံးပစ္စည်းများရှိသော မီးဖိုချောင်တွင် ဟင်းသီးဟင်းရွက် လှီးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "春": { meaningMy: "နွေဦးရာသီ", image: "/images/hsk/vocabulary/hsk3-chun-spring.png", imageAltMy: "နွေဦးပန်းများ ပွင့်လန်းပြီး လိပ်ပြာများ ပျံဝဲနေသော မြန်မာဥယျာဉ်တွင် လမ်းလျှောက်နေသည့် BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "词语": { meaningMy: "စကားလုံး၊ ဝေါဟာရ", image: "/images/hsk/vocabulary/hsk3-ciyu-word.png", imageAltMy: "ပန်းသီး၊ ခွက်နှင့် စက်ဘီးပုံကတ်များကို အမျိုးအစားတူအလိုက် စုစည်းပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "聪明": { meaningMy: "ဉာဏ်ကောင်းသော၊ ထက်မြက်သော", image: "/images/hsk/vocabulary/hsk3-congming-clever.png", imageAltMy: "မိတ်ဆွေများရှေ့တွင် သစ်သားဉာဏ်စမ်းပဟေဠိ၏ နောက်ဆုံးအပိုင်းကို ထက်မြက်စွာ ဖြေရှင်းနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "打扫": { meaningMy: "သန့်ရှင်းရေးလုပ်သည်၊ တံမြက်စည်းလှည်းသည်", image: "/images/hsk/vocabulary/hsk3-dasao-clean.png", imageAltMy: "သပ်ရပ်သော ဧည့်ခန်းကြမ်းပြင်ကို တံမြက်စည်းနှင့် အမှိုက်ခံပြားသုံး၍ သန့်ရှင်းရေးလုပ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "打算": { meaningMy: "အစီအစဉ်ရှိသည်၊ ရည်ရွယ်သည်", image: "/images/hsk/vocabulary/hsk3-dasuan-plan.png", imageAltMy: "နေ့ချင်းပြန်ခရီးအတွက် ကျောပိုးအိတ်၊ ရေဘူး၊ မိုးကာ၊ ကင်မရာနှင့် ဖိနပ်များကို စဉ်းစားရွေးချယ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "带": { meaningMy: "ယူဆောင်သည်၊ ခေါ်ဆောင်သည်၊ ဝတ်ဆင်သည်", image: "/images/hsk/vocabulary/hsk3-dai-bring.png", imageAltMy: "အပြင်ထွက်ရာတွင် ရေဘူး၊ ထီးနှင့် အမှတ်တံဆိပ်ပါ အိတ်ကို အတူယူဆောင်ကာ အိမ်မှ ထွက်လာသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "担心": { meaningMy: "စိုးရိမ်သည်၊ ပူပန်သည်", image: "/images/hsk/vocabulary/hsk3-danxin-worry.png", imageAltMy: "ညှိုးနွမ်းနေသော အိမ်တွင်းအပင်၏ မြေခြောက်မှုကို စိုးရိမ်စွာ စစ်ဆေးပြီး ရေလောင်းရန် ပြင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "蛋糕": { meaningMy: "ကိတ်မုန့်", image: "/images/hsk/vocabulary/hsk3-dangao-cake.png", imageAltMy: "ပွဲတော်စားပွဲပေါ်ရှိ စတော်ဘယ်ရီနှင့် သစ်သီးများ အလှဆင်ထားသော ခရင်မ်ကိတ်မုန့်ကို ဝမ်းသာစွာ တင်ဆက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "当然": { meaningMy: "အမှန်ပင်၊ မုချ၊ သေချာပေါက်", image: "/images/hsk/vocabulary/hsk3-dangran-of-course.png", imageAltMy: "အိမ်နီးချင်း၏ အကူအညီတောင်းခံမှုကို အလွယ်တကူ သဘောတူပြီး ပစ္စည်းသေတ္တာကို အတူသယ်ပေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "地": { meaningMy: "အခြေအနေပြစကားကို ကြိယာနှင့် ဆက်သွယ်ပေးသော ဖွဲ့စည်းပုံပုဒ်", image: "/images/hsk/vocabulary/hsk3-de-manner.png", imageAltMy: "ရေပြည့်ခွက်ကို မဖိတ်စေရန် ငြိမ်သက်ဂရုတစိုက် လမ်းလျှောက်၍ ဗန်းပေါ် သယ်ဆောင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "灯": { meaningMy: "မီးအိမ်၊ မီးလုံး", image: "/images/hsk/vocabulary/hsk3-deng-lamp.png", imageAltMy: "မှောင်ရီသော အခန်းတွင် နွေးထွေးစွာ လင်းနေသည့် စားပွဲတင်မီးအိမ်ကို ဖွင့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "低": { meaningMy: "နိမ့်သော၊ နည်းသော", image: "/images/hsk/vocabulary/hsk3-di-low.png", imageAltMy: "မြင့်သော ခုံးတံခါးဘေးရှိ နိမ့်သော သစ်ကိုင်းအောက်မှ ကိုယ်ကို ကိုင်း၍ ဖြတ်သန်းနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "地方": { meaningMy: "နေရာ၊ ဒေသ", image: "/images/hsk/vocabulary/hsk3-difang-place.png", imageAltMy: "မြစ်ကမ်း၊ သစ်ပင်နှင့် မြန်မာမဏ္ဍပ်ရှိ သီးခြားပျော်ပွဲစားနေရာတစ်ခုတွင် ဖျာခင်းနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "地铁": { meaningMy: "မြေအောက်ရထား", image: "/images/hsk/vocabulary/hsk3-ditie-subway.png", imageAltMy: "ဥမင်အတွင်းရှိ မြေအောက်ရထားဘူတာစင်္ကြံပေါ်တွင် ရောက်လာသော ရထားကို စောင့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "地图": { meaningMy: "မြေပုံ", image: "/images/hsk/vocabulary/hsk3-ditu-map.png", imageAltMy: "တောင်ပေါ်ရှုခင်းကြည့်စင်တွင် လမ်း၊ မြစ်နှင့် အထင်ကရနေရာပုံများပါသော မြေပုံကို ဖွင့်ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "电梯": { meaningMy: "ဓာတ်လှေကား", image: "/images/hsk/vocabulary/hsk3-dianti-elevator.png", imageAltMy: "ဖွင့်ထားသော ဓာတ်လှေကားတံခါးကို သက်ကြီးရွယ်အို ဝင်လာနိုင်ရန် ကိုင်ထားပေးသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "电子": { meaningMy: "အီလက်ထရွန်၊ အီလက်ထရွန်နစ်ဆိုင်ရာ", image: "/images/hsk/vocabulary/hsk3-dianzi-electronic.png", imageAltMy: "လက်ပ်တော့၊ တက်ဘလက်၊ နားကြပ်နှင့် အီလက်ထရွန်နစ်ဆားကစ်ပြားတို့ကို အသုံးပြုနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "冬": { meaningMy: "ဆောင်းရာသီ", image: "/images/hsk/vocabulary/hsk3-dong-winter.png", imageAltMy: "နှင်းခဲနှင့် သစ်ရွက်ကြွေကိုင်းများရှိသော အေးမြသည့် ဆောင်းရာသီဥယျာဉ်တွင် ပဝါနှင့် လက်အိတ်ဝတ်ထားသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "东": { meaningMy: "အရှေ့ဘက်", image: "/images/hsk/vocabulary/hsk3-dong-east.png", imageAltMy: "ရေကန်ဘေး ရှုခင်းကြည့်စင်မှ နံနက်ခင်း အရှေ့ဘက်တွင် ထွက်ပေါ်လာသော နေကို ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "动物": { meaningMy: "တိရစ္ဆာန်", image: "/images/hsk/vocabulary/hsk3-dongwu-animals.png", imageAltMy: "သဘာဝထိန်းသိမ်းရေးနယ်မြေတွင် သမင်ငယ်၊ ယုန်၊ ငှက်နှင့် ဆင်ငယ်တို့ကို ကြင်နာစွာ စောင့်ရှောက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "短": { meaningMy: "တိုသော၊ ပုသော", image: "/images/hsk/vocabulary/hsk3-duan-short.png", imageAltMy: "ရှည်သော အစိမ်းရောင်ဖဲကြိုးနှင့် တိုသောဖဲကြိုးကို နှိုင်းယှဉ်ပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "段": { meaningMy: "အပိုင်း၊ အပိုဒ်၊ ခရီးအပိုင်းကို ရေတွက်သော ပုဒ်", image: "/images/hsk/vocabulary/hsk3-duan-segment.png", imageAltMy: "ကျောက်ပြားများဖြင့် ခင်းထားသောလမ်း၏ အလယ်အပိုင်းတစ်ပိုင်းကို နေရာချနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "锻炼": { meaningMy: "ကိုယ်လက်လေ့ကျင့်ခန်းလုပ်သည်၊ လေ့ကျင့်ပျိုးထောင်သည်", image: "/images/hsk/vocabulary/hsk3-duanlian-exercise.png", imageAltMy: "ဥယျာဉ်တွင် လက်အလေးတုံးများကို ကိုင်၍ ခြေလှမ်းကျယ် လေ့ကျင့်ခန်းလုပ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "多么": { meaningMy: "မည်မျှ၊ အလွန်ပင်ဟု အာမေဍိတ်ဖော်ပြသော စကား", image: "/images/hsk/vocabulary/hsk3-duome-how.png", imageAltMy: "နေထွက်ချိန် ကြာပန်းများပြည့်နေသော ရေကန်၏ လှပမှုကို အံ့အားသင့်စွာ ချီးကျူးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "饿": { meaningMy: "ဗိုက်ဆာသော", image: "/images/hsk/vocabulary/hsk3-e-hungry.png", imageAltMy: "စားပွဲပေါ်ရှိ ပူပူနွေးနွေးအစားအစာများကို ဗိုက်ဆာစွာ စောင့်မျှော်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "而且": { meaningMy: "ထို့အပြင်၊ ဒါ့အပြင်", image: "/images/hsk/vocabulary/hsk3-erqie-moreover.png", imageAltMy: "မိုးရွာသောနေ့အတွက် မိုးကာအင်္ကျီအပြင် ထီးနှင့် ရေစိုခံဖိနပ်တို့ကိုပါ ပြင်ဆင်ထားသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "耳朵": { meaningMy: "နား", image: "/images/hsk/vocabulary/hsk3-erduo-ear.png", imageAltMy: "ဥယျာဉ်ထဲတွင် နားတစ်ဖက်ကို လက်ဖြင့်ကာ၍ ငှက်ကလေး၏ သီချင်းသံကို နားထောင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "发烧": { meaningMy: "ဖျားသည်၊ ကိုယ်ပူသည်", image: "/images/hsk/vocabulary/hsk3-fashao-fever.png", imageAltMy: "ကိုယ်ပူဖျားနာ၍ အိပ်ရာပေါ်တွင် နားနေစဉ် မိခင်က နဖူးစမ်းပြီး အပူချိန်တိုင်းပေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "发现": { meaningMy: "တွေ့ရှိသည်၊ သတိပြုမိသည်", image: "/images/hsk/vocabulary/hsk3-faxian-discover.png", imageAltMy: "တောလမ်းလျှောက်နေစဉ် သစ်ရွက်များကြားရှိ ငှက်သိုက်ကလေးကို ရုတ်တရက် တွေ့ရှိသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "方便": { meaningMy: "အဆင်ပြေသော၊ လွယ်ကူသော", image: "/images/hsk/vocabulary/hsk3-fangbian-convenient.png", imageAltMy: "အိမ်ဝင်ပေါက်တွင် စနစ်တကျထားရှိသော သော့၊ ထီး၊ ဖိနပ်နှင့် အိတ်တို့ထဲမှ လိုအပ်သောထီးကို လွယ်ကူစွာ ယူနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "放": { meaningMy: "ထားသည်၊ လွှတ်သည်၊ ထည့်သည်", image: "/images/hsk/vocabulary/hsk3-fang-put.png", imageAltMy: "အစိမ်းရောင်စာအုပ်တစ်အုပ်ကို စာအုပ်စင်ပေါ်သို့ သေချာစွာ ထားနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "放心": { meaningMy: "စိတ်ချသည်၊ စိုးရိမ်မှုကင်းသည်", image: "/images/hsk/vocabulary/hsk3-fangxin-relieved.png", imageAltMy: "ကလေးငယ် ဘေးကင်းစွာ အိပ်ပျော်နေသည်ကို မြင်ပြီး စိတ်ချလက်ချ အနားယူနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "分": { meaningMy: "ခွဲသည်၊ မိနစ်၊ အမှတ် သို့မဟုတ် အပိုင်း", image: "/images/hsk/vocabulary/hsk3-fen-divide.png", imageAltMy: "လိမ္မော်သီးများကို သူငယ်ချင်းများ၏ ပန်းကန်များထဲသို့ အညီအမျှ ခွဲဝေပေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "附近": { meaningMy: "အနီးအနား၊ အနီးတစ်ဝိုက်", image: "/images/hsk/vocabulary/hsk3-fujin-nearby.png", imageAltMy: "အိမ်မှ ခြေလှမ်းအနည်းငယ်သာဝေးသော အနီးအနားကုန်စုံဆိုင်လေးကို ညွှန်ပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "复习": { meaningMy: "ပြန်လည်လေ့လာသည်၊ စာပြန်နွေးသည်", image: "/images/hsk/vocabulary/hsk3-fuxi-review.png", imageAltMy: "ရုပ်ပုံမှတ်စုနှင့် ကတ်များကို ပြန်လည်ကြည့်ရှု၍ သင်ခန်းစာကို စာပြန်နွေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "干净": { meaningMy: "သန့်ရှင်းသော", image: "/images/hsk/vocabulary/hsk3-ganjing-clean.png", imageAltMy: "တောက်ပြောင်သန့်ရှင်းသော သစ်သားစားပွဲကို အဝတ်ဖြင့် သုတ်သင်ရှင်းလင်းနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "敢": { meaningMy: "ရဲဝံ့သည်၊ လုပ်ရဲသည်", image: "/images/hsk/vocabulary/hsk3-gan-brave.png", imageAltMy: "ဘေးကင်းရေးကြိုးတပ်ဆင်ပြီး တောအုပ်အတွင်းရှိ ကြိုးတံတားပေါ်သို့ ရဲဝံ့စွာ လှမ်းတက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "感冒": { meaningMy: "အအေးမိသည်၊ အအေးမိရောဂါ", image: "/images/hsk/vocabulary/hsk3-ganmao-cold.png", imageAltMy: "နှာခေါင်းနီ၍ စောင်ခြုံထားကာ တစ်ရှူးဖြင့် နှာချေနေသော အအေးမိနေသည့် BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "刚才": { meaningMy: "ခုနက၊ မကြာမီက", image: "/images/hsk/vocabulary/hsk3-gangcai-just-now.png", imageAltMy: "ခုလေးတင် အိမ်မှ ထွက်သွားသော သူငယ်ချင်းကို တံခါးဝမှ လက်ပြနှုတ်ဆက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "根据": { meaningMy: "…အပေါ် အခြေခံ၍၊ အခြေခံချက်", image: "/images/hsk/vocabulary/hsk3-genju-based-on.png", imageAltMy: "ပန်းပင်၏ အရွက်ပုံသဏ္ဌာန်ကို နမူနာအရွက်များနှင့် နှိုင်းယှဉ်ကာ အထောက်အထားပေါ် အခြေခံ၍ လေ့လာနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "跟": { meaningMy: "…နှင့်၊ …နောက်လိုက်သည်", image: "/images/hsk/vocabulary/hsk3-gen-follow.png", imageAltMy: "ဥယျာဉ်လမ်းပေါ်တွင် မိသားစုဝင်တစ်ဦး၏ နောက်မှ လိုက်ပါလမ်းလျှောက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "更": { meaningMy: "ပို၍၊ ထပ်မံ၍", image: "/images/hsk/vocabulary/hsk3-geng-more.png", imageAltMy: "ပန်းပင်များပြည့်နေသော လသာဆောင်ဥယျာဉ်ကို ပိုမိုလှပစေရန် ပန်းအိုးတစ်အိုး ထပ်မံဖြည့်စွက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "公园": { meaningMy: "အများပြည်သူဥယျာဉ်၊ ပန်းခြံ", image: "/images/hsk/vocabulary/hsk3-gongyuan-park.png", imageAltMy: "သစ်ပင်၊ မြက်ခင်း၊ လမ်းလျှောက်လမ်းနှင့် အနားယူသူများရှိသော အများပြည်သူပန်းခြံတွင် လမ်းလျှောက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "故事": { meaningMy: "ပုံပြင်၊ ဇာတ်လမ်း", image: "/images/hsk/vocabulary/hsk3-gushi-story.png", imageAltMy: "ကလေးများ ဝိုင်းထိုင်နားထောင်နေစဉ် စိတ်ဝင်စားဖွယ် ပုံပြင်တစ်ပုဒ်ကို လက်ဟန်အမူအရာဖြင့် ပြောပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "刮": { meaningMy: "လေတိုက်သည်၊ ခြစ်သည်၊ ရိတ်သည်", image: "/images/hsk/vocabulary/hsk3-gua-wind.png", imageAltMy: "လေပြင်းတိုက်ခတ်၍ သစ်ရွက်များ လွင့်ပျံနေသောလမ်းတွင် ဦးထုပ်ကို မလွင့်စေရန် ကိုင်ထားသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "关": { meaningMy: "ပိတ်သည်၊ ဆက်နွှယ်သည်", image: "/images/hsk/vocabulary/hsk3-guan-close.png", imageAltMy: "ညနေမိုးရွာလာချိန် သစ်သားပြတင်းပေါက်တံခါးနှစ်ဖက်ကို လက်ဖြင့် ဆွဲပိတ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "关系": { meaningMy: "ဆက်ဆံရေး၊ ဆက်နွှယ်မှု", image: "/images/hsk/vocabulary/hsk3-guanxi-relationship.png", imageAltMy: "မိသားစုဝင်အကြီးအကဲနှင့် သူငယ်ချင်းတို့၏ လက်ကို ကိုင်ကာ နွေးထွေးသော ဆက်ဆံရေးကို ဖော်ပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "关心": { meaningMy: "ဂရုစိုက်သည်၊ အလေးထားသည်", image: "/images/hsk/vocabulary/hsk3-guanxin-care.png", imageAltMy: "သက်ကြီးရွယ်အိုတစ်ဦးကို နွေးထွေးသော ပုဝါခြုံပေးပြီး ရေနွေးခွက်ပေးကာ ဂရုစိုက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "关于": { meaningMy: "…နှင့်ပတ်သက်၍၊ …အကြောင်း", image: "/images/hsk/vocabulary/hsk3-guanyu-about.png", imageAltMy: "သစ်ပင်ငယ်နှင့် ကမ္ဘာလုံးပုံကို ကြည့်ကာ သဘာဝထိန်းသိမ်းရေးအကြောင်း သူငယ်ချင်းနှင့် ဆွေးနွေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "国家": { meaningMy: "နိုင်ငံ၊ နိုင်ငံတော်", image: "/images/hsk/vocabulary/hsk3-guojia-country.png", imageAltMy: "မြစ်၊ လယ်ယာ၊ မြို့ရွာ၊ မြို့ကြီးနှင့် စေတီပုထိုးတို့ ပါဝင်သော မြန်မာနိုင်ငံရှုခင်းရှေ့တွင် ပြည်သူများနှင့်အတူ ရပ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "果汁": { meaningMy: "သစ်သီးဖျော်ရည်" },
  "过去": { meaningMy: "အတိတ်၊ အရင်က၊ ဖြတ်သွားသည်" },
  "还是": { meaningMy: "သို့မဟုတ်၊ ဖြစ်နေဆဲ၊ ပို၍သင့်တော်သည်" },
  "害怕": { meaningMy: "ကြောက်သည်၊ ကြောက်ရွံ့သည်" },
  "河": { meaningMy: "မြစ်" },
  "黑板": { meaningMy: "ကျောက်သင်ပုန်း၊ သင်ပုန်း" },
  "护照": { meaningMy: "နိုင်ငံကူးလက်မှတ်" },
  "花": { meaningMy: "ပန်း၊ သုံးစွဲသည်၊ အချိန်ကုန်သည်" },
  "花园": { meaningMy: "ပန်းခြံ၊ ဥယျာဉ်" },
  "画": { meaningMy: "ပုံဆွဲသည်၊ ပန်းချီကား" },
  "坏": { meaningMy: "ပျက်သော၊ ဆိုးသော" },
  "环境": { meaningMy: "ပတ်ဝန်းကျင်၊ အခြေအနေ" },
  "换": { meaningMy: "လဲလှယ်သည်၊ ပြောင်းသည်" },
  "黄": { meaningMy: "အဝါရောင်၊ ဝါသော" },
  "会议": { meaningMy: "အစည်းအဝေး၊ ညီလာခံ" },
  "或者": { meaningMy: "သို့မဟုတ်" },
  "机会": { meaningMy: "အခွင့်အရေး၊ အခွင့်အလမ်း" },
  "几乎": { meaningMy: "နီးပါး၊ လုနီးပါး" },
  "极": { meaningMy: "အလွန်အမင်း၊ အဆုံးစွန်" },
  "记得": { meaningMy: "မှတ်မိသည်၊ မမေ့ဘဲ သတိရသည်" },
  "季节": { meaningMy: "ရာသီဥတုကာလ၊ ရာသီ" },
  "检查": { meaningMy: "စစ်ဆေးသည်၊ စစ်ဆေးခြင်း" },
  "简单": { meaningMy: "ရိုးရှင်းသော၊ လွယ်ကူသော" },
  "见面": { meaningMy: "တွေ့ဆုံသည်၊ မျက်နှာချင်းဆိုင်တွေ့သည်" },
  "健康": { meaningMy: "ကျန်းမာခြင်း၊ ကျန်းမာသော" },
  "讲": { meaningMy: "ပြောသည်၊ ရှင်းပြသည်၊ သင်ကြားပို့ချသည်" },
  "教": { meaningMy: "သင်ပေးသည်၊ သင်ကြားသည်" },
  "脚": { meaningMy: "ခြေထောက်၊ ခြေဖဝါး" },
  "角": { meaningMy: "ထောင့်၊ ငွေတစ်ယွမ်၏ ဆယ်ပုံတစ်ပုံ" },
  "接": { meaningMy: "လက်ခံသည်၊ သွားကြိုသည်၊ ဆက်သည်" },
  "街道": { meaningMy: "လမ်း၊ လမ်းမ၊ ရပ်ကွက်အုပ်ချုပ်ရေးနယ်မြေ" },
  "节目": { meaningMy: "အစီအစဉ်၊ ဖျော်ဖြေတင်ဆက်မှု" },
  "节日": { meaningMy: "ပွဲတော်နေ့၊ အထိမ်းအမှတ်နေ့" },
  "结婚": { meaningMy: "လက်ထပ်သည်၊ အိမ်ထောင်ပြုသည်" },
  "结束": { meaningMy: "ပြီးဆုံးသည်၊ အဆုံးသတ်သည်" },
  "解决": { meaningMy: "ဖြေရှင်းသည်၊ ကိုင်တွယ်ဖြေရှင်းသည်" },
  "借": { meaningMy: "ချေးသည်၊ ငှားသည်" },
  "经常": { meaningMy: "မကြာခဏ၊ အမြဲလိုလို" },
  "经过": { meaningMy: "ဖြတ်သန်းသည်၊ ဖြစ်စဉ်၊ အတွေ့အကြုံ" },
  "经理": { meaningMy: "မန်နေဂျာ၊ စီမံခန့်ခွဲရေးမှူး" },
  "久": { meaningMy: "ကြာမြင့်သော၊ အချိန်ကြာသော" },
  "旧": { meaningMy: "ဟောင်းသော၊ ယခင်က" },
  "举行": { meaningMy: "ကျင်းပသည်၊ ပြုလုပ်သည်" },
  "句子": { meaningMy: "ဝါကျ" },
  "决定": { meaningMy: "ဆုံးဖြတ်သည်၊ ဆုံးဖြတ်ချက်" },
  "渴": { meaningMy: "ရေငတ်သော" },
  "可爱": { meaningMy: "ချစ်စရာကောင်းသော" },
  "刻": { meaningMy: "ထွင်းသည်၊ ဆယ့်ငါးမိနစ်၊ အခိုက်အတန့်" },
  "客人": { meaningMy: "ဧည့်သည်၊ ဖောက်သည်" },
  "空调": { meaningMy: "လေအေးပေးစက်၊ လေအပူချိန်ထိန်းစက်" },
  "口": { meaningMy: "ပါးစပ်၊ လူဦးရေ သို့မဟုတ် ရေတွင်းကို ရေတွက်သော ပုဒ်" },
  "哭": { meaningMy: "ငိုသည်" },
  "裤子": { meaningMy: "ဘောင်းဘီ" },
  "筷子": { meaningMy: "တူ၊ စားပွဲသုံးတူ" },
  "蓝": { meaningMy: "အပြာရောင်၊ ပြာသော" },
  "老": { meaningMy: "အသက်ကြီးသော၊ ဟောင်းသော၊ အမြဲတမ်း" },
  "离开": { meaningMy: "ထွက်ခွာသည်၊ ခွဲခွာသည်" },
  "礼物": { meaningMy: "လက်ဆောင်" },
  "历史": { meaningMy: "သမိုင်း၊ ရာဇဝင်" },
  "脸": { meaningMy: "မျက်နှာ" },
  "练习": { meaningMy: "လေ့ကျင့်သည်၊ လေ့ကျင့်ခန်း" },
  "辆": { meaningMy: "ယာဉ်များကို ရေတွက်သော ပုဒ်၊ စီး" },
  "了解": { meaningMy: "သိရှိနားလည်သည်၊ လေ့လာသိရှိသည်" },
  "邻居": { meaningMy: "အိမ်နီးချင်း" },
  "楼": { meaningMy: "အဆောက်အအုံ၊ အထပ်" },
  "绿": { meaningMy: "အစိမ်းရောင်၊ စိမ်းသော" },
  "马": { meaningMy: "မြင်း" },
  "马上": { meaningMy: "ချက်ချင်း၊ မကြာမီ" },
  "满意": { meaningMy: "ကျေနပ်သည်၊ စိတ်တိုင်းကျသည်" },
  "帽子": { meaningMy: "ဦးထုပ်" },
  "米": { meaningMy: "ဆန်၊ မီတာ" },
  "面包": { meaningMy: "ပေါင်မုန့်" },
  "面条": { meaningMy: "ခေါက်ဆွဲ" },
  "明白": { meaningMy: "နားလည်သည်၊ ရှင်းလင်းသော" },
  "拿": { meaningMy: "ယူသည်၊ ကိုင်သည်၊ သယ်သည်" },
  "奶奶": { meaningMy: "အဖွား၊ ဖခင်ဘက်မှ အဖွား" },
  "南": { meaningMy: "တောင်ဘက်" },
  "难": { meaningMy: "ခက်ခဲသော၊ လုပ်ရခက်သော" },
  "难过": { meaningMy: "ဝမ်းနည်းသည်၊ စိတ်မကောင်းဖြစ်သည်" },
  "年级": { meaningMy: "ပညာသင်နှစ်အဆင့်၊ အတန်း" },
  "年轻": { meaningMy: "ငယ်ရွယ်သော၊ လူငယ်ဖြစ်သော" },
  "鸟": { meaningMy: "ငှက်" },
  "努力": { meaningMy: "ကြိုးစားသည်၊ အားထုတ်သည်" },
  "爬山": { meaningMy: "တောင်တက်သည်" },
  "盘子": { meaningMy: "ပန်းကန်ပြား" },
  "胖": { meaningMy: "ဝသော၊ အဆီများသော" },
  "啤酒": { meaningMy: "ဘီယာ" },
  "葡萄": { meaningMy: "စပျစ်သီး" },
  "普通话": { meaningMy: "စံတရုတ်စကား၊ Putonghua" },
  "骑": { meaningMy: "စီးသည်၊ ခွစီးသည်" },
  "其实": { meaningMy: "အမှန်စင်စစ်၊ တကယ်တော့" },
  "其他": { meaningMy: "အခြား၊ အခြားသော" },
  "奇怪": { meaningMy: "ထူးဆန်းသော၊ အံ့ဩဖွယ်ဖြစ်သော" },
  "铅笔": { meaningMy: "ခဲတံ" },
  "清楚": { meaningMy: "ရှင်းလင်းသော၊ ကောင်းစွာသိနားလည်သော" },
  "秋": { meaningMy: "ဆောင်းဦးရာသီ" },
  "裙子": { meaningMy: "စကတ်၊ ဂါဝန်အောက်ပိုင်း" },
  "然后": { meaningMy: "ထို့နောက်၊ ပြီးလျှင်" },
  "热情": { meaningMy: "နွေးထွေးဖော်ရွေသော၊ စိတ်အားထက်သန်မှု" },
  "认为": { meaningMy: "ယူဆသည်၊ ထင်မြင်သည်" },
  "认真": { meaningMy: "အလေးအနက်ထားသော၊ စေ့စပ်သေချာသော" },
  "容易": { meaningMy: "လွယ်ကူသော၊ ဖြစ်လွယ်သော" },
  "如果": { meaningMy: "အကယ်၍၊ လျှင်" },
  "伞": { meaningMy: "ထီး" },
  "上网": { meaningMy: "အင်တာနက်အသုံးပြုသည်၊ အွန်လိုင်းတက်သည်" },
  "生气": { meaningMy: "စိတ်ဆိုးသည်၊ ဒေါသထွက်သည်" },
  "声音": { meaningMy: "အသံ" },
  "使": { meaningMy: "ဖြစ်စေသည်၊ အသုံးပြုသည်၊ စေလွှတ်သည်" },
  "世界": { meaningMy: "ကမ္ဘာ၊ လောက" },
  "瘦": { meaningMy: "ပိန်သော၊ ချောင်သော" },
  "舒服": { meaningMy: "သက်သောင့်သက်သာရှိသော၊ နေကောင်းသော" },
  "叔叔": { meaningMy: "ဦးလေး၊ ဖခင်၏ညီ သို့မဟုတ် အသက်ကြီးအမျိုးသားကို ခေါ်ဝေါ်သည့်စကား" },
  "树": { meaningMy: "သစ်ပင်" },
  "数学": { meaningMy: "သင်္ချာဘာသာရပ်" },
  "刷": { meaningMy: "ပွတ်တိုက်သန့်ရှင်းသည်၊ ဘရပ်ရှ်ဖြင့်တိုက်သည်" },
  "双": { meaningMy: "တစ်စုံ၊ နှစ်ခုတွဲကို ရေတွက်သော ပုဒ်" },
  "水平": { meaningMy: "အဆင့်အတန်း၊ စွမ်းရည်အဆင့်၊ ရေပြင်ညီ" },
  "司机": { meaningMy: "ယာဉ်မောင်း" },
  "虽然": { meaningMy: "…သော်လည်း၊ …ဖြစ်သော်ငြား" },
  "太阳": { meaningMy: "နေ၊ နေမင်း" },
  "糖": { meaningMy: "သကြား၊ သကြားလုံး" },
  "特别": { meaningMy: "အထူး၊ အထူးသဖြင့်" },
  "疼": { meaningMy: "နာကျင်သည်၊ ကိုက်ခဲသည်" },
  "提高": { meaningMy: "မြှင့်တင်သည်၊ တိုးတက်စေသည်" },
  "体育": { meaningMy: "အားကစား၊ ကာယပညာ" },
  "甜": { meaningMy: "ချိုသော" },
  "条": { meaningMy: "ရှည်လျားသောအရာ၊ ငါး၊ လမ်း သို့မဟုတ် အချက်များကို ရေတွက်သော ပုဒ်" },
  "同事": { meaningMy: "လုပ်ဖော်ကိုင်ဖက်" },
  "同意": { meaningMy: "သဘောတူသည်၊ ခွင့်ပြုသည်" },
  "头发": { meaningMy: "ဆံပင်" },
  "突然": { meaningMy: "ရုတ်တရက်၊ မမျှော်လင့်ဘဲ" },
  "图书馆": { meaningMy: "စာကြည့်တိုက်" },
  "腿": { meaningMy: "ခြေထောက်" },
  "完成": { meaningMy: "ပြီးမြောက်သည်၊ အပြီးသတ်သည်" },
  "碗": { meaningMy: "ပန်းကန်လုံး၊ ပန်းကန်လုံးဖြင့် ရေတွက်သော ပုဒ်" },
  "万": { meaningMy: "တစ်သောင်း၊ သောင်း" },
  "忘记": { meaningMy: "မေ့သည်၊ မေ့လျော့သည်" },
  "为了": { meaningMy: "…အတွက်၊ …ရန်ရည်ရွယ်၍" },
  "为什么": { meaningMy: "ဘာကြောင့်၊ အဘယ်ကြောင့်" },
  "位": { meaningMy: "လူကို ရိုသေစွာ ရေတွက်သော ပုဒ်၊ ဦး၊ ယောက်" },
  "文化": { meaningMy: "ယဉ်ကျေးမှု၊ ယဉ်ကျေးမှုဆိုင်ရာ" },
  "西": { meaningMy: "အနောက်ဘက်" },
  "习惯": { meaningMy: "အလေ့အကျင့်၊ အသားကျသည်" },
  "洗手间": { meaningMy: "သန့်စင်ခန်း၊ အိမ်သာ" },
  "洗澡": { meaningMy: "ရေချိုးသည်" },
  "夏": { meaningMy: "နွေရာသီ" },
  "先": { meaningMy: "ဦးစွာ၊ အရင်" },
  "香蕉": { meaningMy: "ငှက်ပျောသီး" },
  "相同": { meaningMy: "တူညီသော၊ အတူတူဖြစ်သော" },
  "相信": { meaningMy: "ယုံကြည်သည်၊ ယုံကြည်လက်ခံသည်" },
  "像": { meaningMy: "တူသည်၊ …ကဲ့သို့၊ ရုပ်ပုံ" },
  "小心": { meaningMy: "သတိထားသည်၊ ဂရုစိုက်သည်" },
  "校长": { meaningMy: "ကျောင်းအုပ်ကြီး" },
  "鞋": { meaningMy: "ဖိနပ်" },
  "新闻": { meaningMy: "သတင်း၊ သတင်းအချက်အလက်" },
  "新鲜": { meaningMy: "လတ်ဆတ်သော၊ အသစ်အဆန်းဖြစ်သော" },
  "信": { meaningMy: "စာ၊ ယုံကြည်သည်" },
  "行李箱": { meaningMy: "ခရီးဆောင်သေတ္တာ" },
  "兴趣": { meaningMy: "စိတ်ဝင်စားမှု၊ ဝါသနာ" },
  "熊猫": { meaningMy: "ပန်ဒါဝက်ဝံ" },
  "需要": { meaningMy: "လိုအပ်သည်၊ လိုအပ်ချက်" },
  "选择": { meaningMy: "ရွေးချယ်သည်၊ ရွေးချယ်မှု" },
  "眼镜": { meaningMy: "မျက်မှန်" },
  "要求": { meaningMy: "တောင်းဆိုသည်၊ သတ်မှတ်ချက်၊ လိုအပ်ချက်" },
  "爷爷": { meaningMy: "အဘိုး၊ ဖခင်ဘက်မှ အဘိုး" },
  "一定": { meaningMy: "သေချာပေါက်၊ မုချ၊ သတ်မှတ်ထားသော" },
  "一共": { meaningMy: "စုစုပေါင်း၊ အားလုံးပေါင်း" },
  "一会儿": { meaningMy: "ခဏ၊ ခဏအကြာ" },
  "一样": { meaningMy: "တူညီသော၊ အတူတူ" },
  "以后": { meaningMy: "နောက်ပိုင်း၊ နောင်တွင်" },
  "以前": { meaningMy: "ယခင်က၊ အရင်က" },
  "以为": { meaningMy: "…ဟု ထင်မှတ်ခဲ့သည်" },
  "一般": { meaningMy: "သာမန်၊ ယေဘုယျအားဖြင့်" },
  "一边": { meaningMy: "တစ်ဖက်၊ တစ်ပြိုင်နက်တည်း လုပ်ဆောင်မှုကို ဖော်ပြသော စကား" },
  "一直": { meaningMy: "တောက်လျှောက်၊ အစဉ်မပြတ်၊ တည့်တည့်" },
  "音乐": { meaningMy: "ဂီတ၊ တေးဂီတ" },
  "银行": { meaningMy: "ဘဏ်" },
  "应该": { meaningMy: "လုပ်သင့်သည်၊ ဖြစ်သင့်သည်" },
  "影响": { meaningMy: "သက်ရောက်မှု၊ သက်ရောက်စေသည်" },
  "用": { meaningMy: "အသုံးပြုသည်၊ သုံးသည်" },
  "游戏": { meaningMy: "ကစားနည်း၊ ဂိမ်း၊ ကစားသည်" },
  "有名": { meaningMy: "နာမည်ကျော်သော၊ ကျော်ကြားသော" },
  "又": { meaningMy: "ထပ်၍၊ လည်းပဲ၊ တစ်ဖန်" },
  "遇到": { meaningMy: "တွေ့ကြုံသည်၊ ဆုံတွေ့သည်" },
  "愿意": { meaningMy: "ဆန္ဒရှိသည်၊ လိုလားသည်" },
  "越": { meaningMy: "ပို၍ပို၍ ဖြစ်လာမှုကို ဖော်ပြသော စကား၊ ကျော်ဖြတ်သည်" },
  "月亮": { meaningMy: "လ၊ လမင်း" },
  "云": { meaningMy: "မိုးတိမ်၊ တိမ်" },
  "站": { meaningMy: "ရပ်သည်၊ ဘူတာ၊ ဌာန" },
  "着急": { meaningMy: "စိတ်လောသည်၊ စိုးရိမ်ပူပန်သည်" },
  "照顾": { meaningMy: "စောင့်ရှောက်သည်၊ ဂရုစိုက်သည်" },
  "照片": { meaningMy: "ဓာတ်ပုံ" },
  "照相机": { meaningMy: "ဓာတ်ပုံကင်မရာ" },
  "只|zhī": { meaningMy: "တိရစ္ဆာန်အချို့နှင့် တစ်ခုတည်းဖြစ်သော အရာများကို ရေတွက်သော ပုဒ်" },
  "只|zhǐ": { meaningMy: "သာလျှင်၊ ပဲ၊ ရုံသာ" },
  "终于": { meaningMy: "နောက်ဆုံးတွင်၊ အဆုံး၌" },
  "中间": { meaningMy: "အလယ်၊ အလယ်ဗဟို" },
  "种": { meaningMy: "အမျိုးအစား၊ မျိုး၊ စိုက်ပျိုးသည်" },
  "重要": { meaningMy: "အရေးကြီးသော" },
  "周末": { meaningMy: "စနေ၊ တနင်္ဂနွေ ရက်သတ္တပတ်အဆုံး" },
  "主要": { meaningMy: "အဓိက၊ အဓိကအားဖြင့်" },
  "祝": { meaningMy: "ဆုတောင်းသည်၊ မွန်မြတ်သောဆန္ဒပြုသည်" },
  "注意": { meaningMy: "သတိပြုသည်၊ ဂရုစိုက်သည်" },
  "字典": { meaningMy: "အဘိဓာန်" },
  "自己": { meaningMy: "မိမိကိုယ်တိုင်၊ ကိုယ်တိုင်" },
  "总是": { meaningMy: "အမြဲတမ်း၊ အစဉ်အမြဲ" },
  "最近": { meaningMy: "မကြာသေးမီက၊ လတ်တလော၊ အနီးဆုံး" },
  "作业": { meaningMy: "အိမ်စာ၊ လေ့ကျင့်ခန်းတာဝန်" },
  "作用": { meaningMy: "အကျိုးသက်ရောက်မှု၊ လုပ်ဆောင်ချက်၊ အခန်းကဏ္ဍ" },
};
