import type { VocabularyEnrichment } from "@/lib/hskVocabularyMy";

// HSK 2 editorial Burmese layer. Composite keys distinguish heteronyms.
export const hsk2VocabularyMy: Record<string, VocabularyEnrichment> = {
  "吧": { meaningMy: "အကြံပြုခြင်း၊ တိုက်တွန်းခြင်း သို့မဟုတ် ခန့်မှန်းခြင်းကို ဖော်ပြသော ဝါကျအဆုံးသတ်ပုဒ်", image: "/images/hsk/vocabulary/hsk2-ba-suggestion.png", imageAltMy: "ကော်ဖီဆိုင်တွင် အတူထိုင်ရန် ယဉ်ကျေးစွာ ဖိတ်ခေါ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "白": { meaningMy: "အဖြူရောင်၊ ဖြူသော", image: "/images/hsk/vocabulary/hsk2-bai-white.png", imageAltMy: "အမှောင်နောက်ခံရှေ့ရှိ အဖြူရောင်ပန်းအိုးနှင့် အဖြူရောင်အထည်ကို ပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "百": { meaningMy: "တစ်ရာ၊ ရာ", image: "/images/hsk/vocabulary/hsk2-bai-hundred.png", imageAltMy: "ပုတီးစေ့တစ်ရာကို ဆယ်တန်းစီ စနစ်တကျ ပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "帮助": { meaningMy: "ကူညီသည်၊ အကူအညီ", image: "/images/hsk/vocabulary/hsk2-bangzhu-help.png", imageAltMy: "အဘိုးတစ်ဦးအား ကုန်ခြောက်သေတ္တာ သယ်ပေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "报纸": { meaningMy: "သတင်းစာ", image: "/images/hsk/vocabulary/hsk2-baozhi-newspaper.png", imageAltMy: "မနက်စာစားပွဲတွင် သတင်းစာဖတ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "比": { meaningMy: "နှိုင်းယှဉ်ရာတွင် ‘…ထက်’ ဟု ဖော်ပြသော ပုဒ်", image: "/images/hsk/vocabulary/hsk2-bi-compare.png", imageAltMy: "အမြင့်မတူသော အပင်နှစ်ပင်ကို ချိန်ခွင်ဖြင့် နှိုင်းယှဉ်ပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "别": { meaningMy: "မ…နှင့်၊ မလုပ်ပါနှင့်", image: "/images/hsk/vocabulary/hsk2-bie-do-not.png", imageAltMy: "ကလေးအား ပူသောရေနွေးအိုး မထိရန် ညင်သာစွာ တားဆီးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "长|cháng": { meaningMy: "ရှည်သော၊ အလျား", image: "/images/hsk/vocabulary/hsk2-chang-long.png", imageAltMy: "ရှည်သောဖဲကြိုးနှင့် တိုသောဖဲကြိုးကို နှိုင်းယှဉ်ပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "唱歌": { meaningMy: "သီချင်းဆိုသည်", image: "/images/hsk/vocabulary/hsk2-changge-sing.png", imageAltMy: "တေးဂီတလေ့ကျင့်ခန်းခန်းတွင် မိုက်ခရိုဖုန်းဖြင့် သီချင်းဆိုနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "出": { meaningMy: "ထွက်သည်၊ အပြင်သို့ သွားသည်", image: "/images/hsk/vocabulary/hsk2-chu-go-out.png", imageAltMy: "အိမ်တံခါးမှ နေရောင်ရှိသော အပြင်ဘက်သို့ ထွက်လာသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "穿": { meaningMy: "ဝတ်သည်၊ စွပ်သည်", image: "/images/hsk/vocabulary/hsk2-chuan-wear.png", imageAltMy: "မှန်ရှေ့တွင် အစိမ်းရောင်လိုဂိုအင်္ကျီကို ဝတ်ဆင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "船": { meaningMy: "သင်္ဘော၊ လှေ", image: "/images/hsk/vocabulary/hsk2-chuan-boat.png", imageAltMy: "မြန်မာ့မြစ်ပေါ်ရှိ သစ်သားခရီးသည်တင်လှေတွင် စီးနင်းနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "次": { meaningMy: "အကြိမ်ရေကို ရေတွက်သော ပုဒ်၊ အကြိမ်", image: "/images/hsk/vocabulary/hsk2-ci-times.png", imageAltMy: "ထပ်ခါတလဲလဲ လေ့ကျင့်မှုတစ်ကြိမ်စီကို ကတ်များဖြင့် စီစဉ်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "从": { meaningMy: "…မှ၊ …ကနေ", image: "/images/hsk/vocabulary/hsk2-cong-from.png", imageAltMy: "အိမ်မှစ၍ ဥယျာဉ်မဏ္ဍပ်ဘက်သို့ လမ်းလျှောက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "错": { meaningMy: "မှားသော၊ အမှား", image: "/images/hsk/vocabulary/hsk2-cuo-mistake.png", imageAltMy: "ပုံသဏ္ဌာန်တုံးကို မှားယွင်းသောအပေါက်တွင် ထည့်ထားကြောင်း သိရှိပြီး ပြင်ဆင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "打篮球": { meaningMy: "ဘတ်စကက်ဘော ကစားသည်", image: "/images/hsk/vocabulary/hsk2-dalanqiu-basketball.png", imageAltMy: "အပြင်ဘက်ကွင်းတွင် ဘတ်စကက်ဘောကို လက်ဖြင့်ပုတ်ကစားနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "大家": { meaningMy: "အားလုံး၊ လူတိုင်း", image: "/images/hsk/vocabulary/hsk2-dajia-everyone.png", imageAltMy: "မြန်မာကျောင်းသားအားလုံး ပါဝင်သည့် စာလေ့လာဝိုင်းကို ဦးဆောင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "但是": { meaningMy: "သို့သော်၊ ဒါပေမဲ့", image: "/images/hsk/vocabulary/hsk2-danshi-but.png", imageAltMy: "ပျော်ပွဲစားထွက်ရန် ပြင်ဆင်ထားသော်လည်း မိုးရွာလာ၍ ထီးဖွင့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "到": { meaningMy: "ရောက်သည်၊ …အထိ၊ …သို့", image: "/images/hsk/vocabulary/hsk2-dao-arrive.png", imageAltMy: "ခရီးဆောင်အိတ်နှင့်အတူ ဘူတာရုံသို့ ရောက်ရှိလာသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "得|de": { meaningMy: "ကြိယာနောက်တွင် ဖြည့်စွက်ဖော်ပြချက်ကို ဆက်ပေးသော ဖွဲ့စည်းပုံပုဒ်", image: "/images/hsk/vocabulary/hsk2-de-complement.png", imageAltMy: "လျင်မြန်ကောင်းမွန်စွာ ပြေးနိုင်မှုကို သူငယ်ချင်းရှေ့တွင် ပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "得|děi": { meaningMy: "မဖြစ်မနေ လုပ်ရမည်၊ လိုအပ်သည်", image: "/images/hsk/vocabulary/hsk2-de-must.png", imageAltMy: "မိုးရွာနေသဖြင့် အပြင်မထွက်မီ ထီးနှင့် မိုးကာကို မဖြစ်မနေ ပြင်ဆင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "弟弟": { meaningMy: "ညီ၊ မောင်", image: "/images/hsk/vocabulary/hsk2-didi-younger-brother.png", imageAltMy: "ညီငယ်နှင့်အတူ သစ်သားလေယာဉ်ပျံအရုပ်ကို နွေးထွေးစွာ တပ်ဆင်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "第一": { meaningMy: "ပထမ၊ နံပါတ်တစ်", image: "/images/hsk/vocabulary/hsk2-diyi-first.png", imageAltMy: "အခြားပြိုင်ပွဲဝင်များထက် ရှေ့ဆုံးမှ ပန်းဝင်ကြိုးကို ပထမဆုံး ဖြတ်ကျော်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "懂": { meaningMy: "နားလည်သည်၊ သိနားလည်သည်", image: "/images/hsk/vocabulary/hsk2-dong-understand.png", imageAltMy: "ကမ္ဘာလုံးပုံ ပဟေဠိကို မှန်ကန်စွာ ပြီးမြောက်၍ နားလည်သဘောပေါက်သွားသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "房间": { meaningMy: "အခန်း", image: "/images/hsk/vocabulary/hsk2-fangjian-room.png", imageAltMy: "အိပ်ရာ၊ စာကြည့်စားပွဲနှင့် ပြတင်းပေါက်ပါသော သပ်ရပ်သည့်အခန်းကို ပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "非常": { meaningMy: "အလွန်၊ အလွန်အမင်း", image: "/images/hsk/vocabulary/hsk2-feichang-extremely.png", imageAltMy: "အလွန်ကြီးမားသော နေကြာပန်းကို အံ့အားသင့်စွာ ကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "服务员": { meaningMy: "ဝန်ဆောင်မှုဝန်ထမ်း၊ စားပွဲထိုး", image: "/images/hsk/vocabulary/hsk2-fuwuyuan-waiter.png", imageAltMy: "စားသောက်ဆိုင်တွင် ဖောက်သည်အား အစားအသောက်နှင့် လက်ဖက်ရည် ယဉ်ကျေးစွာ တည်ခင်းပေးနေသော စားပွဲထိုး", imageStatus: "generated" },
  "高": { meaningMy: "မြင့်သော၊ အရပ်ရှည်သော", image: "/images/hsk/vocabulary/hsk2-gao-tall.png", imageAltMy: "အလွန်မြင့်သော သစ်ပင်နှင့် အနိမ့်ချုံပင်ကို နှိုင်းယှဉ်ပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "告诉": { meaningMy: "ပြောပြသည်၊ အသိပေးသည်", image: "/images/hsk/vocabulary/hsk2-gaosu-tell.png", imageAltMy: "သူငယ်ချင်းအား လမ်းညွှန်ချက်ကို လက်ဟန်ဖြင့် ရှင်းလင်းပြောပြနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "哥哥": { meaningMy: "အစ်ကို", image: "/images/hsk/vocabulary/hsk2-gege-older-brother.png", imageAltMy: "ညီငယ် စက်ဘီးစီးတတ်စေရန် ဘေးမှ ကာကွယ်ကူညီပေးနေသော အစ်ကို BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "给": { meaningMy: "ပေးသည်၊ …အား/အတွက်", image: "/images/hsk/vocabulary/hsk2-gei-give.png", imageAltMy: "သူငယ်ချင်းအား လက်ဆောင်သေတ္တာကို လက်နှစ်ဖက်ဖြင့် ပေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "公共汽车": { meaningMy: "အများပြည်သူသုံး ဘတ်စ်ကား", image: "/images/hsk/vocabulary/hsk2-gonggongqiche-bus.png", imageAltMy: "ဘတ်စ်ကားမှတ်တိုင်တွင် အစိမ်းရောင် အများပြည်သူသုံးဘတ်စ်ကားပေါ် တက်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "公斤": { meaningMy: "ကီလိုဂရမ်", image: "/images/hsk/vocabulary/hsk2-gongjin-kilogram.png", imageAltMy: "ဈေးတွင် ဆန်အိတ်ကို တစ်ကီလိုဂရမ် စံအလေးနှင့် ချိန်ခွင်ပေါ် တိုင်းတာနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "公司": { meaningMy: "ကုမ္ပဏီ", image: "/images/hsk/vocabulary/hsk2-gongsi-company.png", imageAltMy: "ခေတ်မီကုမ္ပဏီရုံးခန်းတွင် လုပ်ဖော်ကိုင်ဖက်များနှင့် အဖွဲ့လိုက်ဆွေးနွေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "贵": { meaningMy: "ဈေးကြီးသော၊ တန်ဖိုးကြီးသော", image: "/images/hsk/vocabulary/hsk2-gui-expensive.png", imageAltMy: "လက်မှုပစ္စည်းဆိုင်ရှိ တန်ဖိုးကြီး ကျောက်စိမ်းလက်ရာကို ငွေအိတ်ဗလာဖြင့် စဉ်းစားကြည့်နေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "还|hái": { meaningMy: "သေးသည်၊ ထို့အပြင်၊ လည်း", image: "/images/hsk/vocabulary/hsk2-hai-still.png", imageAltMy: "ညနက်ချိန်အထိ စာကြည့်မီးအောက်တွင် ဆက်လက်စာလေ့လာနေဆဲ BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "孩子": { meaningMy: "ကလေး၊ သားသမီး", image: "/images/hsk/vocabulary/hsk2-haizi-child.png", imageAltMy: "သင်ယူခန်းတွင် ပုံသဏ္ဌာန်များ ရောင်စုံခြယ်နေသော ကလေးငယ်ကို နွေးထွေးစွာ ကြည့်ရှုကူညီနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "好吃": { meaningMy: "အရသာရှိသော၊ စားကောင်းသော", image: "/images/hsk/vocabulary/hsk2-haochi-delicious.png", imageAltMy: "အငွေ့ပျံနေသော တရုတ်နှင့်မြန်မာ အစားအစာများကို အရသာရှိစွာ စားသုံးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "号": { meaningMy: "နံပါတ်၊ ရက်စွဲ၊ အမှတ်", image: "/images/hsk/vocabulary/hsk2-hao-number.png", imageAltMy: "ဝန်ဆောင်မှုကောင်တာတွင် အစဉ်လိုက်ထားသော အမှတ်ပြတိုကင်များထဲမှ သတ်မှတ်ထားသည့်တစ်ခုကို ရွေးယူနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "黑": { meaningMy: "အနက်ရောင်၊ မည်းသော", image: "/images/hsk/vocabulary/hsk2-hei-black.png", imageAltMy: "တောက်ပသော အဖြူနောက်ခံရှေ့တွင် အနက်ရောင်ထီးနှင့် အနက်ရောင်အထည်ကို ပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "红": { meaningMy: "အနီရောင်၊ နီသော", image: "/images/hsk/vocabulary/hsk2-hong-red.png", imageAltMy: "အနီရောင်မီးပုံးနှင့် တောက်ပသော အနီရောင်ပဝါကို ပြသနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "欢迎": { meaningMy: "ကြိုဆိုသည်၊ ကြိုဆိုပါသည်", image: "/images/hsk/vocabulary/hsk2-huanying-welcome.png", imageAltMy: "BurmeseBridge သင်ယူရေးစင်တာ တံခါးဝတွင် သင်ယူသူများကို လက်နှစ်ဖက်ဖွင့်ကာ နွေးထွေးစွာ ကြိုဆိုနေသော လမ်းညွှန်", imageStatus: "generated" },
  "还|huán": { meaningMy: "ပြန်ပေးသည်၊ ပြန်ဆပ်သည်", image: "/images/hsk/vocabulary/hsk2-huan-return.png", imageAltMy: "စာကြည့်တိုက်ကောင်တာတွင် ငှားယူထားသော စာအုပ်ကို စာကြည့်တိုက်မှူးထံ ပြန်ပေးနေသော BurmeseBridge လမ်းညွှန်", imageStatus: "generated" },
  "回答": { meaningMy: "ဖြေကြားသည်၊ အဖြေ" },
  "机场": { meaningMy: "လေဆိပ်" },
  "鸡蛋": { meaningMy: "ကြက်ဥ" },
  "件": { meaningMy: "အဝတ်အစား၊ ကိစ္စ သို့မဟုတ် ပစ္စည်းအချို့ကို ရေတွက်သော ပုဒ်" },
  "教室": { meaningMy: "စာသင်ခန်း" },
  "姐姐": { meaningMy: "အစ်မ" },
  "介绍": { meaningMy: "မိတ်ဆက်သည်၊ ရှင်းလင်းတင်ပြသည်" },
  "进": { meaningMy: "ဝင်သည်၊ အတွင်းသို့ သွားသည်" },
  "近": { meaningMy: "နီးသော၊ အနီး" },
  "就": { meaningMy: "ချက်ချင်း၊ ထိုအခါ၊ သာလျှင်" },
  "觉得": { meaningMy: "ထင်မြင်သည်၊ ခံစားမိသည်" },
  "咖啡": { meaningMy: "ကော်ဖီ" },
  "开始": { meaningMy: "စတင်သည်၊ အစပြုသည်" },
  "考试": { meaningMy: "စာမေးပွဲ၊ စာမေးပွဲ ဖြေဆိုသည်" },
  "可能": { meaningMy: "ဖြစ်နိုင်သည်၊ ဖြစ်နိုင်ခြေ" },
  "可以": { meaningMy: "လုပ်နိုင်သည်၊ ခွင့်ပြုသည်၊ ရသည်" },
  "课": { meaningMy: "သင်ခန်းစာ၊ ဘာသာရပ်၊ အတန်းချိန်" },
  "快": { meaningMy: "မြန်သော၊ လျင်မြန်စွာ" },
  "快乐": { meaningMy: "ပျော်ရွှင်သော၊ ပျော်ရွှင်မှု" },
  "累": { meaningMy: "ပင်ပန်းသော၊ မောပန်းသော" },
  "离": { meaningMy: "…မှ အကွာအဝေးရှိသည်၊ …နှင့် ဝေးသည်" },
  "两": { meaningMy: "နှစ် (ရေတွက်ပုဒ်မတိုင်မီ သုံးသည်)" },
  "路": { meaningMy: "လမ်း၊ ခရီးလမ်း" },
  "旅游": { meaningMy: "ခရီးသွားသည်၊ အပန်းဖြေခရီး" },
  "卖": { meaningMy: "ရောင်းသည်" },
  "慢": { meaningMy: "နှေးသော၊ ဖြည်းဖြည်း" },
  "忙": { meaningMy: "အလုပ်များသော၊ မအားသော" },
  "每": { meaningMy: "တိုင်း၊ တစ်ခုချင်းစီ" },
  "妹妹": { meaningMy: "ညီမ၊ နှမ" },
  "门": { meaningMy: "တံခါး၊ ဝင်ပေါက်" },
  "男人": { meaningMy: "အမျိုးသား၊ ယောက်ျား" },
  "您": { meaningMy: "လူကြီးမင်း၊ သင် (ယဉ်ကျေးသုံးနှုန်း)" },
  "牛奶": { meaningMy: "နွားနို့" },
  "女人": { meaningMy: "အမျိုးသမီး၊ မိန်းမ" },
  "旁边": { meaningMy: "ဘေးနား၊ အနီးဘေး" },
  "跑步": { meaningMy: "ပြေးသည်၊ အပြေးလေ့ကျင့်သည်" },
  "便宜": { meaningMy: "ဈေးပေါသော၊ ဈေးသက်သာသော" },
  "票": { meaningMy: "လက်မှတ်၊ မဲလက်မှတ်" },
  "妻子": { meaningMy: "ဇနီး" },
  "起床": { meaningMy: "အိပ်ရာထသည်" },
  "千": { meaningMy: "တစ်ထောင်၊ ထောင်" },
  "晴": { meaningMy: "မိုးကင်းစင်သော၊ နေသာသော" },
  "去年": { meaningMy: "မနှစ်က၊ ယခင်နှစ်" },
  "让": { meaningMy: "ခွင့်ပြုသည်၊ စေသည်၊ လမ်းဖယ်ပေးသည်" },
  "上班": { meaningMy: "အလုပ်တက်သည်၊ အလုပ်သွားသည်" },
  "身体": { meaningMy: "ခန္ဓာကိုယ်၊ ကျန်းမာရေးအခြေအနေ" },
  "生病": { meaningMy: "ဖျားနာသည်၊ နေမကောင်းဖြစ်သည်" },
  "生日": { meaningMy: "မွေးနေ့" },
  "时间": { meaningMy: "အချိန်၊ ကာလ" },
  "事情": { meaningMy: "အကြောင်းကိစ္စ၊ အရေးကိစ္စ" },
  "手表": { meaningMy: "လက်ပတ်နာရီ" },
  "手机": { meaningMy: "လက်ကိုင်ဖုန်း၊ မိုဘိုင်းဖုန်း" },
  "送": { meaningMy: "ပို့ပေးသည်၊ လက်ဆောင်ပေးသည်၊ လိုက်ပို့သည်" },
  "所以": { meaningMy: "ထို့ကြောင့်၊ ဒါကြောင့်" },
  "它": { meaningMy: "၎င်း၊ အဲဒါ (လူမဟုတ်သောအရာကို ရည်ညွှန်း)" },
  "踢": { meaningMy: "ကန်သည်" },
  "题": { meaningMy: "မေးခွန်း၊ ခေါင်းစဉ်၊ ပုစ္ဆာ" },
  "跳舞": { meaningMy: "ကခုန်သည်" },
  "外": { meaningMy: "အပြင်၊ ပြင်ပ" },
  "完": { meaningMy: "ပြီးဆုံးသည်၊ ကုန်ဆုံးသည်" },
  "玩": { meaningMy: "ကစားသည်၊ အပန်းဖြေသည်" },
  "晚上": { meaningMy: "ညနေခင်း၊ ညအချိန်" },
  "为": { meaningMy: "…အတွက်၊ …၏အကျိုးအတွက်" },
  "问": { meaningMy: "မေးသည်၊ မေးမြန်းသည်" },
  "问题": { meaningMy: "မေးခွန်း၊ ပြဿနာ" },
  "西瓜": { meaningMy: "ဖရဲသီး" },
  "希望": { meaningMy: "မျှော်လင့်သည်၊ မျှော်လင့်ချက်" },
  "洗": { meaningMy: "ဆေးကြောသည်၊ လျှော်ဖွပ်သည်" },
  "向": { meaningMy: "…သို့၊ …ဘက်သို့၊ …အား" },
  "小时": { meaningMy: "နာရီ (အချိန်ကာလ)" },
  "笑": { meaningMy: "ရယ်သည်၊ ပြုံးသည်" },
  "新": { meaningMy: "အသစ်၊ သစ်သော" },
  "姓": { meaningMy: "မျိုးရိုးအမည်၊ မျိုးရိုးအမည်ဖြစ်သည်" },
  "休息": { meaningMy: "အနားယူသည်၊ အနားယူချိန်" },
  "雪": { meaningMy: "နှင်း၊ နှင်းကျခြင်း" },
  "颜色": { meaningMy: "အရောင်" },
  "眼睛": { meaningMy: "မျက်လုံး" },
  "羊肉": { meaningMy: "သိုးသား" },
  "药": { meaningMy: "ဆေးဝါး၊ ဆေး" },
  "要": { meaningMy: "လိုချင်သည်၊ လိုအပ်သည်၊ ပြုလုပ်မည်" },
  "也": { meaningMy: "လည်း၊ ထို့အတူ" },
  "已经": { meaningMy: "ပြီးပြီ၊ ယခင်ကတည်းက" },
  "一起": { meaningMy: "အတူတကွ၊ တစ်ပေါင်းတည်း" },
  "意思": { meaningMy: "အဓိပ္ပာယ်၊ သဘော၊ ရည်ရွယ်ချက်" },
  "阴": { meaningMy: "တိမ်ထူသော၊ နေမပွင့်သော" },
  "因为": { meaningMy: "…သောကြောင့်၊ အကြောင်းမှာ" },
  "游泳": { meaningMy: "ရေကူးသည်၊ ရေကူးခြင်း" },
  "右边": { meaningMy: "ညာဘက်" },
  "鱼": { meaningMy: "ငါး" },
  "元": { meaningMy: "ယွမ် (တရုတ်ငွေကြေးယူနစ်)" },
  "远": { meaningMy: "ဝေးသော၊ အလှမ်းဝေးသော" },
  "运动": { meaningMy: "အားကစားလုပ်သည်၊ လှုပ်ရှားမှု၊ အားကစား" },
  "再": { meaningMy: "ထပ်မံ၊ နောက်တစ်ကြိမ်" },
  "早上": { meaningMy: "မနက်ခင်း၊ နံနက်စောစော" },
  "张": { meaningMy: "ပြားချပ်သောအရာများကို ရေတွက်သော ပုဒ်၊ ဖြန့်သည်" },
  "长|zhǎng": { meaningMy: "ကြီးပြင်းသည်၊ အရွယ်ရောက်သည်" },
  "丈夫": { meaningMy: "ခင်ပွန်း" },
  "找": { meaningMy: "ရှာသည်၊ ပြန်အမ်းသည်" },
  "着": { meaningMy: "လုပ်ရပ် သို့မဟုတ် အခြေအနေ ဆက်လက်တည်ရှိနေမှုကို ဖော်ပြသော ပုဒ်" },
  "真": { meaningMy: "တကယ်၊ အမှန်တကယ်၊ စစ်မှန်သော" },
  "正在": { meaningMy: "ယခု လုပ်ဆောင်နေဆဲဖြစ်သည်" },
  "知道": { meaningMy: "သိသည်၊ သိရှိသည်" },
  "准备": { meaningMy: "ပြင်ဆင်သည်၊ အဆင်သင့်ပြုလုပ်သည်" },
  "自行车": { meaningMy: "စက်ဘီး" },
  "走": { meaningMy: "လမ်းလျှောက်သည်၊ ထွက်ခွာသည်" },
  "最": { meaningMy: "အများဆုံး၊ အ…ဆုံး" },
  "左边": { meaningMy: "ဘယ်ဘက်" },
};
