"use client";

import { useCallback, useEffect, useState } from "react";
import { Award, Ban, CheckCircle2, XCircle } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Request = { id:number;product_id:number;user_id:string;status:string;learner_note:string|null;eligibility_snapshot:Record<string,number>;created_at:string;knowledge_products:{title_zh:string|null;title_my:string|null;title_en:string|null}|null };
type Certificate = { id:number;certificate_no:string;recipient_name:string;course_title:string;issued_at:string };

export default function CertificateReviewManager({locale}:{locale:string}){
  const copy=locale==="zh"?{heading:"证书审核",intro:"只有课程达标并由教师或管理员审核通过后才颁发正式证书。",pending:"待审核申请",active:"已颁发证书",empty:"暂无待审核申请",approve:"审核通过并颁发",reject:"驳回申请",note:"审核意见；驳回时必填",revoke:"撤销证书",reason:"请输入撤销原因",student:"学生",evidence:"达标记录",done:"操作已完成"}:locale==="my"?{heading:"လက်မှတ် စစ်ဆေးခြင်း",intro:"သင်တန်းစံနှုန်းပြည့်မီပြီး ဆရာ သို့မဟုတ် စီမံခန့်ခွဲသူ အတည်ပြုပြီးမှ လက်မှတ်ထုတ်ပေးမည်။",pending:"စစ်ဆေးရန်",active:"ထုတ်ပေးပြီးသော လက်မှတ်များ",empty:"စစ်ဆေးရန် မရှိပါ",approve:"အတည်ပြုပြီး လက်မှတ်ထုတ်ရန်",reject:"ပယ်ချရန်",note:"စစ်ဆေးမှတ်ချက် (ပယ်ချပါက မဖြစ်မနေ)",revoke:"လက်မှတ်ရုပ်သိမ်းရန်",reason:"ရုပ်သိမ်းရသည့်အကြောင်းရင်း",student:"ကျောင်းသား",evidence:"ပြီးမြောက်မှုမှတ်တမ်း",done:"ဆောင်ရွက်ပြီးပါပြီ"}:{heading:"Certificate review",intro:"A formal certificate is issued only after course completion and instructor or administrator approval.",pending:"Pending requests",active:"Issued certificates",empty:"No requests awaiting review",approve:"Approve and issue",reject:"Reject request",note:"Review note; required when rejecting",revoke:"Revoke certificate",reason:"Enter a revocation reason",student:"Learner",evidence:"Eligibility evidence",done:"Action completed"};
  const[requests,setRequests]=useState<Request[]>([]),[certificates,setCertificates]=useState<Certificate[]>([]),[notes,setNotes]=useState<Record<number,string>>({}),[message,setMessage]=useState("");
  const load=useCallback(async()=>{const[{data:r,error:re},{data:c,error:ce}]=await Promise.all([supabase.from("knowledge_certificate_requests").select("id,product_id,user_id,status,learner_note,eligibility_snapshot,created_at,knowledge_products(title_zh,title_my,title_en)").eq("status","pending").order("created_at",{ascending:true}),supabase.from("knowledge_certificates").select("id,certificate_no,recipient_name,course_title,issued_at").eq("status","active").order("issued_at",{ascending:false}).limit(50)]);if(re||ce)setMessage((re||ce)?.message||"");else{setRequests((r||[]) as unknown as Request[]);setCertificates((c||[]) as Certificate[])}},[]);
  useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load()},[load]);
  async function review(id:number,decision:"approved"|"rejected"){const note=notes[id]?.trim()||null;if(decision==="rejected"&&!note){setMessage(copy.note);return}const{error}=await supabase.rpc("review_knowledge_certificate_request",{p_request_id:id,p_decision:decision,p_review_note:note});if(error)setMessage(error.message);else{setMessage(copy.done);await load()}}
  async function revoke(id:number){const reason=window.prompt(copy.reason)?.trim();if(!reason)return;const{error}=await supabase.rpc("revoke_knowledge_certificate",{p_certificate_id:id,p_reason:reason});if(error)setMessage(error.message);else{setMessage(copy.done);await load()}}
  return <section className="certificate-review-admin"><header><Award size={22}/><div><h2>{copy.heading}</h2><p>{copy.intro}</p></div></header><h3>{copy.pending}<span>{requests.length}</span></h3>{!requests.length?<p className="certificate-review-empty">{copy.empty}</p>:<div className="certificate-review-list">{requests.map(item=>{const title=item.knowledge_products?.title_zh||item.knowledge_products?.title_my||item.knowledge_products?.title_en||`#${item.product_id}`;return <article key={item.id}><div><strong>{title}</strong><p>{copy.student}: <code>{item.user_id}</code></p><small>{new Date(item.created_at).toLocaleString(locale)}</small><details><summary>{copy.evidence}</summary><pre>{JSON.stringify(item.eligibility_snapshot,null,2)}</pre></details></div><div><textarea value={notes[item.id]||""} onChange={e=>setNotes(current=>({...current,[item.id]:e.target.value}))} placeholder={copy.note}/><button onClick={()=>review(item.id,"approved")}><CheckCircle2 size={15}/>{copy.approve}</button><button className="reject" onClick={()=>review(item.id,"rejected")}><XCircle size={15}/>{copy.reject}</button></div></article>})}</div>}<h3>{copy.active}<span>{certificates.length}</span></h3><div className="certificate-issued-list">{certificates.map(item=><article key={item.id}><div><strong>{item.recipient_name}</strong><p>{item.course_title} · {item.certificate_no}</p></div><button onClick={()=>revoke(item.id)}><Ban size={15}/>{copy.revoke}</button></article>)}</div>{message?<p className="verification-message">{message}</p>:null}</section>;
}
