"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { BadgeCheck, ExternalLink, Trash2 } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Product={id:number;title:string};
type License={id:number;product_id:number|null;resource_type:string;title:string;source_url:string;author_name:string|null;license_code:string;license_url:string|null;verified_at:string|null};
export default function ResourceLicenseManager({locale,products}:{locale:string;products:Product[]}){
  const c=locale==="zh"?{title:"课程资源与许可证",intro:"视频、音频、教材或题库必须先登记来源和商业使用许可证，验证后才能作为正式课程资源使用。",product:"选择课程",name:"资源名称",source:"资源来源 HTTPS 链接",author:"作者/机构",code:"许可证（如 CC BY 4.0）",url:"许可证链接",add:"登记资源",verify:"标记已核验",remove:"删除"}:locale==="my"?{title:"သင်တန်းရင်းမြစ်နှင့် License",intro:"ဗီဒီယို၊ အသံ၊ သင်ခန်းစာနှင့် မေးခွန်းဘဏ်တို့၏ မူရင်းနှင့် စီးပွားဖြစ်အသုံးပြုခွင့်ကို အရင်မှတ်တမ်းတင်ရမည်။",product:"သင်တန်းရွေးရန်",name:"ရင်းမြစ်အမည်",source:"မူရင်း HTTPS လင့်ခ်",author:"ရေးသားသူ/အဖွဲ့",code:"License (ဥပမာ CC BY 4.0)",url:"License လင့်ခ်",add:"မှတ်တမ်းတင်ရန်",verify:"စစ်ဆေးပြီး",remove:"ဖျက်ရန်"}:{title:"Course resources and licenses",intro:"Register the source and commercial-use license for every video, audio file, textbook or question bank before publication.",product:"Choose course",name:"Resource title",source:"HTTPS source URL",author:"Author/organisation",code:"License (for example CC BY 4.0)",url:"License URL",add:"Register resource",verify:"Mark verified",remove:"Delete"};
  const [items,setItems]=useState<License[]>([]);const [product,setProduct]=useState("");const [type,setType]=useState("video");const [title,setTitle]=useState("");const [source,setSource]=useState("");const [author,setAuthor]=useState("");const [code,setCode]=useState("");const [url,setUrl]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const {data,error}=await supabase.from("knowledge_resource_licenses").select("id,product_id,resource_type,title,source_url,author_name,license_code,license_url,verified_at").order("created_at",{ascending:false});if(error)setMessage(error.message);else setItems((data||[]) as License[])},[]);useEffect(()=>{
    // Supabase resolves asynchronously before updating local state.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);
  async function submit(e:FormEvent){e.preventDefault();const {error}=await supabase.from("knowledge_resource_licenses").insert({product_id:Number(product),resource_type:type,title:title.trim(),source_url:source.trim(),author_name:author.trim()||null,license_code:code.trim(),license_url:url.trim()||null});if(error)setMessage(error.message);else{setTitle("");setSource("");setAuthor("");setCode("");setUrl("");setMessage("");await load()}}
  async function verify(id:number){const {error}=await supabase.from("knowledge_resource_licenses").update({verified_at:new Date().toISOString()}).eq("id",id);if(error)setMessage(error.message);else await load()}
  async function remove(id:number){const {error}=await supabase.from("knowledge_resource_licenses").delete().eq("id",id);if(error)setMessage(error.message);else await load()}
  return <section className="resource-license-admin"><h2><BadgeCheck size={20}/>{c.title}</h2><p>{c.intro}</p><form onSubmit={submit}><select required value={product} onChange={e=>setProduct(e.target.value)}><option value="">{c.product}</option>{products.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{["video","audio","image","text","subtitle","attachment","dataset","other"].map(v=><option key={v}>{v}</option>)}</select><input required maxLength={300} value={title} onChange={e=>setTitle(e.target.value)} placeholder={c.name}/><input required type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder={c.source}/><input value={author} onChange={e=>setAuthor(e.target.value)} placeholder={c.author}/><input required value={code} onChange={e=>setCode(e.target.value)} placeholder={c.code}/><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder={c.url}/><button>{c.add}</button></form>{message?<p className="verification-message">{message}</p>:null}<div>{items.map(item=><article key={item.id}><div><strong>{item.title}</strong><small>{item.resource_type} · {item.license_code} · {item.author_name||"—"}</small><a href={item.source_url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>{item.source_url}</a></div><div>{item.verified_at?<span><BadgeCheck size={15}/>Verified</span>:<button type="button" onClick={()=>void verify(item.id)}>{c.verify}</button>}<button type="button" className="danger" aria-label={c.remove} onClick={()=>void remove(item.id)}><Trash2 size={15}/></button></div></article>)}</div></section>;
}
