import LegalPage, { LegalSection } from "@/components/LegalPage";

const content: Record<string, { title: string; summary: string; updated: string; sections: LegalSection[] }> = {
  zh: { title: "服务条款", summary: "使用 BurmeseBridge 即表示你同意遵守本条款及适用法律。", updated: "2026年8月14日", sections: [
    { title: "1. 服务范围", paragraphs: ["BurmeseBridge 提供学习、新闻、工作信息、社区讨论、视频和知识内容等网络服务。功能可能随着产品发展调整。"] },
    { title: "2. 账号责任", paragraphs: ["你应提供准确资料、保护账号凭据并对账号活动负责。不得冒充他人、转售账号或绕过平台安全措施。"] },
    { title: "3. 社区规则", paragraphs: ["禁止发布违法、欺诈、骚扰、仇恨、恶意软件、垃圾广告、侵犯隐私或知识产权的内容。平台可以审核、限制或删除违规内容，并在严重情况下暂停账号。"] },
    { title: "4. 用户内容", paragraphs: ["你保留原创内容的权利，同时授予平台为展示、分发、审核和运营服务所必需的非独占许可。你必须确保拥有发布内容所需的权利。"] },
    { title: "5. 付费内容", paragraphs: ["商品价格、访问期限和付款方式以购买页面为准。人工审核的付款应在确认后开通。退款申请将根据内容访问状态、付款渠道能力和适用法律逐案处理。"] },
    { title: "6. 招聘信息与平台角色", paragraphs: ["BurmeseBridge 是信息发布与交流平台，不是招聘公司、劳务派遣机构、职业介绍所，也不是任何职位的雇主或代理人。职位由第三方发布者提供，发布者须对公司身份、招聘资质、工资、地点、签证、合同、住宿和工作条件的真实性、合法性及完整性负责。", "平台可能审核或标记信息，但不构成对雇主、职位、录用、工资、签证或人身安全的保证。求职者应独立核验雇主登记、招聘许可和书面合同；涉及跨境就业时，应咨询相关政府部门或合法持牌机构。"] },
    { title: "7. 禁止人口贩卖与剥削", paragraphs: ["平台对人口贩卖、贩卖人口、强迫劳动、债务束缚、非法拘禁、扣押护照或身份证、威胁暴力、限制离职或行动自由、虚假招聘、童工、性剥削及其他非法招聘行为实行零容忍。"], items: ["不得以招聘、培训、交通、签证或押金名义欺骗或强迫求职者付款。", "不得隐瞒或擅自改变工作性质、工资、地点、工时、住宿或自由离职条件。", "不得索取账号密码、验证码、非必要敏感资料或控制求职者证件。", "发现疑似违法信息时，平台可不经事先通知下架内容、限制账号、保存必要证据，并依法配合或报告有关机构。"] },
    { title: "8. 求职者安全与举报", paragraphs: ["不要仅凭平台帖子转账、旅行或交付证件。应在安全地点面试，将行程和雇主信息告知可信联系人，并保留职位、聊天、合同和付款记录。若面临即时危险，请优先离开现场并联系当地紧急服务、警方或反人口贩卖机构，同时通过平台举报功能报告。"] },
    { title: "9. 责任边界", paragraphs: ["平台会采取合理的内容审核和安全措施，但无法预先核实每项第三方招聘信息，也不是雇佣合同当事方。在适用法律允许范围内，因用户或第三方的虚假陈述、线下交易、雇佣决定或违法行为产生的责任由相应行为人承担。本条款不排除平台依法不得排除的责任，也不限制受害者依法举报和求偿的权利。"] },
    { title: "10. 第三方链接", paragraphs: ["平台可能包含第三方网站、职位、视频或社交平台链接。第三方内容和服务由其提供者负责，访问前请自行核实。"] },
    { title: "11. 条款变更与联系", paragraphs: ["重要变更会通过网站公布。继续使用服务代表接受更新后的条款。如有问题，请联系 admin@burmesebridge.com。"] },
  ] },
  my: { title: "ဝန်ဆောင်မှု စည်းမျဉ်းများ", summary: "BurmeseBridge ကို အသုံးပြုခြင်းဖြင့် ဤစည်းမျဉ်းများနှင့် သက်ဆိုင်ရာဥပဒေများကို လိုက်နာရန် သဘောတူပါသည်။", updated: "၂၀၂၆ ဩဂုတ် ၁၄", sections: [
    { title: "၁။ ဝန်ဆောင်မှု", paragraphs: ["BurmeseBridge တွင် သင်ယူမှု၊ သတင်း၊ အလုပ်အကိုင်၊ community၊ ဗီဒီယိုနှင့် paid knowledge content များ ပါဝင်သည်။ လုပ်ဆောင်ချက်များကို အချိန်နှင့်အမျှ ပြောင်းလဲနိုင်သည်။"] },
    { title: "၂။ အကောင့်တာဝန်", paragraphs: ["မှန်ကန်သောအချက်အလက်ပေးရန်၊ login အချက်အလက်ကို ကာကွယ်ရန်နှင့် မိမိအကောင့်လှုပ်ရှားမှုအတွက် တာဝန်ယူရန် လိုအပ်သည်။"] },
    { title: "၃။ Community စည်းမျဉ်း", paragraphs: ["တရားမဝင်၊ လိမ်လည်၊ နှောင့်ယှက်၊ အမုန်းစကား၊ spam၊ malware၊ ကိုယ်ရေးလုံခြုံမှု သို့မဟုတ် မူပိုင်ခွင့်ချိုးဖောက်သော အကြောင်းအရာ မတင်ရ။ ချိုးဖောက်သည့်အကြောင်းအရာ သို့မဟုတ် အကောင့်ကို ကန့်သတ်/ဖယ်ရှားနိုင်သည်။"] },
    { title: "၄။ အသုံးပြုသူအကြောင်းအရာ", paragraphs: ["မူရင်းအကြောင်းအရာ၏ အခွင့်အရေးကို သင်ပိုင်ဆိုင်ပြီး ဝန်ဆောင်မှုအတွင်း ပြသ၊ ဖြန့်ဝေ၊ စိစစ်ရန်လိုအပ်သော အကန့်အသတ်မရှိမဟုတ်သည့် ခွင့်ပြုချက်ကို ပလက်ဖောင်းအား ပေးပါသည်။"] },
    { title: "၅။ ငွေပေးချေသည့်အကြောင်းအရာ", paragraphs: ["စျေးနှုန်း၊ ဝင်ရောက်ခွင့်ကာလနှင့် ငွေပေးချေမှုကို purchase page အတိုင်း သတ်မှတ်သည်။ Refund ကို content access၊ payment channel နှင့် သက်ဆိုင်ရာဥပဒေအတိုင်း စိစစ်မည်။"] },
    { title: "၆။ အလုပ်ခန့်အပ်မှုနှင့် Platform ၏ အခန်းကဏ္ဍ", paragraphs: ["BurmeseBridge သည် သတင်းအချက်အလက်မျှဝေရာ platform ဖြစ်ပြီး အလုပ်ခန့်အပ်ရေးအေဂျင်စီ၊ အလုပ်ရှင် သို့မဟုတ် ကိုယ်စားလှယ် မဟုတ်ပါ။ အလုပ်ကြော်ငြာတင်သူသည် ကုမ္ပဏီ၊ လစာ၊ နေရာ၊ visa၊ စာချုပ်နှင့် အလုပ်အခြေအနေတို့၏ မှန်ကန်မှုနှင့် တရားဝင်မှုအတွက် တာဝန်ရှိသည်။", "Platform စိစစ်မှုသည် အလုပ်၊ အလုပ်ရှင်၊ လစာ၊ visa သို့မဟုတ် လုံခြုံရေးကို အာမခံခြင်းမဟုတ်ပါ။ လျှောက်ထားသူသည် အလုပ်ရှင်လိုင်စင်နှင့် နားလည်နိုင်သောဘာသာဖြင့် ရေးထားသည့် စာချုပ်ကို ကိုယ်တိုင်စစ်ဆေးရမည်။"] },
    { title: "၇။ လူကုန်ကူးမှုနှင့် အမြတ်ထုတ်မှု လုံးဝတားမြစ်ခြင်း", paragraphs: ["လူကုန်ကူးခြင်း၊ အဓမ္မအလုပ်ခိုင်းခြင်း၊ အကြွေးဖြင့်ချုပ်နှောင်ခြင်း၊ တရားမဝင်ထိန်းသိမ်းခြင်း၊ passport/ID သိမ်းခြင်း၊ ခြိမ်းခြောက်ခြင်း၊ ထွက်ခွာခွင့်ပိတ်ပင်ခြင်း၊ အလုပ်လိမ်လည်ခြင်း၊ ကလေးလုပ်သားနှင့် လိင်ပိုင်းဆိုင်ရာအမြတ်ထုတ်မှုကို လုံးဝခွင့်မပြုပါ။"], items:["အလုပ်၊ training၊ သွားလာရေး၊ visa သို့မဟုတ် deposit အမည်ဖြင့် လိမ်လည်ငွေတောင်းခြင်း မပြုရ။", "အလုပ်အမျိုးအစား၊ လစာ၊ နေရာ၊ အလုပ်ချိန်နှင့် ထွက်ခွာခွင့်ကို ဖုံးကွယ်/ပြောင်းလဲခြင်း မပြုရ။", "Password၊ OTP သို့မဟုတ် မလိုအပ်သောအရေးကြီးအချက်အလက် မတောင်းရ။", "သံသယရှိသည့်အကြောင်းအရာကို ဖယ်ရှား၊ အကောင့်ပိတ်၊ သက်သေထိန်းသိမ်းပြီး သက်ဆိုင်ရာအာဏာပိုင်ထံ တင်ပြနိုင်သည်။"] },
    { title: "၈။ အလုပ်ရှာဖွေသူ လုံခြုံရေး", paragraphs: ["Post တစ်ခုတည်းကို ယုံ၍ ငွေလွှဲခြင်း၊ ခရီးသွားခြင်း သို့မဟုတ် စာရွက်စာတမ်းပေးခြင်း မပြုပါနှင့်။ Interview ကို လုံခြုံသောနေရာတွင်လုပ်ပြီး အလုပ်ရှင်နှင့် ခရီးစဉ်အချက်အလက်ကို ယုံကြည်ရသူအား မျှဝေပါ။ အရေးပေါ်အန္တရာယ်ရှိပါက ဒေသဆိုင်ရာ ရဲတပ်ဖွဲ့/အရေးပေါ်ဝန်ဆောင်မှုကို ဆက်သွယ်ပြီး platform တွင် report လုပ်ပါ။"] },
    { title: "၉။ တာဝန်ကန့်သတ်ချက်", paragraphs: ["Platform သည် သင့်လျော်သောစိစစ်မှု ပြုလုပ်သော်လည်း third-party အလုပ်တိုင်းကို ကြိုတင်အတည်ပြုနိုင်မည်မဟုတ်ဘဲ အလုပ်စာချုပ်၏ အဖွဲ့ဝင်မဟုတ်ပါ။ အသုံးပြုသူ သို့မဟုတ် third party ၏ လိမ်လည်ဖော်ပြမှု၊ offline transaction၊ အလုပ်ခန့်ဆုံးဖြတ်ချက်နှင့် တရားမဝင်လုပ်ရပ်အတွက် သက်ဆိုင်ရာလုပ်ဆောင်သူက တာဝန်ယူရမည်။ ဤစည်းမျဉ်းသည် ဥပဒေအရ မဖယ်ရှားနိုင်သောတာဝန် သို့မဟုတ် နစ်နာသူ၏ တိုင်ကြား/လျော်ကြေးတောင်းခွင့်ကို မကန့်သတ်ပါ။"] },
    { title: "၁၀။ ပြင်ပလင့်ခ်", paragraphs: ["ပြင်ပဝဘ်ဆိုက်၊ အလုပ်၊ ဗီဒီယို သို့မဟုတ် social link များ ပါနိုင်သည်။ အသုံးမပြုမီ ကိုယ်တိုင်စစ်ဆေးပါ။"] },
    { title: "၁၁။ ပြောင်းလဲမှုနှင့် ဆက်သွယ်ရန်", paragraphs: ["အရေးကြီးသော ပြောင်းလဲမှုများကို ဝဘ်ဆိုက်တွင် အသိပေးကြေညာပါမည်။ မေးမြန်းလိုသည်များကို admin@burmesebridge.com သို့ ပေးပို့နိုင်ပါသည်။"] },
  ] },
  en: { title: "Terms of Service", summary: "By using BurmeseBridge, you agree to these terms and applicable laws.", updated: "August 14, 2026", sections: [
    { title: "1. The service", paragraphs: ["BurmeseBridge provides learning, news, job information, community discussions, videos, and knowledge content. Features may change as the product develops."] },
    { title: "2. Account responsibility", paragraphs: ["You must provide accurate information, protect your credentials, and take responsibility for account activity. You may not impersonate others, resell accounts, or bypass security controls."] },
    { title: "3. Community rules", paragraphs: ["Do not publish illegal, fraudulent, harassing, hateful, malicious, spam, privacy-infringing, or intellectual-property-infringing content. We may moderate or remove violations and suspend accounts in serious cases."] },
    { title: "4. User content", paragraphs: ["You retain rights in original content and grant the platform a non-exclusive license necessary to display, distribute, moderate, and operate it within the service. You must have the rights required to publish it."] },
    { title: "5. Paid content", paragraphs: ["Prices, access periods, and payment methods are shown at purchase. Manually reviewed payments are activated after confirmation. Refund requests are assessed according to content access, payment-channel capabilities, and applicable law."] },
    { title: "6. Job listings and our role", paragraphs: ["BurmeseBridge is an information and communication platform, not a recruiter, employment agency, labour broker, employer, or agent for any listing. Third-party publishers are responsible for the truthfulness, legality, and completeness of their identity, licence, wages, location, visa, contract, accommodation, and working conditions.", "Moderation does not guarantee an employer, job, hiring outcome, wage, visa, or personal safety. Jobseekers must independently verify registrations, recruitment licences, and written contracts, and should consult competent authorities or licensed agencies for cross-border work."] },
    { title: "7. Zero tolerance for trafficking and exploitation", paragraphs: ["Human trafficking, forced labour, debt bondage, unlawful confinement, withholding passports or identity documents, threats, restrictions on leaving or movement, fraudulent recruitment, child labour, sexual exploitation, and related illegal recruitment are prohibited."], items:["Do not deceive or coerce jobseekers into paying recruitment, training, travel, visa, or deposit charges.", "Do not conceal or materially change the work, wages, location, hours, accommodation, or freedom to leave.", "Do not request passwords, verification codes, unnecessary sensitive data, or control identity documents.", "We may remove content, restrict accounts, preserve necessary evidence, and cooperate with or report to competent authorities without prior notice."] },
    { title: "8. Jobseeker safety and reporting", paragraphs: ["Do not transfer money, travel, or hand over documents based only on a platform post. Verify independently, interview in a safe place, tell a trusted contact about the employer and journey, and preserve listings, messages, contracts, and payment records. If in immediate danger, leave when safe and contact local emergency services, police, or anti-trafficking authorities, then report the listing to the platform."] },
    { title: "9. Allocation of responsibility", paragraphs: ["We take reasonable moderation and security measures but cannot pre-verify every third-party listing and are not a party to employment contracts. To the extent permitted by law, the relevant actor remains responsible for false statements, offline transactions, employment decisions, and unlawful conduct. Nothing here excludes liability that cannot legally be excluded or limits a victim's right to report or seek a remedy."] },
    { title: "10. Third-party links", paragraphs: ["The service may link to third-party websites, jobs, videos, or social platforms. Those providers are responsible for their services; verify them before relying on them."] },
    { title: "11. Changes and contact", paragraphs: ["Material changes will be posted on the website. Continued use means acceptance of updated terms. Contact admin@burmesebridge.com with questions."] },
  ] },
};

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; return <LegalPage locale={locale} {...(content[locale] || content.en)} />; }
