"use client";
import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { BadgeCheck, Bug, Flag, GraduationCap, LayoutDashboard, Users, FileText, Gavel } from "lucide-react";
import { supabase } from "@/lib/supabase";
import AdminSidebar from "@/components/admin/AdminSidebar";
import AdminStatCard from "@/components/admin/AdminStatCard";
import AdminGuard from "@/components/admin/AdminGuard";
import { DirectoryState } from "@/components/ui/content-directory";
type Counts={users:number;posts:number;verification:number;reports:number;feedback:number;orders:number;memberships:number;appeals:number;certificates:number;assignments:number};
const empty:Counts={users:0,posts:0,verification:0,reports:0,feedback:0,orders:0,memberships:0,appeals:0,certificates:0,assignments:0};
export default function AdminPage(){return <AdminGuard><AdminDashboard/></AdminGuard>}
function AdminDashboard(){
  const locale=String(useParams().locale||"my");
  const copy=locale==="zh"?{title:"后台管理",subtitle:"集中处理平台审核、用户与内容待办。",eyebrow:"管理工作台",loading:"正在加载后台数据",error:"后台统计加载失败",todo:"待处理事项",overview:"平台概览",users:"用户",posts:"帖子",verification:"身份审核",reports:"举报审核",feedback:"反馈与 BUG",orders:"课程订单",memberships:"会员订单",appeals:"用户申诉",certificates:"证书审核",assignments:"作业批改"}:locale==="my"?{title:"စီမံခန့်ခွဲရေး",subtitle:"စိစစ်မှု၊ အသုံးပြုသူနှင့် Content လုပ်ငန်းများကို တစ်နေရာတည်းတွင် စီမံပါ။",eyebrow:"စီမံခန့်ခွဲရေး Workbench",loading:"ဒေတာများ ရယူနေသည်",error:"စီမံခန့်ခွဲရေးစာရင်း ရယူ၍ မရပါ",todo:"စောင့်ဆိုင်းနေသော လုပ်ငန်းများ",overview:"Platform အကျဉ်းချုပ်",users:"အသုံးပြုသူများ",posts:"ပို့စ်များ",verification:"အထောက်အထား စိစစ်မှု",reports:"တိုင်ကြားချက်",feedback:"အကြံပြုချက် / BUG",orders:"သင်တန်းအော်ဒါ",memberships:"အဖွဲ့ဝင်အော်ဒါ",appeals:"အယူခံ",certificates:"လက်မှတ်စစ်ဆေးရန်",assignments:"အိမ်စာစစ်ဆေးရန်"}:{title:"Admin dashboard",subtitle:"Review platform queues, users, and content from one workspace.",eyebrow:"Administration workspace",loading:"Loading administration data",error:"Dashboard statistics could not be loaded",todo:"Pending work",overview:"Platform overview",users:"Users",posts:"Posts",verification:"Identity reviews",reports:"Reports",feedback:"Feedback & bugs",orders:"Course orders",memberships:"Membership orders",appeals:"Appeals",certificates:"Certificate reviews",assignments:"Assignment grading"};
  const [counts,setCounts]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{const results=await Promise.all([supabase.from("profiles").select("*",{count:"exact",head:true}),supabase.from("posts").select("*",{count:"exact",head:true}),supabase.from("verification_requests").select("*",{count:"exact",head:true}).eq("status","pending"),supabase.from("content_reports").select("*",{count:"exact",head:true}).in("status",["pending","reviewing"]),supabase.from("feedback_reports").select("*",{count:"exact",head:true}).in("status",["open","reviewing"]),supabase.from("knowledge_purchase_requests").select("*",{count:"exact",head:true}).eq("status","pending"),supabase.from("knowledge_membership_requests").select("*",{count:"exact",head:true}).eq("status","pending"),supabase.from("moderation_appeals").select("*",{count:"exact",head:true}).eq("status","pending"),supabase.from("knowledge_certificate_requests").select("*",{count:"exact",head:true}).eq("status","pending"),supabase.from("knowledge_assignment_submissions").select("*",{count:"exact",head:true}).eq("status","submitted")]);const failed=results.find(item=>item.error);if(failed?.error){setError(failed.error.message);setLoading(false);return;}setCounts({users:results[0].count||0,posts:results[1].count||0,verification:results[2].count||0,reports:results[3].count||0,feedback:results[4].count||0,orders:results[5].count||0,memberships:results[6].count||0,appeals:results[7].count||0,certificates:results[8].count||0,assignments:results[9].count||0});setLoading(false);},[]);
  useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load();},[load]);
  if(loading)return <div className="adminShell"><AdminSidebar/><main className="adminContent"><DirectoryState kind="loading" title={copy.loading}/></main></div>;
  return <div className="adminShell"><AdminSidebar/><main className="adminContent admin-dashboard"><header className="admin-page-head"><div><span className="admin-eyebrow"><LayoutDashboard size={17}/>{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.subtitle}</p></div></header>{error?<DirectoryState kind="error" title={copy.error} description={error}/>:<><section><h2>{copy.todo}</h2><div className="adminGrid admin-todo-grid"><AdminStatCard title={copy.verification} value={counts.verification} href={`/${locale}/admin/verification`} icon={BadgeCheck}/><AdminStatCard title={copy.reports} value={counts.reports} href={`/${locale}/admin/reports`} icon={Flag}/><AdminStatCard title={copy.feedback} value={counts.feedback} href={`/${locale}/admin/feedback`} icon={Bug}/><AdminStatCard title={copy.orders} value={counts.orders} href={`/${locale}/admin/knowledge`} icon={GraduationCap}/><AdminStatCard title={copy.memberships} value={counts.memberships} href={`/${locale}/admin/knowledge`} icon={GraduationCap}/><AdminStatCard title={copy.certificates} value={counts.certificates} href={`/${locale}/admin/knowledge`} icon={BadgeCheck}/><AdminStatCard title={copy.assignments} value={counts.assignments} href={`/${locale}/teacher`} icon={GraduationCap}/><AdminStatCard title={copy.appeals} value={counts.appeals} href={`/${locale}/admin/appeals`} icon={Gavel}/></div></section><section><h2>{copy.overview}</h2><div className="adminGrid admin-overview-grid"><AdminStatCard title={copy.users} value={counts.users} href={`/${locale}/admin/users`} icon={Users}/><AdminStatCard title={copy.posts} value={counts.posts} href={`/${locale}/admin/posts`} icon={FileText}/></div></section></>}</main></div>;
}
