import LegalPage, { LegalSection } from "@/components/LegalPage";

const content: Record<string, { title: string; summary: string; updated: string; sections: LegalSection[] }> = {
  zh: { title:"求职安全中心", summary:"识别招聘诈骗、强迫劳动和人口贩卖风险，并了解遇到危险时应采取的行动。", updated:"2026年8月14日", sections:[
    { title:"1. 投递前先核验", paragraphs:["不要仅凭聊天账号、群组帖子或公司标志判断职位真实。核对公司登记名称、办公地址、招聘人员身份、招聘许可、工资支付主体和书面合同。跨境工作应向出发地及工作地的主管部门或合法持牌机构核实。"], items:["使用公司公开渠道反向确认招聘人员。", "要求提供你能理解语言的书面合同并保存副本。", "核对工作地点、岗位、工资、工时、休息、住宿、保险、签证和离职条件。"] },
    { title:"2. 高风险警示信号", paragraphs:["出现一个信号不一定能单独证明犯罪，但多个信号同时出现时，应立即停止流程并寻求帮助。"], items:["承诺异常高薪、无需面试、催促立即出境或秘密见面。", "要求支付不明招聘费、押金、保证金、培训费、交通费或使用私人账户收款。", "索取密码、验证码、银行卡控制权，或要求交出护照、身份证和手机。", "到达后工作、工资、地点或住宿与承诺明显不同。", "限制离开、与家人联系或自由活动，以债务、举报移民身份、暴力或扣薪相威胁。"] },
    { title:"3. 面试与出行安全", paragraphs:["优先选择可核验的办公地点或视频面试。把雇主名称、联系人、地址、行程、车辆和住宿信息交给可信联系人，约定定时报平安。不要独自前往偏僻地点，不要把证件原件长期交给招聘人员或雇主。"] },
    { title:"4. 遇到危险怎么办", paragraphs:["如果面临即时危险，优先在安全可行时离开现场，联系当地紧急服务、警方、劳动主管部门、反人口贩卖机构或可信公益组织。不要为了收集更多证据而增加自身风险。"], items:["在安全前提下保存职位页面、账号、电话号码、聊天、合同、转账和地点记录。", "告知可信联系人你的位置和情况。", "在 BurmeseBridge 使用举报/反馈入口提交相关链接和证据；平台举报不能替代报警。"] },
    { title:"5. 平台处理", paragraphs:["收到有效举报后，BurmeseBridge 可以隐藏或删除招聘信息、限制账号、保全必要记录并依法配合主管机关。为保护受害者和调查，我们不会公开举报人的敏感信息，但法律要求或紧急安全需要除外。"] },
    { title:"6. 联系平台", paragraphs:["非紧急举报可通过网站反馈入口提交，或发送邮件至 admin@burmesebridge.com。请勿通过邮件发送密码、验证码或不必要的完整证件照片。"] },
  ]},
  my: { title:"အလုပ်ရှာဖွေသူ လုံခြုံရေးစင်တာ", summary:"အလုပ်လိမ်လည်မှု၊ အဓမ္မအလုပ်နှင့် လူကုန်ကူးမှုအန္တရာယ်ကို သိရှိပြီး အရေးပေါ်အခြေအနေတွင် လုပ်ဆောင်ရမည့်အချက်များ။", updated:"၂၀၂၆ ဩဂုတ် ၁၄", sections:[
    { title:"၁။ မလျှောက်မီ စစ်ဆေးရန်", paragraphs:["Chat account၊ group post သို့မဟုတ် logo တစ်ခုတည်းကို ယုံကြည်မထားပါနှင့်။ ကုမ္ပဏီမှတ်ပုံတင်အမည်၊ လိပ်စာ၊ recruiter identity၊ လိုင်စင်၊ လစာပေးသူနှင့် စာချုပ်ကို စစ်ဆေးပါ။"], items:["ကုမ္ပဏီ၏ public channel မှ recruiter ကို ပြန်လည်အတည်ပြုပါ။", "နားလည်နိုင်သောဘာသာဖြင့် ရေးထားသည့်စာချုပ်နှင့် မိတ္တူတောင်းပါ။", "အလုပ်၊ လစာ၊ အချိန်၊ နေရာ၊ နေထိုင်ခွင့်၊ visa နှင့် ထွက်ခွာခွင့်ကို စစ်ဆေးပါ။"] },
    { title:"၂။ အန္တရာယ်သတိပေးလက္ခဏာ", paragraphs:["လက္ခဏာတစ်ခုတည်းက ရာဇဝတ်မှုကို အတည်မပြုနိုင်သော်လည်း အများအပြားရှိပါက လုပ်ငန်းစဉ်ကို ရပ်ပြီး အကူအညီတောင်းပါ။"], items:["အလွန်မြင့်သောလစာ၊ interview မလိုခြင်း၊ ချက်ချင်းနယ်စပ်ဖြတ်ရန် သို့မဟုတ် လျှို့ဝှက်တွေ့ရန် ဖိအားပေးခြင်း။", "မရှင်းလင်းသော fee၊ deposit၊ training/travel fee သို့မဟုတ် personal account သို့ ငွေလွှဲခိုင်းခြင်း။", "Password၊ OTP၊ bank control၊ passport၊ ID သို့မဟုတ် ဖုန်းတောင်းခြင်း။", "ရောက်ပြီးနောက် အလုပ်၊ လစာ၊ နေရာ သို့မဟုတ် နေထိုင်မှုက ကြော်ငြာနှင့် မတူခြင်း။", "ထွက်ခွာမှု/ဆက်သွယ်မှုကန့်သတ်ခြင်း၊ အကြွေး၊ လူဝင်မှုအခြေအနေ၊ အကြမ်းဖက်မှု သို့မဟုတ် လစာဖြတ်မှုဖြင့် ခြိမ်းခြောက်ခြင်း။"] },
    { title:"၃။ Interview နှင့် ခရီးလုံခြုံရေး", paragraphs:["စစ်ဆေးနိုင်သောရုံး သို့မဟုတ် video interview ကို ရွေးပါ။ အလုပ်ရှင်၊ လိပ်စာ၊ ခရီးနှင့် နေရာအချက်အလက်ကို ယုံကြည်ရသူအား ပေးထားပြီး ပုံမှန်ဆက်သွယ်ပါ။ Passport/ID မူရင်းကို recruiter ထံ မထားပါနှင့်။"] },
    { title:"၄။ အန္တရာယ်ရှိလျှင်", paragraphs:["ချက်ချင်းအန္တရာယ်ရှိပါက လုံခြုံသည့်အခါ နေရာမှထွက်ပြီး ဒေသဆိုင်ရာအရေးပေါ်ဝန်ဆောင်မှု၊ ရဲ၊ အလုပ်သမားဌာန၊ လူကုန်ကူးမှုတားဆီးရေးအဖွဲ့ သို့မဟုတ် ယုံကြည်ရသော NGO ကို ဆက်သွယ်ပါ။ သက်သေစုရန် မိမိကိုယ်ကို ပိုမိုအန္တရာယ်မဖြစ်စေပါနှင့်။"], items:["လုံခြုံစွာ post၊ account၊ ဖုန်း၊ chat၊ contract၊ payment နှင့် location record များကို သိမ်းပါ။", "ယုံကြည်ရသူအား နေရာနှင့်အခြေအနေကို ပြောပါ။", "BurmeseBridge တွင် report လုပ်ပါ၊ သို့သော် platform report သည် ရဲတိုင်ကြားမှုအစား မဟုတ်ပါ။"] },
    { title:"၅။ Platform လုပ်ဆောင်ချက်", paragraphs:["ခိုင်လုံသော report ရရှိလျှင် အလုပ်ကြော်ငြာကို ဖျောက်/ဖယ်ရှားခြင်း၊ account ကန့်သတ်ခြင်း၊ လိုအပ်သောမှတ်တမ်းထိန်းသိမ်းခြင်းနှင့် သက်ဆိုင်ရာအာဏာပိုင်များနှင့် ပူးပေါင်းခြင်း ပြုနိုင်သည်။"] },
    { title:"၆။ ဆက်သွယ်ရန်", paragraphs:["အရေးပေါ်မဟုတ်သော တိုင်ကြားချက်များကို ဝက်ဘ်ဆိုက်၏ အကြံပြုချက်နှင့် ချို့ယွင်းချက်တိုင်ကြားရန် စာမျက်နှာမှ ပေးပို့နိုင်သည် သို့မဟုတ် admin@burmesebridge.com သို့ ဆက်သွယ်နိုင်ပါသည်။ စကားဝှက်၊ OTP သို့မဟုတ် မလိုအပ်သော ကိုယ်ရေးအထောက်အထားအပြည့်အစုံကို အီးမေးလ်ဖြင့် မပေးပို့ပါနှင့်။"] },
  ]},
  en: { title:"Jobseeker Safety Center", summary:"Recognize recruitment scams, forced labour, and human-trafficking risks, and know what to do when danger arises.", updated:"August 14, 2026", sections:[
    { title:"1. Verify before applying", paragraphs:["Do not treat a chat account, group post, or company logo as proof. Verify the registered company name, office, recruiter identity, licence, wage payer, and written contract. For cross-border work, check with competent authorities or properly licensed agencies in both locations."], items:["Confirm the recruiter through an independently found company channel.", "Request a written contract in a language you understand and keep a copy.", "Verify the work, wages, hours, location, rest, accommodation, insurance, visa, and right to leave."] },
    { title:"2. Warning signs", paragraphs:["One indicator alone may not prove a crime, but multiple indicators require urgent caution and further inquiry."], items:["Unusually high pay, no interview, pressure to travel immediately, or secret meetings.", "Unexplained recruitment, deposit, training, travel, or visa charges, especially to personal accounts.", "Requests for passwords, codes, bank control, passports, identity documents, or phones.", "Work, wages, location, or accommodation that differs materially after arrival.", "Restrictions on leaving or contacting family, or threats involving debt, immigration status, violence, or withheld wages."] },
    { title:"3. Interview and travel safety", paragraphs:["Prefer a verifiable office or video interview. Give a trusted contact the employer, recruiter, address, journey, vehicle, and accommodation details and arrange regular check-ins. Do not go alone to isolated locations or surrender original identity documents for continued control."] },
    { title:"4. If you are in danger", paragraphs:["If danger is immediate, prioritize leaving when safely possible and contact local emergency services, police, labour authorities, anti-trafficking services, or a trusted NGO. Do not increase your risk merely to gather evidence."], items:["When safe, preserve listings, account names, phone numbers, chats, contracts, transfers, and location records.", "Tell a trusted person where you are and what is happening.", "Report the listing through BurmeseBridge with relevant links; a platform report is not a substitute for emergency or police assistance."] },
    { title:"5. Platform response", paragraphs:["After a credible report, BurmeseBridge may hide or remove content, restrict accounts, preserve necessary records, and cooperate with competent authorities. Sensitive reporter information is not made public except where legally required or necessary for urgent safety."] },
    { title:"6. Contact", paragraphs:["Use the website feedback form for non-emergency reports or email admin@burmesebridge.com. Never email passwords, verification codes, or unnecessary full identity-document images."] },
  ]},
};

export default async function SafetyPage({ params }: { params: Promise<{ locale:string }> }) { const { locale } = await params; return <LegalPage locale={locale} {...(content[locale] || content.en)} />; }
