-- HSK 6 mastery-level four-skill pilot with original multilingual content and
-- an attributed MIT-licensed vocabulary reference.
do $$
#variable_conflict use_variable
declare v record;product bigint;section_id bigint;lesson_id bigint;quiz_id bigint;question_id bigint;
begin
 for v in select * from(values
 ('listening','听力','နားထောင်မှု','Listening','高密度信息整合与批判性判断','အချက်အလက်သိပ်သည်းမှု ပေါင်းစည်းခြင်းနှင့် ဝေဖန်ဆုံးဖြတ်ခြင်း','Dense information synthesis and critical judgment','听 8–10 分钟讲座、辩论或专题节目，实时区分主张、事实、假设和价值判断。比较不同说话人的前提与证据，整理共识、分歧及尚未解决的问题。','၈–၁၀ မိနစ်ကြာ ဟောပြောချက်၊ ငြင်းခုံမှု သို့မဟုတ် အထူးအစီအစဉ်ကို နားထောင်ပြီး အဆို၊ အချက်အလက်၊ ယူဆချက်နှင့် တန်ဖိုးဆုံးဖြတ်ချက်ကို ချက်ချင်းခွဲခြားပါ။ ပြောသူများ၏ အခြေခံယူဆချက်နှင့် အထောက်အထားကို နှိုင်းယှဉ်ကာ သဘောတူချက်၊ ကွဲလွဲချက်နှင့် မဖြေရှင်းရသေးသောမေးခွန်းများကို စုစည်းပါ။','Listen to an 8–10 minute lecture, debate or feature. Distinguish claims, facts, assumptions and value judgments in real time; compare speakers’ premises and evidence; synthesize agreement, disagreement and unresolved questions.','["前提 · qiántí · အခြေခံယူဆချက် · premise","共识 · gòngshí · ဘုံသဘောတူချက် · consensus","分歧 · fēnqí · ကွဲလွဲချက် · disagreement","质疑 · zhìyí · သံသယဖြင့်မေးမြန်းသည် · challenge"]','两位专家都承认数据有限，但对政策是否应立即实施意见不同。他们的共识是什么？','ကျွမ်းကျင်သူနှစ်ဦးလုံး ဒေတာကန့်သတ်မှုကို လက်ခံသော်လည်း မူဝါဒချက်ချင်းအကောင်အထည်ဖော်မှုအပေါ် ကွဲလွဲကြသည်။ ဘုံသဘောတူချက်မှာ ဘာလဲ။','Both experts accept that the data are limited but disagree on immediate implementation. What is their consensus?','["现有数据有限","政策必须立即实施","政策永远不应实施"]','现有数据有限','现有数据有限，但是否立即实施这项政策，我们的判断并不相同。','听力作业：多方观点综合报告','နားထောင်မှုအိမ်စာ — အမြင်မျိုးစုံပေါင်းစည်းအစီရင်ခံစာ','Listening assignment — Multi-view synthesis','听一段 8–10 分钟圆桌讨论，提交各方立场、前提、证据质量、共识、分歧和你对未决问题的判断。','၈–၁၀ မိနစ် စားပွဲဝိုင်းဆွေးနွေးမှုကို နားထောင်ပြီး ပါဝင်သူတိုင်း၏ ရပ်တည်ချက်၊ အခြေခံယူဆချက်၊ အထောက်အထားအရည်အသွေး၊ ဘုံသဘောတူချက်၊ ကွဲလွဲချက်နှင့် မဖြေရှင်းရသေးသည့်အချက်အပေါ် သင်၏ဆုံးဖြတ်ချက်ကို တင်ပါ။','Listen to an 8–10 minute panel and submit each position, premise, evidence quality, consensus, disagreement and your judgment on unresolved issues.'),
 ('speaking','口语','ပြောဆိုမှု','Speaking','复杂议题协商、论辩与精准表达','ရှုပ်ထွေးအကြောင်းအရာ ညှိနှိုင်းခြင်း၊ ငြင်းခုံခြင်းနှင့် တိကျဖော်ပြခြင်း','Negotiation, argument and precision on complex issues','在正式讨论中界定概念、限定主张范围、主动回应证据不足，并根据听众调整语体。协商时提出底线、可让步条件和可执行方案，避免模糊或绝对化表达。','တရားဝင်ဆွေးနွေးမှုတွင် အယူအဆကို သတ်မှတ်၊ အဆိုအတိုင်းအတာကို ကန့်သတ်ပြီး အထောက်အထားမလုံလောက်မှုကို ကိုယ်တိုင်တုံ့ပြန်ကာ ပရိသတ်အလိုက် ဘာသာပုံစံပြောင်းပါ။ ညှိနှိုင်းရာတွင် အနိမ့်ဆုံးလိုအပ်ချက်၊ လျှော့ပေးနိုင်သောအခြေအနေနှင့် လက်တွေ့အကောင်အထည်ဖော်နိုင်သောအစီအစဉ်ကို တင်ပြပါ။','In formal discussion, define concepts, limit claim scope, address evidence gaps and adapt register to the audience. In negotiation, state minimum requirements, possible concessions and an executable proposal without vague or absolute language.','["界定 · jièdìng · သတ်မှတ်ကန့်သတ်သည် · define","让步 · ràngbù · လျှော့ပေးသည် · concede","可行性 · kěxíngxìng · လက်တွေ့လုပ်နိုင်မှု · feasibility","措辞 · cuòcí · စကားလုံးရွေးချယ်မှု · wording"]','哪一句最能体现严谨的限定？','တိကျသောကန့်သတ်မှုကို အကောင်းဆုံးဖော်ပြသည့်ဝါကျမှာ မည်သည့်ဝါကျနည်း။','Which sentence shows the most careful qualification?','["所有情况下都一定有效。","在样本范围内，这一方法显示出一定效果，但仍需长期验证。","这件事完全没有讨论价值。"]','在样本范围内，这一方法显示出一定效果，但仍需长期验证。',null,'口语作业：政策协商模拟','ပြောဆိုမှုအိမ်စာ — မူဝါဒညှိနှိုင်းမှုသရုပ်ပြ','Speaking assignment — Policy negotiation simulation','录制 6–8 分钟政策协商：界定问题、陈述底线、评估两种方案、作出合理让步并形成可执行结论。','၆–၈ မိနစ် မူဝါဒညှိနှိုင်းမှုအသံသွင်းပါ။ ပြဿနာသတ်မှတ်ခြင်း၊ အနိမ့်ဆုံးလိုအပ်ချက်၊ အစီအစဉ် ၂ ခုအကဲဖြတ်ခြင်း၊ သင့်တော်သောလျှော့ပေးမှုနှင့် လက်တွေ့နိဂုံး ပါစေ။','Record a 6–8 minute policy negotiation defining the issue, stating minimum requirements, evaluating two options, making a reasoned concession and reaching an actionable conclusion.'),
 ('reading','阅读','ဖတ်ရှုမှု','Reading','跨文本比较、隐含假设与知识结构','စာတမ်းများအကြား နှိုင်းယှဉ်မှု၊ သွယ်ဝိုက်ယူဆချက်နှင့် အသိပညာဖွဲ့စည်းပုံ','Cross-text comparison, assumptions and knowledge structure','比较两至三篇 1000 字左右的报道、评论或学术普及文章，追踪概念定义、证据来源和因果链，识别隐含假设、利益关系及修辞框架，建立跨文本知识图谱。','တရုတ်စာလုံး ၁၀၀၀ ခန့်ပါ သတင်း၊ သုံးသပ်ချက် သို့မဟုတ် ပညာရပ်မိတ်ဆက်စာ ၂–၃ ပုဒ်ကို နှိုင်းယှဉ်ပါ။ အယူအဆသတ်မှတ်ချက်၊ အထောက်အထားရင်းမြစ်နှင့် အကြောင်းရင်းကွင်းဆက်ကို လိုက်ကာ သွယ်ဝိုက်ယူဆချက်၊ အကျိုးစီးပွားဆက်နွယ်မှုနှင့် အရေးအသားဘောင်ကို ခွဲခြားပြီး စာတမ်းအကြား အသိပညာမြေပုံတည်ဆောက်ပါ။','Compare two or three texts of about 1,000 Chinese characters. Trace definitions, evidence sources and causal chains; identify assumptions, interests and rhetorical framing; build a cross-text knowledge map.','["隐含假设 · yǐnhán jiǎshè · သွယ်ဝိုက်ယူဆချက် · implicit assumption","因果链 · yīnguǒ liàn · အကြောင်းရင်းကွင်းဆက် · causal chain","框架 · kuàngjià · တင်ပြဘောင် · framing","利益相关者 · lìyì xiāngguānzhě · အကျိုးစီးပွားပါဝင်သူ · stakeholder"]','两篇文章使用相同数据却得出相反结论，首先应比较什么？','စာတမ်းနှစ်ပုဒ်က ဒေတာတူသုံးပြီး ဆန့်ကျင်နိဂုံးရလျှင် ဦးစွာ ဘာကို နှိုင်းယှဉ်သင့်သနည်း။','Two texts use the same data but reach opposite conclusions. What should be compared first?','["各自的前提、定义和推理过程","文章字体大小","作者名字长短"]','各自的前提、定义和推理过程',null,'阅读作业：跨文本综合评估','ဖတ်ရှုမှုအိမ်စာ — စာတမ်းအကြား ပေါင်းစပ်အကဲဖြတ်ခြင်း','Reading assignment — Cross-text evaluation','选择三篇同主题文章，提交概念、立场、证据、假设、利益关系和因果链比较表，并写 400 字综合评估。','တူညီသောခေါင်းစဉ်စာတမ်း ၃ ပုဒ်ရွေးပြီး အယူအဆ၊ ရပ်တည်ချက်၊ အထောက်အထား၊ ယူဆချက်၊ အကျိုးစီးပွားဆက်နွယ်မှုနှင့် အကြောင်းရင်းကွင်းဆက် နှိုင်းယှဉ်ဇယားနှင့် စာလုံး ၄၀၀ ပေါင်းစပ်အကဲဖြတ်ချက်တင်ပါ။','Choose three texts on one topic and submit a comparison of concepts, positions, evidence, assumptions, interests and causal chains plus a 400-character synthesis.'),
 ('writing','书写','ရေးသားမှု','Writing','正式长文、综合论证与编辑规范','တရားဝင်ရှည်စာ၊ ပေါင်းစပ်အဆိုနှင့် တည်းဖြတ်စံ','Formal long-form writing, synthesis and editing','完成 700–900 字正式文章：明确研究问题，综合多个来源，区分事实、引用与个人判断，处理反例和局限，并经过结构、语言和格式三轮编辑。所有来源必须可追溯。','တရုတ်စာလုံး ၇၀၀–၉၀၀ ပါ တရားဝင်စာတွင် လေ့လာမေးခွန်းရှင်းလင်း၊ ရင်းမြစ်မျိုးစုံပေါင်းစည်း၊ အချက်အလက်၊ ကိုးကားချက်နှင့် ကိုယ်ပိုင်ဆုံးဖြတ်ချက် ခွဲခြား၊ ဆန့်ကျင်ဥပမာနှင့် ကန့်သတ်ချက်ကို ကိုင်တွယ်ပြီး ဖွဲ့စည်းပုံ၊ ဘာသာနှင့် format ကို ၃ ကြိမ်တည်းဖြတ်ပါ။ ရင်းမြစ်အားလုံး ပြန်လည်စစ်ဆေးနိုင်ရမည်။','Produce a 700–900 character formal article with a clear research question, synthesis of multiple sources, separation of fact, quotation and judgment, treatment of counterexamples and limitations, and three editing passes for structure, language and format. All sources must be traceable.','["综合论证 · zōnghé lùnzhèng · ပေါင်းစပ်အဆိုပြုမှု · synthesis","局限性 · júxiànxìng · ကန့်သတ်ချက် · limitation","可追溯 · kě zhuīsù · ပြန်လည်ခြေရာခံနိုင်သော · traceable","编辑规范 · biānjí guīfàn · တည်းဖြတ်စံ · editorial standard"]','正式文章引用资料时，最基本的要求是什么？','တရားဝင်စာတွင် အချက်အလက်ကို ကိုးကားရာ၌ အခြေခံအလိုအပ်ဆုံးမှာ ဘာလဲ။','What is the most basic requirement when citing material in formal writing?','["清楚标明来源并可核实","省略来源以节省篇幅","只引用支持自己的内容"]','清楚标明来源并可核实',null,'写作作业：专题分析报告','ရေးသားမှုအိမ်စာ — အထူးခေါင်းစဉ်ခွဲခြမ်းအစီရင်ခံစာ','Writing assignment — Thematic analysis report','围绕教育公平、跨境就业或数字隐私写 700–900 字报告，综合至少三个可核实来源，包含反例、局限和完整修改说明。','ပညာရေးတန်းတူညီမျှမှု၊ နယ်စပ်ဖြတ်ကျော်အလုပ်အကိုင် သို့မဟုတ် ဒစ်ဂျစ်တယ်ကိုယ်ရေးလုံခြုံမှုအကြောင်း တရုတ်စာလုံး ၇၀၀–၉၀၀ အစီရင်ခံစာရေးပါ။ စစ်ဆေးနိုင်သောရင်းမြစ် အနည်းဆုံး ၃ ခု၊ ဆန့်ကျင်ဥပမာ၊ ကန့်သတ်ချက်နှင့် ပြင်ဆင်ချက်ရှင်းလင်းမှု ပါစေ။','Write a 700–900 character report on educational equity, cross-border employment or digital privacy, synthesizing at least three verifiable sources with counterexamples, limitations and a revision note.')
 )as x(skill,skill_zh,skill_my,skill_en,unit_zh,unit_my,unit_en,body_zh,body_my,body_en,vocabulary,prompt_zh,prompt_my,prompt_en,options,answer,speech_text,assignment_zh,assignment_my,assignment_en,instructions_zh,instructions_my,instructions_en)
 loop
  select id into product from public.knowledge_products where catalog_key='hsk-6-'||v.skill;if product is null then raise exception 'Missing HSK 6 course: %',v.skill;end if;
  insert into public.knowledge_resource_licenses(product_id,resource_type,title,source_url,author_name,license_code,license_url,attribution_text,verified_at)select product,'dataset','HSK Cards HSK 6 vocabulary dataset','https://github.com/tnm/hsk/blob/main/public/data/hsk6.csv','Ted Nyman','MIT','https://github.com/tnm/hsk/blob/main/LICENSE','HSK 6 vocabulary adapted from HSK Cards by Ted Nyman under the MIT License.',now()where not exists(select 1 from public.knowledge_resource_licenses where product_id=product and source_url='https://github.com/tnm/hsk/blob/main/public/data/hsk6.csv');
  insert into public.knowledge_course_sections(product_id,catalog_key,title_zh,title_my,title_en,position,status)values(product,'hsk-6-'||v.skill||'-foundation','第一章：'||v.unit_zh,'အခန်း ၁ — '||v.unit_my,'Section 1 — '||v.unit_en,0,'published')on conflict do nothing;select id into section_id from public.knowledge_course_sections where catalog_key='hsk-6-'||v.skill||'-foundation';
  insert into public.knowledge_lessons(product_id,section_id,catalog_key,title_zh,title_my,title_en,position,free_preview,status)values(product,section_id,'hsk-6-'||v.skill||'-lesson-1','第 1 课：'||v.unit_zh,'သင်ခန်းစာ ၁ — '||v.unit_my,'Lesson 1 — '||v.unit_en,0,true,'published')on conflict do nothing;select id into lesson_id from public.knowledge_lessons where catalog_key='hsk-6-'||v.skill||'-lesson-1';
  insert into public.knowledge_lesson_content(lesson_id,body_zh,body_my,body_en,vocabulary,handout_zh,handout_my,handout_en)values(lesson_id,v.body_zh,v.body_my,v.body_en,v.vocabulary::jsonb,'学习流程：定义问题 → 多源分析 → 批判判断 → 测验 → 教师评阅成果。','လေ့လာမှုအစဉ် — ပြဿနာသတ်မှတ် → ရင်းမြစ်မျိုးစုံခွဲခြမ်း → ဝေဖန်ဆုံးဖြတ် → စစ်ဆေးမှု → ဆရာစစ်ဆေးသည့်ရလဒ်။','Study flow: define the problem → multi-source analysis → critical judgment → quiz → instructor-reviewed product.')on conflict do nothing;
  insert into public.knowledge_quizzes(lesson_id,catalog_key,title_zh,title_my,title_en,passing_score,status)values(lesson_id,'hsk-6-'||v.skill||'-quiz-1',v.skill_zh||'熟练级测验',v.skill_my||' ကျွမ်းကျင်အဆင့်စစ်ဆေးမှု',v.skill_en||' mastery quiz',75,'published')on conflict do nothing;select id into quiz_id from public.knowledge_quizzes where catalog_key='hsk-6-'||v.skill||'-quiz-1';if not exists(select 1 from public.knowledge_quiz_questions q where q.quiz_id=quiz_id)then insert into public.knowledge_quiz_questions(quiz_id,question_type,prompt_zh,prompt_my,prompt_en,options,speech_text,position,points)values(quiz_id,case when v.skill='listening'then'listening'else'single'end,v.prompt_zh,v.prompt_my,v.prompt_en,v.options::jsonb,v.speech_text,0,2)returning id into question_id;insert into public.knowledge_quiz_answer_keys(question_id,correct_answer)values(question_id,to_jsonb(v.answer));end if;
  insert into public.knowledge_assignments(lesson_id,catalog_key,title_zh,title_my,title_en,instructions_zh,instructions_my,instructions_en,max_score,due_days,status)values(lesson_id,'hsk-6-'||v.skill||'-assignment-1',v.assignment_zh,v.assignment_my,v.assignment_en,v.instructions_zh,v.instructions_my,v.instructions_en,100,14,'published')on conflict do nothing;
  update public.knowledge_products set status='published',description_zh='HSK 6 '||v.skill_zh||'熟练级课程：'||v.unit_zh||'，包含多源分析、测验和教师评阅成果。',description_my='HSK 6 '||v.skill_my||' ကျွမ်းကျင်အဆင့်သင်တန်း — '||v.unit_my||'၊ ရင်းမြစ်မျိုးစုံခွဲခြမ်းမှု၊ စစ်ဆေးမှုနှင့် ဆရာစစ်ဆေးသည့်ရလဒ် ပါဝင်သည်။',description_en='HSK 6 mastery '||lower(v.skill_en)||' course covering '||lower(v.unit_en)||', with multi-source analysis, assessment and instructor review.'where id=product;
 end loop;
end$$;
