create table if not exists public.hsk_assessment_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  estimated_level smallint not null check (estimated_level between 0 and 6),
  cefr_level text not null check (cefr_level in ('Pre-A1','A1','A2','B1','B2','C1','C2')),
  score smallint not null check (score between 0 and 100),
  correct_answers smallint not null check (correct_answers >= 0),
  total_questions smallint not null check (total_questions > 0),
  answers jsonb not null default '{}'::jsonb,
  level_breakdown jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hsk_assessment_attempts_user_created_idx on public.hsk_assessment_attempts(user_id,created_at desc);
alter table public.hsk_assessment_attempts enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='hsk_assessment_attempts' and policyname='Users view own HSK attempts') then
    create policy "Users view own HSK attempts" on public.hsk_assessment_attempts for select using (auth.uid()=user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='hsk_assessment_attempts' and policyname='Users create own HSK attempts') then
    create policy "Users create own HSK attempts" on public.hsk_assessment_attempts for insert with check (auth.uid()=user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='hsk_assessment_attempts' and policyname='Users delete own HSK attempts') then
    create policy "Users delete own HSK attempts" on public.hsk_assessment_attempts for delete using (auth.uid()=user_id);
  end if;
end $$;
