-- HSK 5 advanced four-skill pilot. Original course content is combined with
-- an attributed MIT-licensed vocabulary reference.
do $$
#variable_conflict use_variable
declare v record;product bigint;section_id bigint;lesson_id bigint;quiz_id bigint;question_id bigint;
begin
 for v in select * from(values
 ('listening','听力','နားထောင်မှု','Listening','长篇讲话的立场、论据与修辞','ရှည်လျားသောပြောဆိုမှု၏ ရပ်တည်ချက်၊ အထောက်အထားနှင့် အရေးအသားနည်း','Position, evidence and rhetoric in extended speech','听 4–6 分钟讲话时，建立“主题—立场—论据—例证—结论”笔记框架。识别反问、强调和语气变化，判断说话人如何影响听众。','၄–၆ မိနစ်ကြာ ပြောဆိုမှုကို နားထောင်ရာတွင် “ခေါင်းစဉ်—ရပ်တည်ချက်—အထောက်အထား—ဥပမာ—နိဂုံး” မှတ်စုဖွဲ့ပါ။ မေးခွန်းပြန်မေးမှု၊ အလေးပေးမှုနှင့် အသံနေအသံထားပြောင်းလဲမှုကို ခွဲခြားပြီး ပရိသတ်အပေါ် သက်ရောက်ပုံကို ဆုံးဖြတ်ပါ။','For a 4–6 minute talk, note topic, position, evidence, examples and conclusion. Identify rhetorical questions, emphasis and changes in tone, and judge how the speaker influences the audience.','["立场 · lìchǎng · ရပ်တည်ချက် · position","论据 · lùnjù · အဆိုအထောက်အထား · supporting evidence","强调 · qiángdiào · အလေးပေးသည် · emphasize","反问 · fǎnwèn · ပြန်လည်မေးခွန်း · rhetorical question"]','听：“难道提高效率就一定要牺牲质量吗？”说话人主要在做什么？','နားထောင်ပါ — “难道提高效率就一定要牺牲质量吗？” ပြောသူက အဓိက ဘာလုပ်နေသနည်း။','Listen: “难道提高效率就一定要牺牲质量吗？” What is the speaker mainly doing?','["用反问质疑一种观点","说明具体时间","赞成牺牲质量"]','用反问质疑一种观点','难道提高效率就一定要牺牲质量吗？','听力作业：演讲论证地图','နားထောင်မှုအိမ်စာ — မိန့်ခွန်းအဆိုမြေပုံ','Listening assignment — Speech argument map','听一段 5 分钟讲话，提交立场、三项论据、两项例证、修辞手段和结论的结构图。','၅ မိနစ်ပြောဆိုမှုကို နားထောင်ပြီး ရပ်တည်ချက်၊ အထောက်အထား ၃ ခု၊ ဥပမာ ၂ ခု၊ အရေးအသားနည်းနှင့် နိဂုံးဖွဲ့စည်းပုံကို တင်ပါ။','Listen to a five-minute talk and submit a map of its position, three reasons, two examples, rhetorical devices and conclusion.'),
 ('speaking','口语','ပြောဆိုမှု','Speaking','正式陈述、即席回应与总结','တရားဝင်တင်ပြခြင်း၊ ချက်ချင်းတုံ့ပြန်ခြင်းနှင့် အကျဉ်းချုပ်','Formal presentation, spontaneous response and summary','进行 4–5 分钟正式陈述：明确目的，预告结构，用数据或实例支持观点，并在结尾总结。问答环节先概括问题，再直接回应并说明依据。','၄–၅ မိနစ် တရားဝင်တင်ပြရာတွင် ရည်ရွယ်ချက်ကို ရှင်းလင်းပြီး ဖွဲ့စည်းပုံကို ကြိုပြောကာ ဒေတာ သို့မဟုတ် ဥပမာဖြင့် အမြင်ထောက်ခံပြီး အဆုံးတွင် အကျဉ်းချုပ်ပါ။ မေးဖြေရာတွင် မေးခွန်းကို ဦးစွာအကျဉ်းချုပ်ပြီး တိုက်ရိုက်ဖြေကာ အထောက်အထားရှင်းပါ။','Give a 4–5 minute formal presentation with a clear purpose, previewed structure, supporting data or examples and a conclusion. In Q&A, summarize the question, answer directly and explain the basis.','["概括 · gàikuò · အကျဉ်းချုပ်သည် · summarize","依据 · yījù · အခြေခံအထောက်အထား · basis","换句话说 · huàn jù huà shuō · တစ်နည်းအားဖြင့် · in other words","综上所述 · zōngshàng suǒshù · အထက်ပါအရ · in summary"]','正式陈述结束时，哪一句最合适？','တရားဝင်တင်ပြမှုအဆုံးတွင် မည်သည့်ဝါကျ အသင့်တော်ဆုံးနည်း။','Which sentence best closes a formal presentation?','["综上所述，这项方案值得进一步试行。","我突然忘了。","反正就是这样。"]','综上所述，这项方案值得进一步试行。',null,'口语作业：五分钟正式陈述','ပြောဆိုမှုအိမ်စာ — ငါးမိနစ်တရားဝင်တင်ပြခြင်း','Speaking assignment — Five-minute presentation','就教育、就业或环境问题录制 4–5 分钟陈述，包含明确结构、可靠例证、反方观点回应和总结。','ပညာရေး၊ အလုပ်အကိုင် သို့မဟုတ် ပတ်ဝန်းကျင်ပြဿနာအကြောင်း ၄–၅ မိနစ် တင်ပြပြီး ရှင်းလင်းသောဖွဲ့စည်းပုံ၊ ယုံကြည်ရသောဥပမာ၊ ဆန့်ကျင်အမြင်တုံ့ပြန်မှုနှင့် အကျဉ်းချုပ် ပါစေ။','Record a 4–5 minute presentation on education, employment or the environment with clear structure, credible examples, a response to an opposing view and a summary.'),
 ('reading','阅读','ဖတ်ရှုမှု','Reading','复杂文本的论证、语体与作者意图','ရှုပ်ထွေးစာတမ်း၏ အဆိုဖွဲ့စည်းမှု၊ ဘာသာပုံစံနှင့် စာရေးသူရည်ရွယ်ချက်','Argument, register and author intent in complex texts','阅读 600–800 字评论、报道或说明文，比较标题与正文立场，追踪代词指代和段落逻辑，评价证据是否充分，并判断正式、讽刺或客观等语体效果。','တရုတ်စာလုံး ၆၀၀–၈၀၀ ပါ သုံးသပ်ချက်၊ သတင်း သို့မဟုတ် ရှင်းလင်းစာကို ဖတ်ပြီး ခေါင်းစဉ်နှင့် ကိုယ်စာ၏ရပ်တည်ချက်ကို နှိုင်းယှဉ်ပါ။ နာမ်စားရည်ညွှန်းမှုနှင့် စာပိုဒ်ယုတ္တိကို လိုက်ကာ အထောက်အထားလုံလောက်မှုနှင့် တရားဝင်၊ သရော် သို့မဟုတ် အလယ်အလတ်ဘာသာပုံစံ၏ သက်ရောက်မှုကို ဆုံးဖြတ်ပါ။','Read a 600–800 character commentary, report or exposition. Compare headline and text positions, track references and paragraph logic, evaluate evidence sufficiency, and identify the effect of formal, ironic or objective register.','["语体 · yǔtǐ · ဘာသာအသုံးပုံစံ · register","客观 · kèguān · အလယ်အလတ်အမြင် · objective","讽刺 · fěngcì · သရော်မှု · irony","充分 · chōngfèn · လုံလောက်သော · sufficient"]','一篇报道只引用支持某观点的人，没有提供其他数据。主要问题是什么？','သတင်းတစ်ပုဒ်တွင် အမြင်တစ်ခုကို ထောက်ခံသူများကိုသာ ကိုးကားပြီး အခြားဒေတာမပေးပါ။ အဓိကပြဿနာမှာ ဘာလဲ။','A report quotes only supporters of one view and gives no other data. What is the main problem?','["证据可能片面且不充分","标题太短","段落数量太多"]','证据可能片面且不充分',null,'阅读作业：批判性阅读报告','ဖတ်ရှုမှုအိမ်စာ — ဝေဖန်ဖတ်ရှုမှုအစီရင်ခံစာ','Reading assignment — Critical reading report','选择一篇 600–800 字文章，分析主张、证据来源、遗漏观点、语体和作者意图，写 250 字评估。','တရုတ်စာလုံး ၆၀၀–၈၀၀ ပါ စာတမ်းတစ်ပုဒ်ရွေးပြီး အဆို၊ အထောက်အထားရင်းမြစ်၊ လွတ်သွားသောအမြင်၊ ဘာသာပုံစံနှင့် စာရေးသူရည်ရွယ်ချက်ကို ခွဲခြမ်းကာ စာလုံး ၂၅၀ အကဲဖြတ်ချက်ရေးပါ။','Choose a 600–800 character article and write a 250-character evaluation of its claims, evidence sources, omitted perspectives, register and author intent.'),
 ('writing','书写','ရေးသားမှု','Writing','完整议论文、证据整合与修改','ပြည့်စုံဆွေးနွေးစာ၊ အထောက်အထားပေါင်းစည်းမှုနှင့် ပြင်ဆင်ခြင်း','Full argument, evidence integration and revision','写 350–450 字议论文，提出可辩论的中心论点，安排两至三个分论点，整合事实和例子，回应反方意见，并通过两轮修改改善逻辑、措辞和句式变化。','တရုတ်စာလုံး ၃၅၀–၄၅၀ ပါ ဆွေးနွေးစာတွင် ဆွေးနွေးနိုင်သောအဓိကအဆို၊ ခွဲအဆို ၂–၃ ခု၊ အချက်အလက်နှင့် ဥပမာပေါင်းစည်းမှု၊ ဆန့်ကျင်အမြင်တုံ့ပြန်မှု ပါစေ။ ယုတ္တိ၊ စကားလုံးရွေးချယ်မှုနှင့် ဝါကျပုံစံကို ၂ ကြိမ်ပြင်ဆင်ပါ။','Write a 350–450 character argument with a debatable thesis, two or three supporting claims, integrated facts and examples, a counterargument response, and two revision passes for logic, diction and sentence variety.','["核心论点 · héxīn lùndiǎn · အဓိကအဆို · thesis","反方观点 · fǎnfāng guāndiǎn · ဆန့်ကျင်အမြင် · counterargument","修改 · xiūgǎi · ပြင်ဆင်သည် · revise","连贯性 · liánguànxìng · ဆက်စပ်ညီညွတ်မှု · coherence"]','哪一项最能增强议论文的可信度？','ဆွေးနွေးစာ၏ ယုံကြည်နိုင်မှုကို မည်သည့်အရာ အကောင်းဆုံးတိုးစေသနည်း။','What best strengthens the credibility of an argument?','["提供可核实的事实并说明来源","重复同一句话","只使用强烈形容词"]','提供可核实的事实并说明来源',null,'写作作业：公共议题议论文','ရေးသားမှုအိမ်စာ — အများပြည်သူဆိုင်ရာ ဆွေးနွေးစာ','Writing assignment — Public issue essay','就远程工作、人工智能教育或城市发展写 350–450 字议论文，包含中心论点、证据、反方回应和修改说明。','အဝေးမှအလုပ်လုပ်ခြင်း၊ AI ပညာရေး သို့မဟုတ် မြို့ပြဖွံ့ဖြိုးမှုအကြောင်း တရုတ်စာလုံး ၃၅၀–၄၅၀ ဆွေးနွေးစာရေးပြီး အဓိကအဆို၊ အထောက်အထား၊ ဆန့်ကျင်အမြင်တုံ့ပြန်မှုနှင့် ပြင်ဆင်ချက်ရှင်းလင်းမှု ပါစေ။','Write a 350–450 character argument on remote work, AI in education or urban development, including a thesis, evidence, counterargument response and revision note.')
 )as x(skill,skill_zh,skill_my,skill_en,unit_zh,unit_my,unit_en,body_zh,body_my,body_en,vocabulary,prompt_zh,prompt_my,prompt_en,options,answer,speech_text,assignment_zh,assignment_my,assignment_en,instructions_zh,instructions_my,instructions_en)
 loop
  select id into product from public.knowledge_products where catalog_key='hsk-5-'||v.skill;if product is null then raise exception 'Missing HSK 5 course: %',v.skill;end if;
  insert into public.knowledge_resource_licenses(product_id,resource_type,title,source_url,author_name,license_code,license_url,attribution_text,verified_at)select product,'dataset','HSK Cards HSK 5 vocabulary dataset','https://github.com/tnm/hsk/blob/main/public/data/hsk5.csv','Ted Nyman','MIT','https://github.com/tnm/hsk/blob/main/LICENSE','HSK 5 vocabulary adapted from HSK Cards by Ted Nyman under the MIT License.',now()where not exists(select 1 from public.knowledge_resource_licenses where product_id=product and source_url='https://github.com/tnm/hsk/blob/main/public/data/hsk5.csv');
  insert into public.knowledge_course_sections(product_id,catalog_key,title_zh,title_my,title_en,position,status)values(product,'hsk-5-'||v.skill||'-foundation','第一章：'||v.unit_zh,'အခန်း ၁ — '||v.unit_my,'Section 1 — '||v.unit_en,0,'published')on conflict do nothing;select id into section_id from public.knowledge_course_sections where catalog_key='hsk-5-'||v.skill||'-foundation';
  insert into public.knowledge_lessons(product_id,section_id,catalog_key,title_zh,title_my,title_en,position,free_preview,status)values(product,section_id,'hsk-5-'||v.skill||'-lesson-1','第 1 课：'||v.unit_zh,'သင်ခန်းစာ ၁ — '||v.unit_my,'Lesson 1 — '||v.unit_en,0,true,'published')on conflict do nothing;select id into lesson_id from public.knowledge_lessons where catalog_key='hsk-5-'||v.skill||'-lesson-1';
  insert into public.knowledge_lesson_content(lesson_id,body_zh,body_my,body_en,vocabulary,handout_zh,handout_my,handout_en)values(lesson_id,v.body_zh,v.body_my,v.body_en,v.vocabulary::jsonb,'学习流程：建立分析框架 → 完成深度任务 → 测验 → 教师评阅作业。','လေ့လာမှုအစဉ် — ခွဲခြမ်းဘောင်တည်ဆောက် → နက်ရှိုင်းလုပ်ငန်း → စစ်ဆေးမှု → ဆရာစစ်ဆေးသည့်အိမ်စာ။','Study flow: build an analysis framework → complete the advanced task → quiz → instructor-reviewed assignment.')on conflict do nothing;
  insert into public.knowledge_quizzes(lesson_id,catalog_key,title_zh,title_my,title_en,passing_score,status)values(lesson_id,'hsk-5-'||v.skill||'-quiz-1',v.skill_zh||'高级测验',v.skill_my||' အဆင့်မြင့်စစ်ဆေးမှု',v.skill_en||' advanced quiz',70,'published')on conflict do nothing;select id into quiz_id from public.knowledge_quizzes where catalog_key='hsk-5-'||v.skill||'-quiz-1';if not exists(select 1 from public.knowledge_quiz_questions q where q.quiz_id=quiz_id)then insert into public.knowledge_quiz_questions(quiz_id,question_type,prompt_zh,prompt_my,prompt_en,options,speech_text,position,points)values(quiz_id,case when v.skill='listening'then'listening'else'single'end,v.prompt_zh,v.prompt_my,v.prompt_en,v.options::jsonb,v.speech_text,0,2)returning id into question_id;insert into public.knowledge_quiz_answer_keys(question_id,correct_answer)values(question_id,to_jsonb(v.answer));end if;
  insert into public.knowledge_assignments(lesson_id,catalog_key,title_zh,title_my,title_en,instructions_zh,instructions_my,instructions_en,max_score,due_days,status)values(lesson_id,'hsk-5-'||v.skill||'-assignment-1',v.assignment_zh,v.assignment_my,v.assignment_en,v.instructions_zh,v.instructions_my,v.instructions_en,100,14,'published')on conflict do nothing;
  update public.knowledge_products set status='published',description_zh='HSK 5 '||v.skill_zh||'高级课程：'||v.unit_zh||'，包含多语言策略、测验和教师评阅任务。',description_my='HSK 5 '||v.skill_my||' အဆင့်မြင့်သင်တန်း — '||v.unit_my||'၊ ဘာသာစုံနည်းဗျူဟာ၊ စစ်ဆေးမှုနှင့် ဆရာစစ်ဆေးသည့်လုပ်ငန်း ပါဝင်သည်။',description_en='HSK 5 advanced '||lower(v.skill_en)||' course covering '||lower(v.unit_en)||', with multilingual strategy, assessment and instructor review.'where id=product;
 end loop;
end$$;
