-- HSK 4 four-skill pilot with original multilingual learning material and an
-- independently attributed MIT-licensed vocabulary reference.
do $$
#variable_conflict use_variable
declare v record;product bigint;section_id bigint;lesson_id bigint;quiz_id bigint;question_id bigint;
begin
 for v in select * from(values
 ('listening','听力','နားထောင်မှု','Listening','观点、态度与隐含信息','အမြင်၊ သဘောထားနှင့် သွယ်ဝိုက်အချက်အလက်','Opinion, attitude and implied meaning','听新闻式短文或访谈时，区分事实与观点，记录说话人的态度词，并根据语气和上下文判断没有直接说出的信息。','သတင်းပုံစံစာပိုဒ် သို့မဟုတ် မေးမြန်းခန်းကို နားထောင်ရာတွင် အချက်အလက်နှင့် အမြင်ကို ခွဲခြားပြီး ပြောသူ၏သဘောထားစကားလုံးများကို မှတ်သားကာ အသံနေအသံထားနှင့် စာစပ်မှ သွယ်ဝိုက်အချက်အလက်ကို ဆုံးဖြတ်ပါ။','When listening to a news-style text or interview, separate fact from opinion, note attitude markers and infer unstated information from tone and context.','["观点 · guāndiǎn · အမြင် · viewpoint","态度 · tàidu · သဘောထား · attitude","似乎 · sìhū · ဖြစ်ပုံရသည် · seemingly","实际上 · shíjìshàng · အမှန်တကယ် · actually"]','听：“他嘴上说不累，可一回家就睡着了。”可以推断什么？','နားထောင်ပါ — “他嘴上说不累，可一回家就睡着了。” ဘာကို ကောက်ချက်ချနိုင်သနည်း။','Listen: “他嘴上说不累，可一回家就睡着了。” What can be inferred?','["他其实很累","他不想回家","他没有睡觉"]','他其实很累','他嘴上说不累，可一回家就睡着了。','听力作业：态度证据分析','နားထောင်မှုအိမ်စာ — သဘောထားအထောက်အထား','Listening assignment — Attitude evidence','听两段访谈，写出每位说话人的主要观点、态度及三处语言证据。','မေးမြန်းခန်း ၂ ပုဒ်ကို နားထောင်ပြီး ပြောသူတစ်ဦးစီ၏ အဓိကအမြင်၊ သဘောထားနှင့် ဘာသာစကားအထောက်အထား ၃ ခု ရေးပါ။','Listen to two interviews and identify each speaker’s main view, attitude and three pieces of language evidence.'),
 ('speaking','口语','ပြောဆိုမှု','Speaking','观点陈述与讨论回应','အမြင်တင်ပြခြင်းနှင့် ဆွေးနွေးမှုတုံ့ပြန်ခြင်း','Presenting opinions and responding in discussion','用“我认为、从……来看、虽然……但是……”陈述观点，并用例子支持理由。回应不同意见时先确认对方重点，再礼貌补充或反驳。','“我认为、从……来看、虽然……但是……” ဖြင့် အမြင်တင်ပြပြီး ဥပမာဖြင့် အကြောင်းပြချက်ထောက်ခံပါ။ မတူညီသောအမြင်ကို တုံ့ပြန်ရာတွင် အခြားသူ၏အဓိကအချက်ကို ဦးစွာအတည်ပြုပြီး ယဉ်ကျေးစွာ ဖြည့်စွက် သို့မဟုတ် ချေပပါ။','Present an opinion with 我认为, 从…来看 and 虽然…但是…, supporting reasons with examples. When responding, acknowledge the other view before adding or disagreeing politely.','["我认为 · wǒ rènwéi · ကျွန်ုပ်ထင်သည် · I believe","从……来看 · …မှကြည့်လျှင် · from the perspective of","支持 · zhīchí · ထောက်ခံသည် · support","反对 · fǎnduì · ဆန့်ကျင်သည် · oppose"]','哪一句是礼貌回应不同意见？','မတူညီသောအမြင်ကို ယဉ်ကျေးစွာတုံ့ပြန်သည့်ဝါကျမှာ မည်သည့်ဝါကျနည်း။','Which sentence responds politely to a different opinion?','["你完全错了。","我理解你的看法，不过我认为还要考虑成本。","不要再说了。"]','我理解你的看法，不过我认为还要考虑成本。',null,'口语作业：三分钟观点陈述','ပြောဆိုမှုအိမ်စာ — သုံးမိနစ်အမြင်တင်ပြခြင်း','Speaking assignment — Three-minute opinion','围绕线上学习或城市交通录制 2–3 分钟发言，提出观点、两个理由、一个例子并回应一种反对意见。','Online လေ့လာမှု သို့မဟုတ် မြို့ပြသယ်ယူပို့ဆောင်ရေးအကြောင်း ၂–၃ မိနစ် ပြောပြီး အမြင်၊ အကြောင်းရင်း ၂ ခု၊ ဥပမာ ၁ ခုနှင့် ဆန့်ကျင်အမြင်တုံ့ပြန်မှု ပါစေ။','Record 2–3 minutes on online learning or urban transport with a position, two reasons, one example and a response to an opposing view.'),
 ('reading','阅读','ဖတ်ရှုမှု','Reading','篇章结构、论点与证据','စာတမ်းဖွဲ့စည်းပုံ၊ အဆိုနှင့် အထောက်အထား','Text structure, claims and evidence','阅读 300–400 字说明或议论短文，标记主题句、论点、例证、转折和结论；判断每段在全文中的作用，并区分作者观点与引用事实。','တရုတ်စာလုံး ၃၀၀–၄၀၀ ပါ ရှင်းလင်း သို့မဟုတ် ဆွေးနွေးစာကို ဖတ်ပြီး ခေါင်းစဉ်ဝါကျ၊ အဆို၊ ဥပမာ၊ အလှည့်နှင့် နိဂုံးကို မှတ်သားပါ။ စာပိုဒ်တစ်ခုစီ၏ အခန်းကဏ္ဍကို ဆုံးဖြတ်ပြီး စာရေးသူအမြင်နှင့် ကိုးကားအချက်အလက်ကို ခွဲခြားပါ။','Read a 300–400 character explanatory or argumentative text. Mark topic sentences, claims, examples, contrasts and conclusions; identify each paragraph’s role and distinguish author opinion from cited fact.','["论点 · lùndiǎn · အဆို · claim","证据 · zhèngjù · အထောက်အထား · evidence","此外 · cǐwài · ထို့အပြင် · furthermore","总之 · zǒngzhī · အနှစ်ချုပ်အားဖြင့် · in conclusion"]','文章先提出问题，再列出数据和例子，最后给出建议。数据和例子的作用是什么？','စာတွင် ပြဿနာတင်ပြပြီး ဒေတာနှင့် ဥပမာများဖော်ပြကာ နောက်ဆုံးအကြံပြုသည်။ ဒေတာနှင့် ဥပမာ၏အခန်းကဏ္ဍမှာ ဘာလဲ။','A text presents a problem, then data and examples, and ends with advice. What is the role of the data and examples?','["支持论点","改变主题","介绍作者姓名"]','支持论点',null,'阅读作业：文章结构批注','ဖတ်ရှုမှုအိမ်စာ — စာတမ်းဖွဲ့စည်းပုံမှတ်ချက်','Reading assignment — Structure annotation','批注一篇 350 字文章，标出主旨、各段作用、两项证据、一处转折和结论，并写 100 字摘要。','တရုတ်စာလုံး ၃၅၀ ပါ စာတမ်းတစ်ပုဒ်တွင် အဓိကအကြောင်း၊ စာပိုဒ်အခန်းကဏ္ဍ၊ အထောက်အထား ၂ ခု၊ အလှည့် ၁ ခုနှင့် နိဂုံးကို မှတ်သားကာ စာလုံး ၁၀၀ အကျဉ်းချုပ်ရေးပါ။','Annotate a 350-character article for main idea, paragraph roles, two pieces of evidence, one contrast and the conclusion, then write a 100-character summary.'),
 ('writing','书写','ရေးသားမှု','Writing','说明文与议论段落','ရှင်းလင်းစာနှင့် ဆွေးနွေးစာပိုဒ်','Expository and argumentative paragraphs','写 180–220 字短文，开头明确主题，中间用分类、比较或因果展开，结尾总结。引用事实时避免夸大，并检查指代、连接词和段落一致性。','တရုတ်စာလုံး ၁၈၀–၂၂၀ ပါ စာတွင် အစ၌ ခေါင်းစဉ်ကို ရှင်းလင်းစွာဖော်ပြပြီး အလယ်တွင် အမျိုးအစားခွဲခြင်း၊ နှိုင်းယှဉ်ခြင်း သို့မဟုတ် အကြောင်းရင်း–ရလဒ်ဖြင့် ချဲ့ထွင်ကာ အဆုံးတွင် အကျဉ်းချုပ်ပါ။ အချက်အလက်ကို မချဲ့ကားဘဲ ရည်ညွှန်းမှု၊ ဆက်စပ်စကားလုံးနှင့် စာပိုဒ်ညီညွတ်မှုကို စစ်ဆေးပါ။','Write 180–220 Chinese characters with a clear topic, development by classification, comparison or cause, and a conclusion. Avoid exaggerating facts and check references, connectors and paragraph unity.','["一方面 · yì fāngmiàn · တစ်ဖက်တွင် · on one hand","另一方面 · lìng yì fāngmiàn · အခြားတစ်ဖက်တွင် · on the other hand","由此可见 · yóucǐ kějiàn · ထို့မှမြင်နိုင်သည် · this shows","相比之下 · xiāngbǐ zhīxià · နှိုင်းယှဉ်လျှင် · by comparison"]','选择最适合作为结论的表达。','နိဂုံးအတွက် အသင့်တော်ဆုံးအသုံးအနှုန်းကို ရွေးပါ။','Choose the expression most suitable for a conclusion.','["由此可见","比如说","首先"]','由此可见',null,'写作作业：科技与生活','ရေးသားမှုအိမ်စာ — နည်းပညာနှင့်ဘဝ','Writing assignment — Technology and life','用 180–220 个汉字讨论科技给生活带来的一个好处和一个问题，提供例子并提出建议。','နည်းပညာက လူနေမှုဘဝသို့ ပေးသည့် ကောင်းကျိုး ၁ ခုနှင့် ပြဿနာ ၁ ခုကို တရုတ်စာလုံး ၁၈၀–၂၂၀ ဖြင့် ဆွေးနွေးပြီး ဥပမာနှင့် အကြံပြုချက်ပေးပါ။','Discuss one benefit and one problem technology brings to life in 180–220 Chinese characters, with examples and a recommendation.')
 )as x(skill,skill_zh,skill_my,skill_en,unit_zh,unit_my,unit_en,body_zh,body_my,body_en,vocabulary,prompt_zh,prompt_my,prompt_en,options,answer,speech_text,assignment_zh,assignment_my,assignment_en,instructions_zh,instructions_my,instructions_en)
 loop
  select id into product from public.knowledge_products where catalog_key='hsk-4-'||v.skill;if product is null then raise exception 'Missing HSK 4 course: %',v.skill;end if;
  insert into public.knowledge_resource_licenses(product_id,resource_type,title,source_url,author_name,license_code,license_url,attribution_text,verified_at) select product,'dataset','HSK Cards HSK 4 vocabulary dataset','https://github.com/tnm/hsk/blob/main/public/data/hsk4.csv','Ted Nyman','MIT','https://github.com/tnm/hsk/blob/main/LICENSE','HSK 4 vocabulary adapted from HSK Cards by Ted Nyman under the MIT License.',now() where not exists(select 1 from public.knowledge_resource_licenses where product_id=product and source_url='https://github.com/tnm/hsk/blob/main/public/data/hsk4.csv');
  insert into public.knowledge_course_sections(product_id,catalog_key,title_zh,title_my,title_en,position,status)values(product,'hsk-4-'||v.skill||'-foundation','第一章：'||v.unit_zh,'အခန်း ၁ — '||v.unit_my,'Section 1 — '||v.unit_en,0,'published')on conflict do nothing;select id into section_id from public.knowledge_course_sections where catalog_key='hsk-4-'||v.skill||'-foundation';
  insert into public.knowledge_lessons(product_id,section_id,catalog_key,title_zh,title_my,title_en,position,free_preview,status)values(product,section_id,'hsk-4-'||v.skill||'-lesson-1','第 1 课：'||v.unit_zh,'သင်ခန်းစာ ၁ — '||v.unit_my,'Lesson 1 — '||v.unit_en,0,true,'published')on conflict do nothing;select id into lesson_id from public.knowledge_lessons where catalog_key='hsk-4-'||v.skill||'-lesson-1';
  insert into public.knowledge_lesson_content(lesson_id,body_zh,body_my,body_en,vocabulary,handout_zh,handout_my,handout_en)values(lesson_id,v.body_zh,v.body_my,v.body_en,v.vocabulary::jsonb,'学习流程：分析任务 → 学习策略 → 完成测验 → 提交作业。','လေ့လာမှုအစဉ် — လုပ်ငန်းခွဲခြမ်း → နည်းဗျူဟာလေ့လာ → စစ်ဆေးမှု → အိမ်စာတင်။','Study flow: analyze task → learn strategy → quiz → assignment.')on conflict do nothing;
  insert into public.knowledge_quizzes(lesson_id,catalog_key,title_zh,title_my,title_en,passing_score,status)values(lesson_id,'hsk-4-'||v.skill||'-quiz-1',v.skill_zh||'随堂测验',v.skill_my||' စစ်ဆေးမှု',v.skill_en||' lesson quiz',60,'published')on conflict do nothing;select id into quiz_id from public.knowledge_quizzes where catalog_key='hsk-4-'||v.skill||'-quiz-1';
  if not exists(select 1 from public.knowledge_quiz_questions q where q.quiz_id=quiz_id)then insert into public.knowledge_quiz_questions(quiz_id,question_type,prompt_zh,prompt_my,prompt_en,options,speech_text,position,points)values(quiz_id,case when v.skill='listening'then'listening'else'single'end,v.prompt_zh,v.prompt_my,v.prompt_en,v.options::jsonb,v.speech_text,0,2)returning id into question_id;insert into public.knowledge_quiz_answer_keys(question_id,correct_answer)values(question_id,to_jsonb(v.answer));end if;
  insert into public.knowledge_assignments(lesson_id,catalog_key,title_zh,title_my,title_en,instructions_zh,instructions_my,instructions_en,max_score,due_days,status)values(lesson_id,'hsk-4-'||v.skill||'-assignment-1',v.assignment_zh,v.assignment_my,v.assignment_en,v.instructions_zh,v.instructions_my,v.instructions_en,100,10,'published')on conflict do nothing;
  update public.knowledge_products set status='published',description_zh='HSK 4 '||v.skill_zh||'课程：'||v.unit_zh||'，包含多语言策略讲义、测验和教师批改作业。',description_my='HSK 4 '||v.skill_my||' သင်တန်း — '||v.unit_my||'၊ ဘာသာစုံနည်းဗျူဟာ၊ စစ်ဆေးမှုနှင့် ဆရာစစ်ဆေးသည့် အိမ်စာ ပါဝင်သည်။',description_en='HSK 4 '||lower(v.skill_en)||' course covering '||lower(v.unit_en)||', with multilingual strategy notes, assessment and instructor-reviewed assignment.'where id=product;
 end loop;
end$$;
