import LegalPage, { LegalSection } from "@/components/LegalPage";
import { CONTACT_EMAILS } from "@/lib/contactEmails";

const content: Record<string, { title: string; summary: string; updated: string; sections: LegalSection[] }> = {
  zh: { title: "退款政策", summary: "本政策说明 BurmeseBridge 课程、会员、实体卡和其他付费服务的退款处理规则。", updated: "2026年9月5日", sections: [
    { title: "1. 适用范围", paragraphs: ["本政策适用于 BurmeseBridge 网站内的课程、会员、学习资料、人工审核服务、实体学生证/教师证申请及其他付费项目。购买或提交付款审核前，你必须阅读并同意购买页面显示的规则和本退款政策。"] },
    { title: "2. 数字课程与会员", paragraphs: ["课程、会员和数字资料开通、下载、观看、使用或获得访问权限后，原则上不支持因个人改变主意、误选课程、时间安排变化、未充分阅读说明或学习效果预期不同而退款。数字内容一旦开通即可能被复制、观看或消费，因此平台需要保护教师、作者和平台的合法权益。"] },
    { title: "3. 可申请退款或人工复核的情形", paragraphs: ["在不排除适用法律强制性权利的前提下，以下情形可以联系平台申请退款、补开权限或人工复核。平台会根据付款记录、使用记录、课程开通记录和支付渠道规则处理。"], items: ["重复扣款或重复付款。", "未经授权的交易，并能提供支付渠道、银行或相关机构的证明。", "付款成功但平台未能在合理时间内开通相应服务。", "平台无法继续提供已购买的核心服务，且没有提供合理替代方案。", "用户误付到错误账户、金额明显错误或币种错误，且款项尚未用于开通服务。", "适用法律或支付渠道规则要求退款、撤销或争议处理。"] },
    { title: "4. 不予退款的常见情形", paragraphs: ["以下情形通常不支持退款，但你仍可以联系平台说明情况，平台可根据事实决定是否提供补偿、延期、换课或其他善意处理。"], items: ["账号已获得课程、会员或资料访问权限并已经使用。", "用户因个人原因、学习计划变化、网络环境、设备问题或未阅读课程介绍而要求退款。", "用户违反服务条款，例如共享账号、转售课程、代购后分发、拼单倒卖、录屏传播、批量截图外传、公开下载链接、上传到公共网盘或仓库、绕过 Mux 签名播放或其他访问控制、提交虚假付款凭证。", "实体卡、NFC 卡或定制材料已进入制作、寄送或第三方服务处理流程。", "第三方支付渠道、汇款服务或银行收取的手续费、汇率差额或跨境费用。"] },
    { title: "5. 实体卡、NFC 卡与身份认证", paragraphs: ["学生证、教师证、作者认证、KYC 或实体卡只证明 BurmeseBridge 私立学习平台内部的学习、教学或审核状态，不代表任何政府部门、政府学校、大学、考试机构或官方资格。实体卡或 NFC 卡一旦制作、个性化写入、寄送或交由第三方处理，通常不支持因个人原因退款。若平台未制作或未提交处理，可联系平台取消或修改申请。"] },
    { title: "6. 申请方式与处理时间", paragraphs: [`请在发现问题后尽快通过网站反馈页面或 ${CONTACT_EMAILS.support} 联系平台，并提供账号邮箱、订单或付款参考号、付款截图、问题说明和可核验凭证。一般退款或复核请求建议在付款后 7 天内提出；重复扣款、未授权交易或法律另有规定的情形不受此建议时限限制。平台会尽量在 7 个工作日内回复，复杂案件可能需要更长时间。`] },
    { title: "7. 退款方式", paragraphs: ["若退款被批准，平台通常会按原支付路径或双方确认的合理方式退回。到账时间取决于银行、支付渠道、汇款服务或区块链网络等第三方处理。平台不保证第三方手续费、汇率损失或网络手续费可退回，除非适用法律或支付渠道规则另有要求。"] },
    { title: "8. 滥用、侵权与追责", paragraphs: ["平台可拒绝明显滥用、欺诈、伪造凭证、恶意争议、重复拒付或违反条款的退款请求，并可限制账号、撤销课程访问、冻结认证、保存必要证据或依法向支付渠道、权利人及有关机构报告。若转卖、盗版传播、破解、爬取、共享账号或其他不当行为造成损失，平台保留要求停止侵害、删除传播内容、赔偿损失、承担合理维权成本并依法追究责任的权利。"] },
    { title: "9. 联系", paragraphs: [`退款、付款异常或消费争议请联系 ${CONTACT_EMAILS.support}。平台可能要求验证账号所有权和付款真实性后再处理。`] },
  ] },
  my: { title: "ငွေပြန်အမ်းရေး မူဝါဒ", summary: "BurmeseBridge သင်တန်း၊ membership၊ physical card နှင့် paid service များအတွက် refund စည်းမျဉ်းများ။", updated: "၂၀၂၆ စက်တင်ဘာ ၅", sections: [
    { title: "၁။ သက်ဆိုင်သည့်အရာများ", paragraphs: ["ဤမူဝါဒသည် BurmeseBridge ရှိ သင်တန်း၊ membership၊ digital learning material၊ manual review service၊ student/teacher card နှင့် အခြား paid service များနှင့် သက်ဆိုင်ပါသည်။ ဝယ်ယူခြင်းမပြုမီ purchase rules နှင့် refund policy ကို ဖတ်ရှုပြီး သဘောတူရပါမည်။"] },
    { title: "၂။ Digital သင်တန်းနှင့် Membership", paragraphs: ["သင်တန်း၊ membership သို့မဟုတ် digital material အသုံးပြုခွင့် ဖွင့်ပြီး၊ download လုပ်ပြီး၊ ကြည့်ရှု/အသုံးပြုပြီးနောက် ကိုယ်ပိုင်စိတ်ပြောင်းခြင်း၊ သင်တန်းမှားရွေးခြင်း၊ အချိန်မရှိခြင်း သို့မဟုတ် မျှော်လင့်ချက်မတူခြင်းကြောင့် refund မပေးနိုင်ပါ။ Digital content သည် ဖွင့်ပြီးသည်နှင့် ကြည့်ရှု၊ ကူးယူ သို့မဟုတ် အသုံးပြုနိုင်သောကြောင့် teacher၊ author နှင့် platform ၏ အခွင့်အရေးကို ကာကွယ်ရန်လိုအပ်ပါသည်။"] },
    { title: "၃။ Refund သို့မဟုတ် Review တောင်းနိုင်သောအခြေအနေ", paragraphs: ["သက်ဆိုင်ရာဥပဒေအရ ရရှိနိုင်သော အခွင့်အရေးများကို မဖယ်ရှားဘဲ အောက်ပါအခြေအနေများတွင် platform သို့ ဆက်သွယ်ပြီး refund၊ access ပြန်ဖွင့်ခြင်း သို့မဟုတ် manual review တောင်းနိုင်ပါသည်။"], items: ["ငွေထပ်မံကောက်ခံခြင်း သို့မဟုတ် နှစ်ကြိမ်ပေးချေခြင်း။", "ခွင့်မပြုထားသော payment ဖြစ်ကြောင်း bank/payment provider အထောက်အထားရှိခြင်း။", "ငွေပေးပြီးနောက် သင့်လျော်သောအချိန်အတွင်း service မဖွင့်ပေးနိုင်ခြင်း။", "Platform က ဝယ်ယူထားသော core service ကို ဆက်မပေးနိုင်ခြင်း။", "မှားယွင်းသော account သို့မဟုတ် မှားယွင်းသောငွေပမာဏ ပေးမိပြီး service မဖွင့်ရသေးခြင်း။", "ဥပဒေ သို့မဟုတ် payment channel စည်းမျဉ်းအရ refund/chargeback လိုအပ်ခြင်း။"] },
    { title: "၄။ ပုံမှန်အားဖြင့် Refund မရသောအခြေအနေ", paragraphs: ["အောက်ပါအခြေအနေများတွင် ပုံမှန်အားဖြင့် refund မပေးနိုင်ပါ။ သို့သော် platform သည် အခြေအနေအပေါ်မူတည်၍ extension၊ course change သို့မဟုတ် အခြားကူညီမှုကို စဉ်းစားနိုင်ပါသည်။"], items: ["သင်တန်း၊ membership သို့မဟုတ် material အသုံးပြုခွင့် ရရှိပြီး အသုံးပြုပြီးခြင်း။", "ကိုယ်ပိုင်အကြောင်းပြချက်၊ network/device problem သို့မဟုတ် course description မဖတ်ခြင်းကြောင့် refund တောင်းခြင်း။", "Account sharing၊ course resale၊ proxy purchase distribution၊ group-buy resale၊ screen recording distribution၊ mass screenshot sharing၊ public download link၊ public cloud/repository upload၊ Mux signed playback bypass သို့မဟုတ် access control bypass၊ payment proof အတု တင်ခြင်း။", "Physical card၊ NFC card သို့မဟုတ် custom material ကို ထုတ်လုပ်/ပို့ဆောင်/third-party process စတင်ပြီးခြင်း။", "Bank/payment/remittance fee၊ exchange-rate difference သို့မဟုတ် network fee။"] },
    { title: "၅။ Card၊ NFC နှင့် Identity Verification", paragraphs: ["Student card၊ teacher card၊ author verification၊ KYC နှင့် physical card များသည် BurmeseBridge private learning platform အတွင်း learning/teaching/review status ကိုသာ ပြသပြီး အစိုးရ၊ အစိုးရကျောင်း၊ တက္ကသိုလ် သို့မဟုတ် official qualification မဟုတ်ပါ။ Physical/NFC card ကို ထုတ်လုပ်၊ personalize၊ ပို့ဆောင် သို့မဟုတ် third-party process စတင်ပြီးပါက ကိုယ်ပိုင်အကြောင်းပြချက်ဖြင့် refund မရနိုင်ပါ။"] },
    { title: "၆။ တောင်းဆိုပုံနှင့် အချိန်", paragraphs: [`ပြဿနာတွေ့ပါက website feedback page သို့မဟုတ် ${CONTACT_EMAILS.support} မှတဆင့် account email၊ order/payment reference၊ payment proof နှင့် ပြဿနာရှင်းလင်းချက် ပေးပို့ပါ။ ပုံမှန်အားဖြင့် payment ပြုလုပ်ပြီး ၇ ရက်အတွင်း ဆက်သွယ်ရန် အကြံပြုပါသည်။ Unauthorized transaction၊ duplicate payment သို့မဟုတ် ဥပဒေအရ ကာကွယ်ထားသောအခြေအနေများတွင် ဤအကြံပြုချိန်ကန့်သတ်ချက် မသက်ဆိုင်နိုင်ပါ။`] },
    { title: "၇။ Refund ပြန်ပေးပုံ", paragraphs: ["Refund အတည်ပြုပါက မူလ payment path သို့မဟုတ် နှစ်ဖက်သဘောတူသည့်နည်းလမ်းဖြင့် ပြန်ပေးနိုင်ပါသည်။ ရောက်ရှိချိန်သည် bank၊ payment provider၊ remittance service သို့မဟုတ် blockchain network စသည်တို့အပေါ် မူတည်ပါသည်။ Third-party fee၊ exchange loss သို့မဟုတ် network fee ကို platform က အာမမခံပါ။"] },
    { title: "၈။ အလွဲသုံးစားမှု၊ infringement နှင့် legal responsibility", paragraphs: ["လိမ်လည်မှု၊ proof အတု၊ malicious dispute၊ repeated chargeback သို့မဟုတ် terms violation ရှိပါက platform သည် refund ကို ငြင်းပယ်နိုင်ပြီး account restriction၊ access revocation၊ verification freeze၊ evidence retention သို့မဟုတ် သက်ဆိုင်ရာအဖွဲ့များထံ report ပြုလုပ်နိုင်သည်။ Course resale၊ piracy distribution၊ cracking၊ scraping၊ account sharing သို့မဟုတ် အခြား improper conduct ကြောင့် loss ဖြစ်ပါက platform သည် stop infringement၊ content deletion၊ compensation၊ reasonable enforcement cost နှင့် legal responsibility ကို တောင်းဆိုနိုင်သည်။"] },
    { title: "၉။ ဆက်သွယ်ရန်", paragraphs: [`Refund၊ payment issue သို့မဟုတ် consumer dispute များအတွက် ${CONTACT_EMAILS.support} သို့ ဆက်သွယ်ပါ။ Platform သည် account ownership နှင့် payment truthfulness ကို စစ်ဆေးနိုင်ပါသည်။`] },
  ] },
  en: { title: "Refund Policy", summary: "This policy explains how BurmeseBridge handles refunds for courses, memberships, physical cards, and other paid services.", updated: "September 5, 2026", sections: [
    { title: "1. Scope", paragraphs: ["This policy applies to BurmeseBridge courses, memberships, learning materials, manual review services, physical student/teacher card requests, and other paid services. Before purchasing or submitting a payment review, you must read and agree to the purchase rules and this refund policy."] },
    { title: "2. Digital courses and memberships", paragraphs: ["After a course, membership, or digital material is activated, downloaded, viewed, used, or access is granted, change-of-mind refunds are generally unavailable. This includes choosing the wrong course, schedule changes, not reading the course description, or expectations about learning outcomes. Digital content can be consumed or copied once access is opened, so the platform must protect teachers, authors, and the service."] },
    { title: "3. When refunds or manual review may be requested", paragraphs: ["Without excluding any mandatory rights under applicable law, you may contact us for a refund, restored access, or manual review in the following cases. We review payment records, access logs, service records, and payment-channel rules."], items: ["Duplicate charging or duplicate payment.", "An unauthorised transaction supported by evidence from a bank, payment provider, or relevant institution.", "Payment was successful but the platform did not provide access within a reasonable time.", "The platform cannot continue providing the purchased core service and no reasonable alternative is offered.", "Payment was sent to the wrong account, the amount was clearly wrong, or the currency was wrong, and service access has not been activated.", "Applicable law or payment-channel rules require refund, cancellation, chargeback, or dispute handling."] },
    { title: "4. Common non-refundable cases", paragraphs: ["The following cases are usually not refundable, although the platform may decide whether to offer an extension, course change, credit, or other goodwill remedy based on the facts."], items: ["The account has received and used course, membership, or material access.", "The request is based on personal reasons, schedule changes, network/device issues, or not reading the course information.", "The user violated the Terms, including account sharing, course resale, proxy-purchase distribution, group-buy resale, recording/distribution, mass screenshot sharing, public download links, uploads to public cloud or repositories, bypassing Mux signed playback or other access controls, or submitting false payment proof.", "A physical card, NFC card, or customised material has entered production, shipping, or third-party processing.", "Third-party bank, payment, remittance, exchange-rate, or network fees."] },
    { title: "5. Physical cards, NFC cards, and identity verification", paragraphs: ["Student IDs, teacher IDs, author verification, KYC, physical cards, and NFC cards only confirm internal learning, teaching, or review status inside the private BurmeseBridge platform. They are not government documents, government-school records, university credentials, examination certificates, or official qualifications. Once a physical or NFC card is produced, personalised, shipped, or submitted to a third-party processor, it is usually not refundable for personal reasons."] },
    { title: "6. How to request review", paragraphs: [`Contact us through the website feedback page or ${CONTACT_EMAILS.support} as soon as you notice a problem. Include your account email, order or payment reference, payment proof, a clear explanation, and verifiable evidence. We recommend submitting ordinary refund requests within 7 days after payment. Duplicate charges, unauthorised transactions, and rights required by law or payment-channel rules may not be limited by this recommendation. We aim to respond within 7 business days, although complex cases may take longer.`] },
    { title: "7. Refund method", paragraphs: ["If a refund is approved, we normally return it through the original payment route or another reasonable method confirmed by both sides. Arrival time depends on third-party banks, payment providers, remittance services, or blockchain networks. Unless applicable law or payment-channel rules require otherwise, we do not guarantee that third-party fees, exchange-rate losses, or network fees can be returned."] },
    { title: "8. Abuse, infringement, and responsibility", paragraphs: ["We may reject refund requests involving abuse, fraud, forged evidence, malicious disputes, repeated chargebacks, or Terms violations. We may restrict the account, revoke access, freeze verification, preserve necessary evidence, or lawfully report the matter to payment providers, rights holders, or competent authorities. If resale, piracy, cracking, scraping, account sharing, or other improper conduct causes losses, we reserve the right to require the user to stop the infringement, remove distributed content, compensate losses, cover reasonable enforcement costs, and face legal responsibility where applicable."] },
    { title: "9. Contact", paragraphs: [`For refunds, payment issues, or consumer disputes, contact ${CONTACT_EMAILS.support}. We may verify account ownership and payment authenticity before processing a request.`] },
  ] },
};

export default async function RefundPolicyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return <LegalPage locale={locale} {...(content[locale] || content.en)} />;
}
